<?php if(Mage::getStoreConfig('detailedreview/social_share_optios/share_review_to_pinterest') && Mage::getStoreConfig(MageWorkshop_ReviewWall_Helper_Data::REVIEWWALL_XML_PATH_TEMPLATE_ID) == 2): ?>
    <?php
        $review = $this->getReview();
        $shareUrl = $this->getShareUrl();
        $product = $review->getProduct();
        $image = $review->getImage();
        $fullSizeImage = substr($image, strpos($image, 'detailedreview'));
    ?>
    <?php if ($review && $shareUrl ): ?>

        <div class="drw-share-pinterest">
        <a href="<?php echo 'https://pinterest.com/pin/create/link/?url=' . urlencode($shareUrl) . '&description=' . $product->getName() . '&media=' . Mage::getBaseUrl('media') . $fullSizeImage; ?>" class="link-pinterest" title="<?php echo $this->__('Share on Pinterest'); ?>" target="_blank"  data-social-type="pinterest"></a>
    </div>
    <?php endif; ?>
<?php endif; ?>
