<?php
$title =  get_field('setting_style_title','option');
$description =  get_field('setting_style_description','option');
$bottomLabel =  get_field('setting_style_bottom_label','option');
$bottomLink =  get_field('setting_style_bottom_link','option');
$tabs = get_field('setting_style_section','option');
$newtab = '';
$catLink = "javascript:void(0);";
if($bottomLink){
    $newtab = 'target="_blank"';
    $catLink = check_custom_settingStyle($bottomLink);
} ?>
<?php 
if(have_rows('setting_style_section','option')): ?>     
<div class="setting-styles-section">
    <h2><?php echo $title;?></h2>
    <p><?php echo $description;?></p>
    <div class="content-slider"> 
        <div class="line"></div>
        <div id="mySliderTabs">
            <ul>
                <?php $i=1;foreach($tabs as $tab): ?>
                       <?php
                        $tabName = $tab['setting_style_tab_name'];
                        $tabIcon = $tab['setting_tab_icon']['url'];
                       ?>
                       <?php if($i<=2):?>
                        <li class="nav-item nav-item-<?php echo $i;?>"><a href="#<?php echo $tabName; ?>"><span class="name"><?php echo $tabName; ?></span><div class="icon"><img src="<?php echo $tabIcon;?>" alt=""></div></a></li>
                       <?php else:?>
                       <li class="nav-item nav-item-<?php echo $i;?>"><a href="#<?php echo $tabName; ?>"><div class="icon"><img src="<?php echo $tabIcon;?>" alt=""></div><span class="name"><?php echo $tabName; ?></span></a></li>
                       <?php endif;?>
                <?php $i++;endforeach;?>
            </ul>
           <?php foreach($tabs as $tab):?> 
             <?php
                    $tabName = $tab['setting_style_tab_name'];
                    $tabIcon = $tab['setting_tab_icon']['url'];
                    $settingSlider = $tab['setting_style_tab_slider'];
             ?>
            <div id="<?php echo $tabName; ?>">
                <div class="setting-style owl-carousel">
                   <?php 
                    foreach($settingSlider as $slider):
                        $sliderImage =  $slider['setting_slide_image']['url'];
                        $sliderDescription =  $slider['setting_slide_description'];
                        $sliderLabel =  $slider['setting_slide_label'];
                        $sliderLink =  $slider['setting_slide_link'];
                        $newtab1 = '';
                        $sldLink = "javascript:void(0);";
                        if($sliderLink){
                            $newtab1 = 'target="_blank"';
                            $sldLink = check_custom_settingStyle($sliderLink);
                        } ?>                      
                        <div class="item">
                        <div class="title">
                            <div class="icon"><img src="<?php echo $this->getSkinUrl('images/setting-slider/solitare-icon.png'); ?>"></div>
                            <h3><?php echo $tabName;?></h3> </div>
                        <div class="image"><img src="<?php echo $sliderImage; ?>" alt=""></div>
                        <div class="description">
                            <p><?php echo $sliderDescription;?></p> <a href="<?php echo $sldLink;?>" class="readmore"><?php echo $sliderLabel;?></a>
                        </div>
                        </div>
                    <?php endforeach;?> 
                </div>
            </div>
            <?php endforeach;?> 
          </div>
    </div>     
    <a href="<?php echo $catLink;?>" class="readmore"><?php echo $bottomLabel;?></a>
</div>
<script type="text/javascript">
    var slider = jQuery("#mySliderTabs").sliderTabs({
        autoplay: false,
        mousewheel: false,
        position: "bottom",
        height:700
    });
    
    jQuery('.setting-style').owlCarousel({
        loop:false,
        margin:0,
        items:1,
        nav:false,
        dots:true,        
        responsiveClass:true,
        mouseDrag: false,
        freeDrag: false
    })
    
</script>
<?php
    function check_custom_settingStyle($arglink)
    {
        $httpPost = strpos($arglink,'http');
        if(strlen($arglink)==0)
        {
            $link = 'javascript:;';
        }
        elseif(strlen($httpPost)==0)
        {
           $link = 'http://'.$arglink;
        }
        else
        {
           $link = $arglink;
        }
        return $link;
    }
?>
<?php endif; ?>
