<?php
/** @var MageWorkshop_CommentOnReview_Block_Reply_Item $this */

/** @var MageWorkshop_DetailedReview_Model_Review $newReply */
$newReply = $this->getNewReply()->getFirstItem();

$newReplyID = $newReply->getId();

$enableClientTimezone = Mage::getStoreConfig('detailedreview/datetime_options/enable_to_set_timezone');

$dateFormat = $enableClientTimezone
    ? Mage::getStoreConfig('detailedreview/datetime_options/date_format')
    : 'd/M/Y';
$timeFormat = $enableClientTimezone
    ? Mage::getStoreConfig('detailedreview/datetime_options/time_format')
    : 'h:m ' . Zend_Date::MERIDIEM;

$isLoggedIn = Mage::getSingleton('customer/session')->isLoggedIn();
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'mageworkshop' . DS . 'commentonreview' . DS ;

/* TODO Refactoring */
$detail = '<span class="reply-comment-nickname" contenteditable="false">' . preg_replace("/\s/", '</span> ', str_replace( chr( 194 ) . chr( 160 ), ' ', $newReply->getDetail()), 1);

?>
<li id="reply-<?php echo $newReplyID?>"  class="reply">
    <ul class="reply-wrap">
        <li class="avatar">
            <?php if ($newReply->getCustomerId()): ?>
                <span class="review-img customer-image" title="<?php echo $this->__('Customer'); ?>"></span>
            <?php else: ?>
                <span class="review-img guest-image" title="<?php echo $this->__('Guest'); ?>"></span>
            <?php endif; ?>
        </li>
        <li class="reply-info">
            <div class="reply-author-date">
                <span class="reply-author title"><?php echo $newReply->getNickname(); ?></span>

                <input type="hidden" class="review-id" name="review-id" value="<?php echo $newReplyID; ?>">

                <span class="reply-date-wrap">
                    <?php $date = new Zend_Date($newReply->getCreatedAt()); ?>
                    <small class="date review-date reply-date" data-utc="<?php echo $newReply->getCreatedAt(); ?>" data-format="<?php echo $dateFormat; ?>"><?php echo $date->get($dateFormat); ?></small>
                    <small class="hide-date-review" data-utc="<?php echo $newReply->getCreatedAt(); ?>" data-format="<?php echo $dateFormat; ?>"><?php echo $date->get(str_replace('D', 'd', $dateFormat)); ?></small>
                    <small class="date review-date reply-date" data-utc="<?php echo $newReply->getCreatedAt(); ?>" data-format="<?php echo $timeFormat; ?>"><?php echo $date->get($timeFormat); ?></small>
                </span>
            </div>
            <div class="reply-data">
                <span>
                    <span class="reply-detail">
                        <?php echo $detail; ?>
                    </span>
                </span>
            </div>
            <div class="reply-action-wrapper">
                <div class="reply-action">
                    <span class="reply-button reply-reply"><?php echo $this->__('Reply'); ?></span>
                </div>
                <div class="reply-helpful">
                    <form class="helpful-form" action="<?php echo $this->getUrl('detailedreview/helpful/vote', array('_secure' => Mage::app()->getStore()->isCurrentlySecure())); ?>" method="post" >
                        <div class="js-helpful-voting">
                            <input type="hidden" name="review_id" value="<?php echo $newReply->getId()?>"/>
                            <div class="rating-wrapper">
                                <a class="review-vote-rating helpful-btn"  title="<?php echo $this->__('Helpful')?>" href="#login-dialog-block"></a>
                                <span class="helpful-qty voting-qty"><?php echo $newReply->getCountHelpful() ?></span>
                            </div>
                            <div class="rating-wrapper">
                                <a class="review-vote-rating unhelpful-btn" title="<?php echo $this->__('Unhelpful')?>" href="#login-dialog-block"></a>
                                <span class="unhelpful-qty voting-qty"><?php echo $newReply->getCountUnhelpful() ?></span>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </li>
        <?php if($isLoggedIn): ?>
            <li>
                <?php $complaintButton = $this->getChild('mageworkshop.detailedreview.review.complaint.button'); ?>
                <?php if ($complaintButton): ?>
                    <?php $complaintButton->setData('record_id', $newReply->getId()); ?>
                    <?php echo $this->getChildHtml('mageworkshop.detailedreview.review.complaint.button', false); ?>
                <?php endif; ?>
            </li>
        <?php endif; ?>
    </ul>
</li>
