<?php
/** @var MageWorkshop_CommentOnReview_Block_Reply $this */
$replies = $this->getReviewReplies();

$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'mageworkshop' . DS . 'commentonreview' . DS ;

$enableClientTimezone = Mage::getStoreConfig('detailedreview/datetime_options/enable_to_set_timezone');

$dateFormat = $enableClientTimezone
    ? Mage::getStoreConfig('detailedreview/datetime_options/date_format')
    : 'd/M/Y';
$timeFormat = $enableClientTimezone
    ? Mage::getStoreConfig('detailedreview/datetime_options/time_format')
    : 'h:m ' . Zend_Date::MERIDIEM;

$isLoggedIn = Mage::getSingleton('customer/session')->isLoggedIn();
$showElements = Mage::getStoreConfig(MageWorkshop_CommentOnReview_Helper_Data::COMMENT_XML_PATH_EXPANDER);
$replyCount = count($replies);

$commentFromAdmin = false;
?>

<div class="clear"></div>
<div class="reply-list-wrap">
    <div class="reply-action">
        <span class="reply-button reply-review">
            <?php echo $this->__('Reply'); ?>
        </span>
    </div>
    <ul class="reply-list" >
        <?php
            /** @var MageWorkshop_DetailedReview_Model_Review $reply */
            foreach($replies as $index => $reply):
                $replyId = $reply->getId();
            ?>
                <li id="reply-<?php echo $replyId?>" class="reply <?php echo ($index < $showElements) ? 'expanded' : '' ?>">
                <ul class="reply-wrap">
                    <li class="avatar">
                        <?php if ($reply->getCustomerId()): ?>
                            <span class="review-img customer-image" title="<?php echo $this->__('Customer'); ?>"></span>
                        <?php else: ?>
                            <span class="review-img guest-image" title="<?php echo $this->__('Guest'); ?>"></span>
                        <?php endif; ?>
                    </li>
                    <li class="reply-info">
                        <div class="reply-author-date">
                            <span class="reply-author title"><?php echo $reply->getNickname()?></span>
                            <input type="hidden" class="review-id" name="review-id" value="<?php echo $replyId; ?>">

                            <span class="reply-date-wrap">
                                <?php $date = new Zend_Date($reply->getCreatedAt());
                                      $replyDate = $reply->getCreatedAt(); ?>
                                <small class="date review-date reply-date" data-utc="<?php echo $replyDate; ?>" data-format="<?php echo $dateFormat; ?>"><?php echo $date->get($dateFormat); ?></small>
                                <small class="hide-date-review" data-utc="<?php echo $replyDate; ?>" data-format="<?php echo $dateFormat; ?>"><?php echo $date->get(str_replace('D', 'd', $dateFormat)); ?></small>
                                <small class="date review-date reply-date" data-utc="<?php echo $replyDate; ?>" data-format="<?php echo $timeFormat; ?>"><?php echo $date->get($timeFormat); ?></small>
                            </span>
                        </div>
                        <div class="reply-detail ">
                            <?php echo Mage::getStoreConfig(MageWorkshop_CommentOnReview_Helper_Data::COMMENT_XML_PATH_NICKNAME_SUFFIX) . substr($reply->getDetail(), 1) ?>
                        </div>

                        <div class="reply-action-wrapper">
                            <div class="reply-action">
                                <span class="reply-button reply-reply"><?php echo $this->__('Reply'); ?></span>
                            </div>
                            <div class="reply-helpful">
                                <form class="helpful-form" action="<?php echo $this->getUrl('detailedreview/helpful/vote', array('_secure' => Mage::app()->getStore()->isCurrentlySecure())); ?>" method="post" >
                                    <div class="js-helpful-voting">
                                        <input type="hidden" name="review_id" value="<?php echo $reply->getId()?>"/>
                                        <div class="rating-wrapper">
                                            <a class="review-vote-rating helpful-btn"  title="<?php echo $this->__('Helpful')?>" href="#login-dialog-block"></a>
                                            <span class="helpful-qty voting-qty"><?php echo $reply->getCountHelpful() ?></span>
                                        </div>
                                        <div class="rating-wrapper">
                                            <a class="review-vote-rating unhelpful-btn" title="<?php echo $this->__('Unhelpful')?>" href="#login-dialog-block"></a>
                                            <span class="unhelpful-qty voting-qty"><?php echo $reply->getCountUnhelpful() ?></span>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <?php if($reply->getResponse()): ?>
                            <div class="admin-response">
                                <?php echo $reply->getResponse();
                                if($index >= $showElements && !$commentFromAdmin) {
                                    $commentFromAdmin = true;
                                }
                                ?>
                            </div>
                        <?php endif; ?>
                    </li>
                    <?php if ($isLoggedIn): ?>
                        <li>
                            <?php $complaintButton = $this->getChild('mageworkshop.detailedreview.review.complaint.button'); ?>
                            <?php if ($complaintButton): ?>
                                <?php $complaintButton->setData('record_id', $reply->getId()); ?>
                                <?php echo $this->getChildHtml('mageworkshop.detailedreview.review.complaint.button', false); ?>
                            <?php endif; ?>
                        </li>
                    <?php endif; ?>
                </ul>
            </li>
        <?php endforeach; ?>
    </ul>
    <?php $show = ($showElements < $replyCount)? 'show' : ''; ?>
    <div class="reply-visible reply-expander expand <?php echo $show; ?>">
        <span class="reply-show-hide expand">
            <?php echo $this->__('Show more comments'); ?>
            (<span class="reply-count"><?php echo $replyCount - $showElements; ?></span>)
        </span>
        <span class="reply-show-hide collapse">
            <?php echo $this->__('Hide comments'); ?>
        </span>
        <?php if($commentFromAdmin): ?>
            <i class="admin-response-icon" title="<?php echo $this->__('Administrator response');?>"></i>
        <?php endif; ?>
    </div>
</div>
