<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_GiftCard
 */
?>
<?php $_source  = $this->getSource() ?>
<?php $this->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getAmGiftCardsAmount()): ?>
	<?php $_giftCards = unserialize($_source->getAmGiftCards()); ?>
	<?php $_giftCards = $_giftCards ? $_giftCards : array(); ?>
	<?php foreach ($_giftCards as $_card): ?>
		<?php $_baseAmount = $_card['ba']; ?>
		<?php $_amount = $_card['a']; ?>
		<?php $_code = $_card['c']; ?>

		<tr>
			<td class="label"><?php echo Mage::helper('amgiftcard')->__('Gift Card (%s)', $_code) ?></td>
			<td>
				<?php echo $this->displayPrices(-$_baseAmount, -$_amount); ?>
			</td>
		</tr>
	<?php endforeach; ?>
<?php endif; ?>