<?php
$diamondCut = array();
$title =  get_field('home_diamond_style_title','option');
$label =  get_field('home_diamond_label','option');
$link =  get_field('home_diamond_link','option');
$newtab = '';
$catLink = "javascript:void(0);";
if($link){
    $newtab = 'target="_blank"';
    $catLink = check_custom_diamondlink($link);
} ?>
<?php 
if(have_rows('home_diamond_style','option')): 
    while(have_rows('home_diamond_style','option')): the_row(); 
        $diamondName = get_sub_field('home_diamond_style_label','option');
        $diamondLink = get_sub_field('home_diamond_style_link','option');
        $diamondImage = get_sub_field('home_diamond_style_image','option');
        $diamondText = get_sub_field('home_diamond_style_short_text','option');
        $diamondCut[]= array($diamondName,$diamondLink,$diamondImage,$diamondText);  
    endwhile;
    $diamondCut = array_chunk($diamondCut,2);?>
<section class="diamond-cuts-section">
    <div class="description">
        <h2><?php echo $title;?></h2>
    </div>
    <div class="container">
    <div class="row">
        <ul> 
        <?php $i = 0; 
            $class = "left-block text-left col-sm-4";
            foreach($diamondCut as $diamond):  ?>  
            <?php if($i == 0): $class = "left-block text-left col-sm-4";?>
            <?php elseif($i == 1): $class = "right-block pull-right col-sm-4 text-center";?>
            <?php else: $class = "middle-block col-sm-4 text-right"; ?>
            <?php endif; ?>
            
                
                    <?php foreach($diamond as $cut):
                         $dcLink = "javascript:void(0);";
                         $diamondStyle = $cut[0];
                         $diamondLink = $cut[1];
                         if($diamondLink): $dcLink = check_custom_diamondlink($diamondLink); endif;
                         $image = Mage::helper('latestblogpost')->getResizedHomeNewsImage($cut[2]["url"], 187, 185,"home-diamond");    
                         $diamondText = $cut[3];?> 
                    <li class="item">
                        <div class="image">
                            <img src="<?php echo $image;?>" alt="" />
                        </div>
                        <div class="details">
                            <h3><a href="<?php echo $dcLink;?>" title="<?php echo $diamondStyle;?>"><?php echo $diamondStyle;?></a></h3>
                            <p><?php echo $diamondText;?></p>
                        </div>
                    </li>
                    <?php if($i == 2):?>
                        
                    <?php endif;?>
                    <?php endforeach;?>
               
            
        <?php $i++; endforeach;?>    
         </ul>    
         <li class="viewall-links">
                            <a href="<?php echo $catLink;?>" title="<?php echo $label;?>" <?php echo $newtab;?>><?php echo $label;?></a>
                        </li>    
        </div>
    </div>
</section>
<?php endif;?>
<?php
    function check_custom_diamondlink($arglink)
    {
        $httpPost = strpos($arglink,'http');
        if(strlen($arglink)==0)
        {
            $link = 'javascript:;';
        }
        elseif(strlen($httpPost)==0)
        {
           $link = 'http://'.$arglink;
        }
        else
        {
           $link = $arglink;
        }
        return $link;
    }
?>
