<?php $_productCollection = $this->getMatchingBandCollection();
      $matchingBandCollection = $this->getTotalMatchingBand();   
      $TotalMatchingBand = count($matchingBandCollection);
      $_helper = $this->helper('catalog/output');
?>
<div class="matchingband-top-description">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('matching-wedding-band')->toHtml();?>
</div>


<div class="matching-tabs">
    <ul class="m-tabs">
        <li class="current" data-tab="engagement-ring">
            <div class="icon"><img src="<?php echo $this->getSkinUrl('images/matching-band-icon-1.png'); ?>" alt=""></div>
            <div class="name">
                <span class="number"><strong><?php echo $this->__('1');?></strong></span>
                <span class="tab-name"><?php echo $this->__('CHOOSE YOUR <strong>ENGAGEMENT RING</strong>');?></span>
            </div>
        </li>
        <li data-tab="matching-wedding-band">
            <div class="icon"><img src="<?php echo $this->getSkinUrl('images/matching-band-icon-2.png'); ?>" alt=""></div>
            <div class="name">
                <span class="number"><strong><?php echo $this->__('2');?></strong></span>
                <span class="tab-name"><?php echo $this->__('CHOOSE YOUR <strong>MATCHING WEDDING Band</strong>');?></span>
            </div>
        </li>
    </ul>
     <div id="engagement-ring" class="tab-content current">
<?php if (!count($_productCollection)): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<?php $_collectionSize = count($_productCollection) ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
        <ul class="products-grid products-grid--max-4-col" >
            <?php $k = 1; $i=0; foreach ($_productCollection as $product): ?> 
                 <?php $_product = Mage::getModel('catalog/product')->load($product['pid']); ?>
                <li class="item last<?php /*if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif;*/ ?>">
                    <a href="<?php echo Mage::getUrl('weddingband/'.$_product->getUrlKey());?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image" data-productid="<?php echo $_product->getId();?>">
                        <?php $_imgSize = 260; ?>
                        <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                             src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                             alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    </a>
                    <div class="product-info">
                        <h2 class="product-name">
                            <a href="<?php echo Mage::getUrl('weddingband/'.$_product->getUrlKey());?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                        </h2>
                        <?php
                        if ($this->getChild('name.after')) {
                            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                            foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                $_nameAfterChild->setProduct($_product);
                                echo $_nameAfterChild->toHtml();
                            }
                        }
                        ?>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                        <?php if($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php endif; ?>
                        <div class="actions">
                            <?php /* ?><?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                                <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                                <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                            <?php */ ?>
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"></a></li>
                                <?php endif; ?>
                                <li><a href="#custom-popup" class="popop-product" data-fancybox data-productId="<?php echo $_product->getId()?>"><img src="<?php echo $this->getSkinUrl('images/zoom-icon.png'); ?>" width="26" alt=""></a></li>
                            </ul>
                        </div> 
                    </div>
                </li>                
            <?php endforeach ?>
        </ul>
        <input type="hidden" class="total-ring" id="total-ring" value="<?php echo $TotalMatchingBand;?>"/>
        <input type="hidden" class="show-ring" id="show-ring" value="1"/>
        <a href="javascript:void(0);" class="load-more" style="display: none;" title="<?php echo $this->__('Load More');?>">
            <?php echo $this->__('Load More');?>
            <img src="<?php echo $this->getSkinUrl('images/spinner-m.gif');?>" alt="Loader" width="75" style="display:none;" class="loading-icon">
        </a>
       <div id="custom-popup" style="display: none;" class="custom-popup category-popup">
            <div class="loading" style="display: none;"></div>
        </div> 
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>
    </div>
    <div id="matching-wedding-band" class="tab-content"></div>
   </div>
 <form name="matching-band-form" id="matching-band-form" action="" method="post">
    <input type="hidden" class="matching-band-ring" id="matching-band-ring" name="matching-band-ring" value=""/>
 </form>  
    
<script type="text/javascript">
    jQuery(document).ready(function () {
    showLoadmore();
    jQuery(document).on('click','.popop-product',function(){        
        var productId = jQuery(this).attr('data-productId');
        url = '<?php echo $this->getUrl('wizard/index/getpopupproduct');?>';
        jQuery('#custom-popup').hide();
        jQuery("#custom-popup .loading").show();
        jQuery.ajax( {
            url : url,
            dataType : 'html',
            type: 'POST',
            data: {id: productId},
            success : function(response) {
              //alert(response);
                jQuery('#custom-popup .loading').removeClass();
                jQuery('#custom-popup').show();
                jQuery('.custom-popup').html(response);
                setTimeout(function(){ popupSlider(); }, 500);
            }
        });     
    });
   /*
   // Code for SCroll load but not working
   var lastScrollTop = 0;  
   jQuery(document).scroll(function(e){
        var st = jQuery(this).scrollTop();
        if (st > lastScrollTop){
            var scrollAmount = jQuery(document).scrollTop();
            var documentHeight = jQuery(document).height();
            var scrollPercent = (scrollAmount / documentHeight) * 100;
            if(scrollPercent > 80) {
               loadmore();
            }
        }
        lastScrollTop = st;
    });

    function loadmore(){
        var limit = parseInt(jQuery(".show-ring").val());       
        var url = '<?php //echo $this->getUrl('matchingband/index/loadmore');?>';
        jQuery.ajax({
            url : url,
            dataType : 'html',
            type: 'POST',
            data: {limit: limit},
            success : function(response) {
              jQuery(".products-grid").append(response);
               var limit = parseInt(jQuery(".show-ring").val());
               var setpage = limit + 1;
               jQuery(".show-ring").val(setpage);
               showLoadmore();
            }
        });     
    };    */
    jQuery(".product-image").click(function(){
        var productid = jQuery(this).attr('data-productid');
        var url = jQuery(this).attr('href');
        jQuery(".matching-band-ring").val(productid);
        jQuery("#matching-band-form").attr('action',url);
        jQuery("#matching-band-form").submit();
    });
    jQuery('.load-more').click(function(){
        jQuery('.loading-icon').show();
        var limit = parseInt(jQuery(".show-ring").val());        
        var url = '<?php echo $this->getUrl('matchingband/index/loadmore');?>';
        jQuery.ajax({
            url : url,
            dataType : 'html',
            type: 'POST',
            data: {limit: limit},
            success : function(response) {
              jQuery('.loading-icon').hide();
              jQuery(".products-grid").append(response);
               var limit = parseInt(jQuery(".show-ring").val());
               var setpage = limit + 1;
               jQuery(".show-ring").val(setpage);
               showLoadmore();
               
            }
        });     
    });
    
    
    /*tabs*/
    
  /*  jQuery('.matching-tabs li').click(function () { 
            var tab_id = jQuery(this).attr('data-tab');
            jQuery('.matching-tabs li').removeClass('current');
            jQuery('.tab-content').removeClass('current');
            jQuery(this).addClass('current');
            jQuery("#" + tab_id).addClass('current');                    
        })*/
    
    
});    
function showLoadmore(){
        var totalRing = parseInt(jQuery(".total-ring").val());
        var liLength =  parseInt(jQuery(".products-grid > li").length);
        if(liLength < totalRing){
           jQuery(".load-more").show() 
        }else{
            jQuery(".load-more").hide() 
        }
    }
</script>