<?php
$productId = $this->getData('productId');
?>
<section class="sections diamond-section">
    <div class="section-title">
      <h3><?php echo $this->__('<span>Diamond</span> Details');?></h3>
    </div>
    <?php $product =  mage::getModel('catalog/product')->load($productId); //echo '<pre>111';$product->getData(); ?>
    <div class="diamond-type details-diamond-type">
                    <div class="item diamond-item">
                        <div class="content">
                            <h3><?php echo Mage::Helper('wizard')->getAttributeValue('stone_color',$product->getStoneColor());?><?php echo $this->__(' Colour');?></h3>
                            <p><?php echo $this->__('Color may be slightly detectable to the unaided eye, particularly in fancy shapes or diamonds over 1-carat.');?></p>
                        </div>
                        <div class="item-option">
                            <ul>
                                <?php foreach (Mage::Helper('wizard')->getAllOptions('stone_color') as $value) { ?>
                                        <li class="<?php if($value['value'] == $product->getStoneColor()){ echo 'active';} ?>">
                                            <img src="<?php echo $this->getSkinUrl('images/media/dimond1.png');?>">
                                            <img class="colorimg" src="<?php echo $this->getSkinUrl('images/media/dimond1-h.png');?>">
                                            <span><?php echo $value['label'];?></span>
                                        </li>
                                    <?php
                                } ?>
                            </ul>
                        </div>
                    </div>
                    <div class="item caratr-item">
                        <div class="content">
                            <h3><?php echo round($product->getCarat(), 2);?> <?php echo $this->__('Carat');?></h3>
                            <p><?php echo $this->__('The international unit of weight used for measuring diamonds and gemstones, 1 carat is equal to 200 milligrams, or 0.2 grams.');?></p>
                        </div>
                        <div class="item-option ">
                            <ul>
                                <?php for ($i = 0; $i < 7; $i++) { ?>
                                    <li><img src="<?php echo $this->getSkinUrl('images/media/ct-0-25.png');?>"><span><?php echo $i;?><?php echo $this->__('Ct');?></span>
                                    <?php
                                        $caratValue = round($product->getCarat(), 2);
                                        $left = 50;
                                        if($caratValue > $i-0.5 && $caratValue <= $i+0.5){
                                            $whole = floor($caratValue);
                                            $fraction = $caratValue - $whole;
                                            $fraction = explode('.', $fraction);
                                            if(strlen($fraction[1]) == 1){
                                                $fraction[1] = $fraction[1].'0';
                                            }
                                            if($caratValue != $i && $caratValue != $i+0.5){
                                                if($caratValue > $i){
                                                    $left = $fraction[1]+50;
                                                }else{
                                                    $left = $fraction[1]-50;
                                                }
                                            }else if($caratValue == $i+0.5){
                                                $left = 100;
                                            }
                                         ?>
                                        <i style="left: <?php echo $left;?>%"><?php echo $caratValue;?></i>
                                    <?php } ?>
                                </li>
                                <?php } ?>
                            </ul>
                        </div>
                    </div>
                    <div class="item diamond-item clarity-item">
                        <div class="content">
                            <h3><?php echo Mage::Helper('wizard')->getAttributeValue('stone_quality',$product->getStoneQuality());?> <?php echo $this->__('Clarity');?></h3>
                            <p><?php echo $this->__('The international unit of weight used for measuring diamonds &amp; gemstones, 1 carat is equal to 200 milligrams, or 0.2 grams.');?></p>
                        </div>
                        <div class="item-option">
                            <ul>
                                <?php foreach (Mage::Helper('wizard')->getAllOptions('stone_quality') as $value) { ?>
                                        <li class="<?php if($value['value'] == $product->getStoneQuality()){ echo 'active';} ?>"><a href="javascript:void(0);">
                                            <img src="<?php echo $this->getSkinUrl('images/media/clarity.png');?>">
                                            <img class="colorimg" src="<?php echo $this->getSkinUrl('images/media/clarity-h.png');?>">
                                            </a><span><?php echo $value['label'];?></span>
                                        </li>

                                    <?php
                                } ?>
                            </ul>
                        </div>
                    </div>
                    <div class="item diamond-item clarity-item ideal-item">
                        <div class="content">
                            <h3><?php echo Mage::Helper('wizard')->getAttributeValue('stone_cut',$product->getStoneCut());?> <?php echo $this->__('Cut');?></h3>
                            <p><?php echo $this->__('The international unit of weight used for measuring diamonds &amp; gemstones, 1 carat is equal to 200 milligrams, or 0.2 grams.');?></p>
                        </div>
                        <div class="item-option">
                            <ul>
                                <?php foreach (Mage::Helper('wizard')->getAllOptions('stone_cut') as $value) { ?>
                                        <li class="<?php if($value['value'] == $product->getStoneCut()){ echo 'active';} ?>"><a href="javascript:void(0);">
                                            <img src="<?php echo $this->getSkinUrl('images/media/dimond1.png');?>">
                                            <img class="colorimg" src="<?php echo $this->getSkinUrl('images/media/dimond1-h.png');?>">
                                            </a><span><?php echo $value['label'];?></span>
                                        </li>

                                    <?php
                                } ?>
                            </ul>
                        </div>
                    </div>
                </div>  
   <!-- <div class="diamond-type">
      <div class="item diamond-item">
        <div class="content">
          <h3>J Colour</h3>
          <p>Color may be slightly detectable to the unaided eye, particularly in fancy shapes or diamonds over 1-carat.</p>
        </div>
        <div class="item-option">
          <ul>
            <li class="active"><a href="#"><img src="<?php //echo $this->getSkinUrl('images/media/dimond1.png') ?>" /> <img class="colorimg" src="<?php //echo $this->getSkinUrl('images/media/dimond1-h.png') ?>" /></a> <span>J</span></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/media/dimond1.png') ?>" /> <img class="colorimg" src="<?php //echo $this->getSkinUrl('images/media/dimond1-h.png') ?>" /></a> <span>i</span></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/media/dimond1.png') ?>" /> <img class="colorimg" src="<?php //echo $this->getSkinUrl('images/media/dimond1-h.png') ?>" /> </a><span>h</span></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/media/dimond1.png') ?>" /> <img class="colorimg" src="<?php //echo $this->getSkinUrl('images/media/dimond1-h.png') ?>" /></a> <span>g</span></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/media/dimond1.png') ?>" /> <img class="colorimg" src="<?php // echo $this->getSkinUrl('images/media/dimond1-h.png') ?>" /> </a><span>f</span></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/media/dimond1.png') ?>" /> <img class="colorimg" src="<?php //echo $this->getSkinUrl('images/media/dimond1-h.png') ?>" /> </a><span>e</span></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/media/dimond1.png') ?>" /> <img class="colorimg" src="<?php //echo $this->getSkinUrl('images/media/dimond1-h.png') ?>" /> </a> <span>d</span></li>
          </ul>
        </div>
      </div>
      <div class="item caratr-item">
        <div class="content">
          <h3>0.26 Caratr</h3>
          <p>The international unit of weight used for measuring diamonds and gemstones,
1 carat is equal to 200 milligrams, or 0.2 grams. </p>
        </div>
        <div class="item-option ">
          <ul>
            <li class="active"><img src="<?php echo $this->getSkinUrl('images/media/ct-0-25.png') ?>" /><span>0.25 Ct</span>
            <i>0.25</i></li>
            <li><img src="<?php //echo $this->getSkinUrl('images/media/ct-0-5.png') ?>" /><span>0.5 Ct</span> </li>
            <li><img src="<?php //echo $this->getSkinUrl('images/media/ct-0-75.png') ?>" /><span>0.75 Ct</span> </li>
            <li><img src="<?php //echo $this->getSkinUrl('images/media/ct-1.png') ?>" /><span>1 Ct</span> </li>
            <li><img src="<?php //echo $this->getSkinUrl('images/media/ct-1-25.png') ?>" /> <span>1.25 Ct</span></li>
            <li><img src="<?php //echo $this->getSkinUrl('images/media/ct-1-5.png') ?>" /> <span>1.5 Ct</span></li>
            <li><img src="<?php //echo $this->getSkinUrl('images/media/ct-1-75.png') ?>" /> <span>1.75 Ct</span></li>
            <li><img src="<?php //echo $this->getSkinUrl('images/media/ct-2.png') ?>" /><span>2 Ct</span> </li>
          </ul>
        </div>
      </div>
      <div class="item diamond-item clarity-item">
        <div class="content">
          <h3>VS1 Clarity</h3>
          <p>The international unit of weight used for measuring diamonds & gemstones, 1 carat is equal to 200 milligrams, or 0.2 grams.</p>
        </div>
        <div class="item-option">
          <ul>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/media/clarity.png') ?>" /> <img class="colorimg" src="<?php //echo $this->getSkinUrl('images/media/clarity-h.png') ?>" /></a> <span>SL2</span></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/media/clarity.png') ?>" /> <img class="colorimg" src="<?php //echo $this->getSkinUrl('images/media/clarity-h.png') ?>" /> </a><span>SL1</span></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/media/clarity.png') ?>" /> <img class="colorimg" src="<?php //echo $this->getSkinUrl('images/media/clarity-h.png') ?>" /> </a><span>VS2</span></li>
            <li class="active"><a href="#"><img src="<?php //echo $this->getSkinUrl('images/media/clarity.png') ?>" /> <img class="colorimg" src="<?php //echo $this->getSkinUrl('images/media/clarity-h.png') ?>" /> <span>VS1</span></a></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/media/clarity.png') ?>" /> <img class="colorimg" src="<?php //echo $this->getSkinUrl('images/media/clarity-h.png') ?>" /> </a><span>VVS2</span></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/media/clarity.png') ?>" /> <img class="colorimg" src="<?php //echo $this->getSkinUrl('images/media/clarity-h.png') ?>" /> </a><span>VVS1</span></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/media/clarity.png') ?>" /> <img class="colorimg" src="<?php //echo $this->getSkinUrl('images/media/clarity-h.png') ?>" /> </a><span>IF</span></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/media/clarity.png') ?>" /> <img class="colorimg" src="<?php //echo $this->getSkinUrl('images/media/clarity-h.png') ?>" /> </a><span>FL</span></li>
          </ul>
        </div>
      </div>
      <div class="item diamond-item clarity-item ideal-item">
        <div class="content">
          <h3>Ideal Cut</h3>
          <p>The international unit of weight used for measuring diamonds & gemstones, 1 carat is equal to 200 milligrams, or 0.2 grams.</p>
        </div>
        <div class="item-option">
          <ul>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/media/dimond1.png') ?>" /> <img class="colorimg" src="<?php //echo $this->getSkinUrl('images/media/dimond1-h.png') ?>" /></a> <span>Good</span></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/media/dimond1.png') ?>" /> <img class="colorimg" src="<?php //echo $this->getSkinUrl('images/media/dimond1-h.png') ?>" /></a> <span>Very Good</span></li>
            <li class="active"><a href="#"><img src="<?php //echo $this->getSkinUrl('images/media/dimond1.png') ?>" /> <img class="colorimg" src="<?php //echo $this->getSkinUrl('images/media/dimond1-h.png') ?>" /></a> <span>Ideal</span></li>
          </ul>
        </div>
      </div>
    </div>-->
  </section>