<?php

/** @var $this MageWorkshop_ReviewWall_Block_Widget_Wall */

/** @var MageWorkshop_ReviewWall_Model_Review $reviewModel */
$reviewModel = Mage::getModel('reviewwall/review');
$helper = Mage::helper('reviewwall');

/** @var MageWorkshop_DetailedReview_Model_Mysql4_Review_Collection $preparedReviews */
$preparedReviews = $reviewModel->getPreparedReviewsCollection('entity_id');

$items = $preparedReviews->getItems();
?>

<?php if ($preparedReviews->getSize()) : ?>
    <div class="all-review-wall-wrapper">
        <?php echo $this->getChildHtml('searchForm', false); ?>

        <?php echo $this->getChildHtml('totalRating', false); ?>

        <div class="drw-container grid" id="drw-container">
            <div class="drw-grid-sizer"></div>
            <div class="drw-gutter-sizer"></div>
            <?php /**@var MageWorkshop_DetailedReview_Model_Review $_review */ ?>
            <?php foreach ($items as $_review): ?>
                <div class="drw-box drw-grid-item no-image">
                    <a href="<?php echo $_review->getProduct()->getUrlInStore(array('_ignore_category' => true)) . '#rw_'.$_review->getId() ?>" class="drw-title" target='_blank'>
                        <?php echo  ($this->escapeHtml($_review->getTitle()))
                            ? $this->escapeHtml($_review->getTitle())
                            : $this->escapeHtml($_review->getProduct()->getName())
                        ?>
                    </a>
                    <span class='review-by-wrapper'> <?php echo $this->__('Review by') . ' ' . $this->escapeHtml($_review->getNickname()) ?></span>
                    <?php if ($_review->hasRating()) : ?>
                        <?php $rating = $helper->getAverageReviewRating($_review->getRatingVotes()->getItems()); ?>
                        <div class="ratings-table">
                            <div class="rating-box">
                                <div class="rating" style="width:<?php echo $rating; ?>%;"></div>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="drw-item-info">
                        <div class="drw-review-dt" id="<?php echo 'rw_' . $_review->getId(); ?>">
                            <p class="drw-detail">
                                <?php echo Mage::helper('detailedreview')->smartyModifierTruncate(
                                    $this->escapeHtml($_review->getDetail()),
                                    $helper->getCountCharsInReview()
                                ); ?>
                            </p>
                        </div>
                        <div class="clearboth"></div>
                        <div class="social-helpful-wrapper">
                            <div class="drw-review-dd">
                                <?php $this->getChild('socialShare')->setReview($_review); ?>
                                <?php echo $this->getChildHtml('socialShare', false); ?>
                            </div>
                            <?php $this->getChild('helpful')->setReview($_review); ?>
                            <?php echo $this->getChildHtml('helpful', false); ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php
        $nextPage = $preparedReviews->getCurPage(+1);
        $nextPage = $preparedReviews->getCurPage() == $nextPage ? ++$nextPage : $nextPage;
        ?>
        <div id="drw-ajax-load-grid" class="drw-box drw-grid-item" data-next-page="<?php echo $nextPage; ?>" style="display:none;"></div>
        <div id="dialog" title="<?php echo $this->__('Vote Warning'); ?>"><p></p></div>
        <div class="drw-loader">
            <img src="<?php echo $this->getSkinUrl('images/detailedreview/ajax-loader.gif') ?>" />
        </div>
        <div class="drw-next-page" data-next-page="2"></div>
    </div>
<?php else: ?>
    <div class="drw-no-reviews"><?php echo $this->__('Sorry, you don\'t have any reviews or reviews with images'); ?></div>
<?php endif; ?>

<?php echo $this->getChildHtml('js', false); ?>
<?php echo $this->getChildHtml('emailShare', false); ?>
