<?php

/** @var $this MageWorkshop_ReviewWall_Block_Widget_Wall */


/** @var MageWorkshop_ReviewWall_Model_Review $reviewModel */
$reviewModel = Mage::getModel('reviewwall/review');

/** @var MageWorkshop_DetailedReview_Model_Mysql4_Review_Collection $preparedReviews */
$preparedReviews = $reviewModel->getPreparedReviewsCollection($reviewModel::IMAGE_FILTER);
?>

<?php if ($preparedReviews->getSize()) : ?>
    <div class="image-review-wall-wrapper">

        <?php echo $this->getChildHtml('searchForm', false); ?>

        <div class="drw-container grid" id="drw-container">
            <div class="drw-grid-sizer image"></div>
            <div class="drw-gutter-sizer"></div>
            <?php foreach ($preparedReviews as $_review): ?>
                <?php
                    $_product = $_review->getProduct();
                    $image = $_review->getImage();
                ?>
                <div class="drw-box drw-grid-item image">
                    <a href="<?php echo $_product->getUrlInStore(array('_ignore_category' => true)) . '#rw_'.$_review->getId() ?>" target='_blank'>
                        <div class="drw-images-box">
                            <div class="drw-image-review">
                                <img src="<?php echo $image; ?>" alt="" />
                            </div>
                        </div>
                    </a>
                    <div class="drw-item-info">
                        <?php if ($item = $_review->getRatingVotes()->getItems()) : ?>
                            <?php $rating = Mage::helper('reviewwall')->getAverageReviewRating($_review->getRatingVotes()->getItems());?>
                            <div class="ratings-table">
                                <div class="rating-box">
                                    <div class="rating" style="width:<?php echo $rating; ?>%;"></div>
                                </div>
                            </div>
                        <?php endif; ?>
                        <div class="drw-review-dt image" id="<?php echo 'rw_'.$_review->getId(); ?>">
                            <span class="drw-title"><?php echo $this->escapeHtml($_review->getTitle()); ?></span>
                            <span class="drw-nickname"><?php echo $this->escapeHtml($_review->getNickname()); ?></span>
                        </div>

                        <?php $this->getChild('helpful')->setReview($_review); ?>
                        <?php echo $this->getChildHtml('helpful', false); ?>

                        <div class="drw-review-dd">
                            <?php $this->getChild('socialShare')->setReview($_review); ?>
                            <?php echo $this->getChildHtml('socialShare', false); ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php
        $nextPage = $preparedReviews->getCurPage(+1);
        $nextPage = $preparedReviews->getCurPage() == $nextPage ? ++$nextPage : $nextPage;
        ?>
        <div id="drw-ajax-load-grid" class="drw-box drw-grid-item" data-next-page="<?php echo $nextPage; ?>" style="display:none;"></div>
        <div id="dialog" title="<?php echo $this->__('Vote Warning'); ?>"><p></p></div>
        <div class="drw-loader">
            <img src="<?php echo $this->getSkinUrl('images/detailedreview/ajax-loader.gif') ?>" />
        </div>
        <div class="drw-next-page" data-next-page="2"></div>
    </div>
<?php else: ?>
    <div class="drw-no-reviews"><?php echo $this->__('Sorry, you don\'t have any reviews or reviews with images'); ?></div>
<?php endif; ?>

<?php echo $this->getChildHtml('js', false); ?>
<?php echo $this->getChildHtml('emailShare', false); ?>
