<?php if(Mage::getStoreConfig(MageWorkshop_CommentOnReview_Helper_Data::COMMENT_XML_PATH_MODULE_ENABLE)): ?>
<?php
/** @var MageWorkshop_CommentOnReview_Helper_Data $commentOnReviewHelper */
$commentOnReviewHelper = Mage::helper('mageworkshop_commentonreview');

$nickname         = $commentOnReviewHelper->prepareNickname();
$expanderAmount   = Mage::getStoreConfig(MageWorkshop_CommentOnReview_Helper_Data::COMMENT_XML_PATH_EXPANDER);
$minSymbolsReply  = Mage::getStoreConfig(MageWorkshop_CommentOnReview_Helper_Data::COMMENT_XML_PATH_MIN_SYMBOLS);
$maxSymbolsReply  = Mage::getStoreConfig(MageWorkshop_CommentOnReview_Helper_Data::COMMENT_XML_PATH_MAX_SYMBOLS);
?>

<script type='text/javascript'>
    //<![CDATA[
    document.observe("dom:loaded", function() {
        (function($) {
            $(document).ready(function() {
                $().commentOnReview({
                    saveReplyUrl: "<?php echo Mage::getUrl('commentonreview/reply/save', array('_secure' => Mage::app()->getStore()->isCurrentlySecure())); ?>",
                    delayOfMessageDisplaying: 3000,
                    emptyDetailMessage: "<?php echo $this->__('Please enter text of the reply'); ?>",
                    isCaptchaEnabled: "<?php echo $commentOnReviewHelper->isCommentOnReviewReCaptchaEnabled(); ?>",
                    checkCaptchaUrl: "<?php echo Mage::getUrl('commentonreview/reply/checkCaptchaReply', array('_secure' => Mage::app()->getStore()->isCurrentlySecure())); ?>",
                    showElements: <?php echo $expanderAmount; ?>,
                    minDetailLength: "<?php echo $minSymbolsReply; ?>",
                    maxDetailLength: "<?php echo $maxSymbolsReply; ?>",
                    queryParams: {
                        nickname: "<?php echo $nickname; ?>"
                    },
                    detailErrorMessages: {
                        emptyDetail: "<?php echo $this->__('Please enter text of the reply'); ?>",
                        lengthDetail: "<?php echo $this->__('Reply must be min %s and max %s characters', $minSymbolsReply, $maxSymbolsReply); ?>"
                    },
                    nicknameSuffix: "<?php echo Mage::getStoreConfig(MageWorkshop_CommentOnReview_Helper_Data::COMMENT_XML_PATH_NICKNAME_SUFFIX); ?>",
                    defaultFailMessage: "<?php echo $this->__('Something went wrong.'); ?>"
                });

                $().CommentExpander({
                    showElements: <?php echo $expanderAmount; ?>
                });
            });
        })(DRjQuery);
    });
    //]]>
</script>
<?php endif; ?>