


<div class="my-account-section">
<div class="step-menu">
<ul>
<li class="checkout active"><span>My Orders</span>
<div class="icon"></div>
</li>
<li class="shipping"><span>Wish List</span>
<div class="icon"></div>
</li>
<li class="payment"><span>Your details</span>
<div class="icon"></div>
</li>
<li class="finish"><span>Sign out</span>
<div class="icon"></div>
</li>
</ul>
</div>
<div class="my-account-details">
	<div class="left">
		<div class="image">
			<img src="<?php echo $this->getSkinUrl('images/ring.png') ?>" alt="">
		</div>
		<div class="details">
			<h3>Round Diamond Ring</h3>
			<div class="order-status">
				<span>ORDER # 406-3821552-5994754</span>
				<span>Arriving in 4 days</span>
			</div>
			<div class="attr">Cut: <strong>Ideal</strong> | Carat: <strong>0.13</strong> | Color: <strong>F/G</strong> | Clarity: <strong>SI</strong></div>
			<div class="ring-size">Ring Size- <strong>6.0</strong></div>
			<div class="price-box">
				<span class="price">$479.00</span>				
			</div>
		</div>
	</div>
	<div class="right">
		<h4>Shipping Address</h4>
		<p>Arjun Panwar <br>DY Works, G 01, B/2 wing, <br>
Marathon Innova<br> Ganpatrao Kadam Marg, <br>Lower Parel West, <br>Mumbai 400013 <br>MUMBAI, MAHARASHTRA 
<br>400013, India</p>
	</div>
	<div class="buttons-set">
		<button class="button">Track order</button>		
	</div>
	<div class="cancel-link">
		<a href="#" class="cancel-item">Cancel items</a>
	</div>
</div>
</div> 