<div class="track-order-status">
	<ul class="status">
		<li class="active"><a href="javascript:void(0);"><label>Ordered 12 March</label></a></li>
		<li><a href="javascript:void(0);"><label>Expected to ship tomorrow</label></a></li>
		<li><a href="javascript:void(0);"><label>Out for delivery</label></a></li>
		<li><a href="javascript:void(0);"><label>Arriving tomorrow</label></a></li>
	</ul>
	<div class="tracking-id">
		<img src="<?php echo $this->getSkinUrl('images/fedex-img.png'); ?>" alt="">
		<span>Tracking ID 678468</span>
	</div>
</div>
 