<?php
$labelArr = array('weight'=>'Carat','stone_cut'=>'Cut','stone_quality'=>'Clarity','stone_color'=>'Color');

$resource = Mage::getSingleton('core/resource');
$readConnection = $resource->getConnection('core_read');
$did = $this->getDiamondid();
$side = $this->getSideid();
if($did > 0){
$diaData = $readConnection->fetchRow("select stone_cut,weight,stone_color,stone_quality from wizardmaster where pid=".$did); ?>
<p>
<span class="image">
    <img src="<?php echo $this->getSkinUrl('images/diamondiconsingle.png'); ?>" alt="">
</span>
<span class="four-content">
    <?php $singleDia = array();
    foreach ($diaData as $key=>$value):
        $singleDia[] = $labelArr[$key].': <strong>'.$value.'</strong>';
    endforeach;
    echo implode(" | ", $singleDia);
    ?>
</span>
</p>

<?php
}
if($side > 0){
$sideGroup = $readConnection->fetchCol("select pid from wizardmaster where group_code IN (select group_code from wizardmaster where pid=".$side.")");
$sidestoneArr = $readConnection->fetchRow("select GROUP_CONCAT(stone_cut) as stone_cut,GROUP_CONCAT(weight) as weight,GROUP_CONCAT(stone_color) as stone_color,GROUP_CONCAT(stone_quality) as stone_quality from wizardmaster where pid IN (".implode(',', $sideGroup).") LIMIT 2");
 ?>

<p>
<span class="image">
    <img src="<?php echo $this->getSkinUrl('images/diamondiconsingle.png'); ?>" alt="">
    <img src="<?php echo $this->getSkinUrl('images/diamondiconsingle.png'); ?>" alt="">
</span>
<span class="four-content">
    <?php $multiDia = array();
    foreach ($sidestoneArr as $key=>$value):
        $multiDia[] = $labelArr[$key].': <strong>'.$value.'</strong>';
    endforeach;
    echo implode(" | ", $multiDia);
    ?>
</span>
</p>

<?php  } ?>