  <?php
   $_helper = $this->helper('catalog/output');
   $_productCollection = Mage::getBlockSingleton('layernavigation/layernavigation')->getFilterProductCollection(null); 
?>
<?php //exit('stop'); ?>
<?php if($_productCollection): ?>
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <?php $_imgSize = 625; ?>
                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
            </a>
            <div class="product-shop">
                <div class="product-primary">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <?php
                    if ($this->getChild('name.after')) {
                        $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                        foreach ($_nameAfterChildren as $_nameAfterChildName) {
                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                            $_nameAfterChild->setProduct($_product);
                            echo $_nameAfterChild->toHtml();
                        }
                    }
                    ?>
                    <div class="desc">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>                        
                    </div>
                    <div class="preset-options">
                        <span class="label"><?php echo $this->__('Carat'); ?></span>
                        <div class="options">
                            <ul>
                                <li class="radio">
                                    <input type="radio" class="radio" id="1/3">
                                    <label class="name" for="1/3">1/3</label>
                                </li>
                                <li class="radio">
                                    <input type="radio" class="radio" id="1/3">
                                    <label class="name" for="1/3">1/2</label>
                                </li>
                                <li class="radio">
                                    <input type="radio" class="radio" id="1/3">
                                    <label class="name" for="1/3">3/4</label>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="preset-options metal-options">
                        <span class="label"><?php echo $this->__('Metal'); ?></span>
                        <div class="options">
                            <ul>
                                 <li><a href="#"><img src="<?php echo $this->getSkinUrl('images/metal-1.png'); ?>" alt=""></a></li>
                                 <li><a href="#"><img src="<?php echo $this->getSkinUrl('images/metal-2.png'); ?>" alt=""></a></li>
                                 <li><a href="#"><img src="<?php echo $this->getSkinUrl('images/metal-3.png'); ?>" alt=""></a></li>
                                 <li><a href="#"><img src="<?php echo $this->getSkinUrl('images/metal-4.png'); ?>" alt=""></a></li>
                                 <li><a href="#"><img src="<?php echo $this->getSkinUrl('images/metal-5.png'); ?>" alt=""></a></li>
                                 <li><a href="#"><img src="<?php echo $this->getSkinUrl('images/metal-6.png'); ?>" alt=""></a></li>
                                 <li class="active"><a href="#"><img src="<?php echo $this->getSkinUrl('images/metal-7.png'); ?>" alt=""></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="price-wrapper">
                        <span class="label"><?php echo $this->__('Total'); ?></span>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                    </div>
                    <div class="button-proceed">
                        <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                            <p class="action"><button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Proceed') ?></span></span></button></p>
                        <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                            <p class="action"><a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a></p>
                        <?php else: ?>
                            <p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>  
                    </div>
                </div>
                <ul class="add-to-links">
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <li>
                            <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"></a>
                        </li>
                    <?php endif; ?>
                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                        <li>
                            <a href="#" onclick="ajaxCompare('<?php echo $_compareUrl?>','<?php echo $_product->getId()?>'); return false;" class="link-compare"></a>
                        </li>
                    <?php endif; ?>
                </ul>                 
            </div>
        </li>
    <?php  endforeach; ?>
    <?php endif; ?> 


 