  <?php
   $_helper = $this->helper('catalog/output');
   $currentCategory = Mage::registry('current_category');
   $_productCollections = Mage::getBlockSingleton('layernavigation/layernavigation')->getLoadedProductCollection(null);
   $_productCollections = json_decode($_productCollections);
   $totalRecord = $_productCollections->totalRec;
   $totalRecord = explode("-",$totalRecord);
   $categoryId = $totalRecord[3];
   $_productCollection = $_productCollections->collection;
   //echo '<pre>';print_R($_productCollection);
   //echo '<pre>';print_R($totalRecord);
?>
<?php //exit('stop'); ?>
<p id="totalRecord" style="display: none"><?php echo $totalRecord[0];?></p>
<p id="max-price" style="display: none"><?php echo $totalRecord[1];?></p>
<p id="min-price" style="display: none"><?php echo $totalRecord[2];?></p>
<?php if(count($_productCollection) <= 0): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
    <?php foreach ($_productCollection as $product): ?>
        <?php $_product = Mage::getModel('catalog/product')->load($product->entity_id);?>
        <?php $pid = $_product->getId();?>
        <?php $productTotalDiaWt = $_product->getTotalDiaWt();?>
        <?php $productMetalKarat = $_product->getMetalColor()."-".$_product->getKarat();?>
        <?php $getCaratCollection = Mage::getBlockSingleton('layernavigation/layernavigation')->getCaratCollection($_product,$categoryId);?>
        <?php $totalDiaWt = $getCaratCollection["TotalDia"]; //print_R($totalDiaWt);?>
        <?php $metalColorKarat = $getCaratCollection["metal"];?>
        <?php //$diamondProductId = $getCaratCollection['Diamond-Product'];?>
        <?php $diamondProductId = $getCaratCollection['productId'];?>
        <?php $diamondPrice = $getCaratCollection['price'];?>
        <?php $diamondSpecialPrice = $getCaratCollection['special_price'];?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl()."?did=".$diamondProductId; ?>" id="image-<?php echo $pid;?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <?php $_imgSize = 270; ?>
                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
            </a>
            <div class="product-shop">
                <div class="product-primary">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl()."?did=".$diamondProductId; ?>" id="product-name-<?php echo $pid;?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getVariantRemark(), 'variant_remark'); ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <?php
                    if ($this->getChild('name.after')) {
                        $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                        foreach ($_nameAfterChildren as $_nameAfterChildName) {
                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                            $_nameAfterChild->setProduct($_product);
                            echo $_nameAfterChild->toHtml();
                        }
                    }
                    ?>
                    <div class="desc" id="desc-<?php echo $pid;?>">
                        <?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>
                    </div>
                    <?php // Get Catar Code : 20-03-2018 ?>
                    <?php //echo "total" . count($totalDiaWt);?>
                    <?php if(count($totalDiaWt) > 0):?>
                    <div class="preset-options">
                        <span class="label"><?php echo $this->__('Carat'); ?></span>
                        <div class="options">
                            <ul>
                                <?php foreach($totalDiaWt as $key=>$total):?>
                                <li class="radio">
                                    <input type="radio" name="carat<?php echo "-".$pid?>" value="<?php echo $key;?>" data-totalLabel="<?php echo $total[1];?>" class="radio changestylediamond" data-totalDiaWt="<?php echo $key;?>" data-productId="<?php echo $pid;?>" data-itemid=<?php echo $_product->getItemId();?> id="<?php echo $pid."-".$key;?>" <?php if($productTotalDiaWt == $total[1]):?>checked="checked"<?php endif;?>>
                                    <label class="name" for="<?php echo $pid."-".$key;?>"><?php echo $total[0];?></label>
                                </li>
                                <?php endforeach;?>
                            </ul>
                        </div>
                    </div>
                    <?php endif;?>
                    <?php
                        $catId = $categoryId;
                        $itemId = $_product->getItemId();
                       // $metalColorCollection = Mage::getBlockSingleton('layernavigation/layernavigation')->getMetalKarat($catId,$pid,$itemId,$productTotalDiaWt); ?>
                    <?php if(count($metalColorKarat) > 0):?>
                    <div class="preset-options metal-options">
                        <span class="label"><?php echo $this->__('Metal'); ?></span>
                        <div class="options">
                            <ul>
                                <?php /*echo '<pre>';print_R($metalColorKarat);*/ foreach($metalColorKarat as $metalKaratKey => $metal):?>
                                    <?php if($metal):?>
                                            <?php $ids = explode("-",$metalKaratKey); ?>
                                        <?php /*echo '<pre>';print_R($metal);*/ foreach($metal as $metalKarat):?>
                                            <li>
                                              <input type="radio" name="metalkarat<?php echo "-".$pid?>" data-metalid ="<?php echo $ids[0];?>" data-productId="<?php echo $pid;?>" data-itemid=<?php echo $_product->getItemId();?> class="changestyledia"  data-karatid="<?php echo $ids[1];?>" id="<?php echo $pid."-".$metalKaratKey;?>" <?php if($productMetalKarat == $metalKaratKey):?>checked="checked"<?php endif;?> >
                                              <label for="<?php echo $pid."-".$metalKaratKey;?>">
                                                    <?php $imageName = strtolower(str_replace(' ',"_",$metalKarat[0])."_".$metalKarat[1]).".png"; ?>
                                                    <?php $imagePath = Mage::getBaseUrl('media')."wizard". DS."category-listing" . DS .$imageName;?>
                                                    <img src="<?php echo $imagePath; ?>" alt="<?php echo $imageName;?>"/>
                                              </label>
                                            </li>
                                            <?php endforeach;?>
                                    <?php endif;?>
                                 <?php endforeach;?>
                            </ul>
                        </div>
                    </div>
                    <?php endif;?>
                    <span  style="display: none"; class="diamond-product-id" data-productId="<?php echo $pid;?>" id="<?php echo $diamondProductId; ?>">
                    <?php echo $diamondProductId; ?></span>
                    <div class="price-wrapper">
                        <span class="label"><?php echo $this->__('Total'); ?></span>
                        <?php //echo $this->getPriceHtml($_product, true) ?>
                        <?php if(!$_product->getSpecialPrice() || !$diamondSpecialPrice):?>
                                <?php $price = $_product->getPrice();?>
                                <?php $mainTotal = $price + $diamondPrice;?>
                            <div class="price-box">
                                <span class="regular-price" id="product-price-<?php echo $pid;?>">
                                    <span class="price"><?php echo Mage::helper('core')->currency($mainTotal, true, false);?></span>
                                </span>
                            </div>
                         <?php else:?>
                                <?php $price = $_product->getPrice();?>
                                <?php $specialPrice = $_product->getSpecialPrice();?>
                                <?php $mainTotal = $price + $diamondPrice;?>
                                <?php $specialotal = $specialPrice + $diamondSpecialPrice;?>
                             <div class="price-box">
                                <p class="old-price">
                                    <span class="price" id="old-price-<?php echo $pid;?>"><?php echo Mage::helper('core')->currency($mainTotal, true, false);?></span>
                                </p>
                                <p class="special-price">
                                    <span class="price" id="product-price-<?php echo $pid;?>"><?php echo Mage::helper('core')->currency($specialotal, true, false);?></span>
                                </p>
                            </div>
                        <?php endif;?>
                        <i id="spinner-<?php echo $pid;?>" class="fa fa-spinner fa-spin fa-fw" style="display: none;"></i>
                    </div>
                    <div class="button-proceed">
                        <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                            <?php /*<p class="action"><button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Proceed') ?></span></span></button></p>*/?>
                         <p class="action">
                            <a href="<?php echo $_product->getProductUrl()."?did=".$diamondProductId;?>" class="button btn-cart" id="proceed-<?php echo $pid;?>">
                                <span><span><?php echo $this->__('Proceed') ?></span></span>
                            </a>
                         </p>
                        <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                            <p class="action"><a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a></p>
                        <?php else: ?>
                            <p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                    </div>
                </div>
                <ul class="add-to-links">
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <li>
                            <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"></a>
                        </li>
                    <?php endif; ?>
                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                        <li>
                            <a href="#" onclick="ajaxCompare('<?php echo $_compareUrl?>','<?php echo $_product->getId()?>'); return false;" class="link-compare"></a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </li>
    <?php  endforeach; ?>
    <?php endif; ?>

