<?php
$data = $this->getData('data');
$product = $data['selectedvalue'];
?>
<?php foreach ($data['metal'] as $metalKaratKey => $metal) { ?>
    <li>
        <input type="radio" class="metal-color" name="metalkarat<?php echo "-".$product['pid']?>" data-id="<?php echo $metalKaratKey;?>" data-pid="<?php echo $metal['pid'];?>" data-item-id="<?php echo $product['item_id'];?>" id="<?php echo $metalKaratKey.'-'.$product['pid'];?>" <?php if($data['selected'] == $metalKaratKey):?>checked="checked"<?php endif;?> >
        <label for="<?php echo $metalKaratKey.'-'.$product['pid'];?>">
        <?php $imageName = strtolower(str_replace('-',"_",$metalKaratKey)).".png"; ?>
        <?php $imagePath = Mage::getBaseUrl('media')."wizard". DS."category-listing" . DS .$imageName;?>
        <img src="<?php echo $imagePath; ?>" alt="<?php echo $imageName;?>"/>
    </li>
<?php } ?>
