<?php $product = $this->getListPopupProduct(); ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<div class="popup-slider">
    <div class="popup-main-image">
        <?php foreach ($product->getMediaGalleryImages() as $img) :?>
                <div><img src="<?php echo Mage::helper('catalog/image')->init($product, 'image', $img->getFile())->backgroundColor(255,255,255)->resize(455,505)?>" alt="<?php echo $product->getName()?>" /></div>
        <?php endforeach; ?>
    </div>
    <div class="links">
        <a class="link wishlist-link" href="#"><span><?php echo $this->__('Wish It');?></span></a>
        <a class="link" href="javascript:void(0);">
            <div class="sharethis-inline-share-buttons"></div>
            <script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a423282c4203c00110b8eca&product=unknown" async="async"></script>
        </a>
    </div>
</div>            
<div class="popup-details">
    <h2 class="title"><?php echo $product->getName();?></h2>   
    <div class="price-box"><span class="price"><?php echo $this->getPriceHtml($product, true);?></span> </div>
    <div class="links"> 
        <a href="<?php echo $product->getProductUrl() ?>" class="link" title="<?php echo $this->stripTags($product->getName(), null, true) ?>"><?php echo $this->__('Proceed');?></a>
    </div>
    <div class="popup-thumb-image">
        <?php foreach ($product->getMediaGalleryImages() as $img) :?>
            <div><img src="<?php echo Mage::helper('catalog/image')->init($product, 'thumbnail', $img->getFile())->backgroundColor(255,255,255)->resize(100,100); ?>" alt="<?php $product->getName();?>" /></div>
        <?php endforeach; ?>
    </div>
</div> 
<button data-fancybox-close="" class="fancybox-close-small" title="Close"></button>
       
