<?php
/* @var $this Mage_Checkout_Block_Onepage_Progress */
?>
<div class="block block-progress opc-block-progress">

    <div class="block-content col2-set">
        <dl class="col-1 box">

            <dt class="complete box-title">
                <?php echo $this->__('Billing Address') ?> 
                <a href="#billing" onclick="checkout.gotoSection('billing'); return false;"><?php echo $this->__('Change') ?></a>
            </dt>
            <dd class="complete box-content">
                <address><?php echo $this->getBilling()->format('html') ?></address>
            </dd>
        </dl>
        <dl class="col-2 box">
            <dt class="complete box-title">
                <?php echo $this->__('Shipping Address') ?> 
                <a href="#payment" onclick="checkout.gotoSection('shipping');return false;"><?php echo $this->__('Change') ?></a>
            </dt>
            <dd class="complete box-content">
                <address><?php echo $this->getShipping()->format('html') ?></address>
            </dd>
        </dl>
        <dl class="col-1 box">
            <dt class="complete box-title">
                <?php echo $this->__('Shipping Method') ?> 
                <a href="#shipping_method" onclick="checkout.gotoSection('shipping_method'); return false;"><?php echo $this->__('Change') ?></a>
            </dt>
            <dd class="complete box-content">
                <?php if ($this->getShippingMethod()): ?>
                    <?php echo $this->escapeHtml($this->getShippingDescription()) ?>

                    <?php $_excl = $this->getShippingPriceExclTax(); ?>
                    <?php $_incl = $this->getShippingPriceInclTax(); ?>
                    <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                        <?php echo $_incl; ?>
                    <?php else: ?>
                        <?php echo $_excl; ?>
                    <?php endif; ?>
                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                    <?php endif; ?>

                <?php else: ?>
                    <?php echo $this->__('Shipping method has not been selected yet') ?>
                <?php endif; ?>
            </dd>
        </dl>
        <dl class="col-2 box">
            <dt class="complete box-title">
                <?php echo $this->__('Payment Method') ?> 
                <a href="#payment" onclick="checkout.gotoSection('payment'); return false;"><?php echo $this->__('Change') ?></a>
            </dt>
            <dd class="complete box-content">
                <?php echo $this->getPaymentHtml() ?>
            </dd>
        </dl>
    </div>
</div>
