<div class="related-post">
	<ul>
		<li class="item">
			<div class="image">
				<img src="<?php echo $this->getSkinUrl('images/blog/2.jpg'); ?>" alt="image1">
			</div>
			<div class="category-name">
				<?php echo $this->__('WEDDING IDEAS'); ?>					
			</div>
			<h3>
				<?php echo $this->__('Magen Markel’s wedding ring inspiration');?>
			</h3> 
		</li>
		<li class="item">
			<div class="image">
				<img src="<?php echo $this->getSkinUrl('images/blog/5.jpg'); ?>" alt="image1">
			</div>
			<div class="category-name">
				<?php echo $this->__('WEDDING IDEAS'); ?>					
			</div>
			<h3>
				<?php echo $this->__('Winter Proposals by Faaya customers');?>
			</h3> 
		</li>
		<li class="item">
			<div class="image">
				<img src="<?php echo $this->getSkinUrl('images/blog/3.jpg'); ?>" alt="image1">
			</div>
			<div class="category-name">
				<?php echo $this->__('PLANNING'); ?>					
			</div>
			<h3>
				<?php echo $this->__('Top 5 wedding rings trending this season');?>
			</h3> 
		</li>
	</ul>
</div>