<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_GiftCard
 */
?>
<?php /* @var $this Amasty_GiftCard_Block_Check */?>
<?php $card = $this->getCard() ?>
<?php if ($card->getId()): ?>
	<div class="am-gift-card-info">
		<p><?php echo $this->__("Status: %s", '<strong>' . $card->getStatus() . '</strong>'); ?></p>
		<p><?php echo $this->__('Current Balance: %s', '<strong>' . Mage::helper('core')->currency($card->getCurrentValue()) . '</strong>'); ?></p>
		<?php if ($card->getExpiredDate()): ?>
			<?php $_validTill = $this->formatDate($card->getExpiredDate(), 'short'); ?>
		<?php else: ?>
			<?php $_validTill = $this->__('unlimited'); ?>
		<?php endif; ?>
		<p><?php echo $this->__('Valid till: %s', '<strong>' . $_validTill . '</strong>'); ?></p>

	</div>
<?php else: ?>
	<ul class="messages"><li class="error-msg"><ul><li><span><?php echo $this->__('Wrong Gift Card Code.'); ?></span></li></ul></li></ul>
<?php endif; ?>
