
<a href='{{!it.baseUrl}}/{{!it.review.product.url_path}}#rw_{{=it.review.review_id}}' class='drw-title' target='_blank'>{{!it.review.title}}</a>

<span class='review-by-wrapper'> {{!it.review.reviewedBy}} {{!it.review.nickname}}</span>
{{?it.review.rating}}
    <div class='ratings-table'>
        <div class='rating-box'>
            <div class='rating' style='width:{{=it.review.rating}}%;'></div>
        </div>
    </div>
{{?}}
<div class='drw-item-info'>
    <div class='drw-review-dt' id='rw_{{=it.review.id}}'>
        <p class='drw-detail'>{{!it.review.detail}}</p>
    </div>
        <div class='clearboth'></div>
    <div class='social-helpful-wrapper'>
        <div class='drw-review-dd'>
            <div class='drw-social-share'>
                <div class='drw-share-fb'>
                    {{=it.review.fb}}
                </div>
                <div class='drw-share-twitter'>
                    {{=it.review.tw}}
                </div>
                {{? it.review.pt}}
                    <div class='drw-share-pinterest'>
                        {{=it.review.pt}}
                    </div>
                {{?}}
                {{? it.review.mailto}}
                    {{=it.review.mailto}}
                {{?}}
            </div>
        </div>
        {{=it.review.vote}}
    </div>
</div>
