<?php
/** @var MageWorkshop_DetailedReview_Block_Complaint $this */
$complaints = $this->getComplaint();
?>

<div class="complaint-list-wrapper complaint-hide">
    <div class="complaint-title"><?php echo $this->__('What kind of abuse are you reporting?')?></div>
    <form action="<?php echo Mage::getUrl('detailedreview/complaint/save', array('_secure' => Mage::app()->getStore()->isCurrentlySecure())); ?>" name="report" class="report-form">
        <ul class="complaint-list">
            <?php /** @var MageWorkshop_DetailedReview_Model_ReviewCustomerComplaint $complaint */ ?>
            <?php foreach($complaints as $complaint): ?>
                <?php $complaintId = $complaint->getEntityId(); ?>
                <li class="complaint control" data-id="<?php echo $complaintId; ?>">
                    <input id="complaint-value-<?php echo $complaintId;?>" class="complaint-value radio" name="complaint" value="<?php echo $complaintId; ?>" type="radio">
                    <label for="complaint-value-<?php echo $complaintId;?>">
                        <?php echo $this->__($complaint->getTitle()); ?>
                    </label>
                </li>
            <?php endforeach;?>
        </ul>
        <div class="complaint-action clearfix">
            <button class="complaint-submit-button submit-button" value="<?php echo $this->__('Continue')?>"><?php echo $this->__('Continue')?></button>
            <button class="complaint-cancel-button cancel-button" value="<?php echo $this->__('Cancel')?>"><?php echo $this->__('Cancel')?></button>
        </div>
    </form>
</div>