<?php $wordpressPageId = $this->getWordpressID();
$title = get_field('title' ,$wordpressPageId);
$description = get_field('descrption' ,$wordpressPageId);
$label = get_field('label' ,$wordpressPageId);
$link = get_field('link' ,$wordpressPageId);
$image = get_field('image' ,$wordpressPageId);
$newtab = '';
$catLink = "javascript:void(0);";
if($link){
    $newtab = 'target="_blank"';
    $catLink = check_custom_aboutlink2($link);
}
?>
<div class="whereweare-and-whowere-section">
    <div class="description">
        <h2><?php echo $this->__($title);?></h2>
        <?php echo $description;?>
         <a href="<?php echo $catLink;?>" <?php echo $newtab;?> class="readmore"><?php echo $label;?></a> </div>
         <div class="banner-img"> <img src="<?php echo $image['url']; ?>" alt="<?php echo $title;?>" /> </div>
     <?php if(have_rows('team_section',$wordpressPageId)):  ?> 
         <div class="whoweare-slider-outer">
            <div class="whoweare-slider">
                <div class="pinwheel_slider pinwheel_multi pinwheel_slider_set">
                    <div id="pinwheel_slider_1_prev" class="pinwheel_prev"></div>
                    <div id="pinwheel_slider_1_next" class="pinwheel_next"></div>
                    <div id="pinwheel_slider_1" class="pinwheel_slider_handle">
                     <?php  while(have_rows('team_section',$wordpressPageId)): the_row(); ?>
                                 <?php
                                  $memberName = get_sub_field('name',$wordpressPageId);
                                  $memberPosition = get_sub_field('position',$wordpressPageId);
                                  $memberDescription = get_sub_field('member_description',$wordpressPageId);
                                  $memberImage = get_sub_field('member_image',$wordpressPageId);
                                  $memberTag = get_sub_field('tag',$wordpressPageId); 
                                  $memberTagLink = get_sub_field('tag_link',$wordpressPageId); 
                                  $image = Mage::helper('latestblogpost')->getResizedHomeNewsImage($memberImage['url'], 270, 270,"aboutus-member");?>
                                     <div class="pinwheel_slideri carousel-feature" data-focus-x="" data-focus-y="">
                                        <div class="image">
                                            <img src="<?php echo $image; ?>" alt="<?php echo $memberName;?>">
                                        </div>
                                        <div class="info">
                                            <h4><?php echo $memberName;?></h4>
                                            <h5><?php echo $memberPosition;?></h5>
                                            <p>
                                                <?php echo $memberDescription; ?>
                                                <a target="_blank" href="<?php echo $memberTagLink ?>">
                                                    <?php echo $memberTag;?>
                                                </a>
                                            </p>
                                        </div>
                                    </div>
                         <?php endwhile; ?>
                    </div>

                </div>
            </div>
        </div>
     <?php endif;  ?> 
</div> 
<script type="text/javascript">
    jQuery(document).ready(function() {

        /* setTimeout(function() {

             jQuery('.whoweare-slider-outer .slick-slide').removeClass('slick-active2');
             jQuery('.whoweare-slider-outer .slick-current').prev('.slick-slide').addClass('slick-active2');
             jQuery('.whoweare-slider-outer .slick-current').next('.slick-slide').addClass('slick-active2');

         }, 2000);




         jQuery('.whoweare-slider').slick({
             centerMode: true,
             slidesToShow: 5,
             centerPadding: '0',
             //infinite: false,

             responsive: [{
                     breakpoint: 768,
                     settings: {
                         centerMode: true,
                         centerPadding: '40px',
                         slidesToShow: 3
                     }
                 },
                 {
                     breakpoint: 480,
                     settings: {
                         centerMode: true,
                         centerPadding: '20px',
                         slidesToShow: 1
                     }
                 }
             ]
         });

         jQuery('.whoweare-slider').on('afterChange', function(event, slick, currentSlide, nextSlide) {
             jQuery('.whoweare-slider-outer .slick-slide').removeClass('slick-active2');
             jQuery('.whoweare-slider-outer .slick-current').prev('.slick-slide').addClass('slick-active2');
             jQuery('.whoweare-slider-outer .slick-current').next('.slick-slide').addClass('slick-active2');
         });*/



        args = {
            flankingItems:2,
            autoPlay: 0,
            trackerIndividual: false,
            trackerSummation: false,
            speed: 600,
            //animationEasing: "swing",
            separation:175,
            forcedImageWidth:270,
            forcedImageHeight:480,
            //horizon: 255,
            sizeMultiplier: 0.75,
            sliderMaxWidth: 860,
            sliderMaxHeight:520,
            minimize: true,
            //prettyphoto: false,
            slider_handle: "pinwheel_slider_1",
            timthumb: 1
        };
        var pinwheel_slider_1_c = jQuery("#pinwheel_slider_1").pinwheelAlt(args);
        jQuery(window).on("debouncedresize", function() {
            pinwheel_slider_1_c.reload(args);
        });
        jQuery("#pinwheel_slider_1_prev").bind("click", function() {
            pinwheel_slider_1_c.prev();
            return false;
        });
        jQuery("#pinwheel_slider_1_next").bind("click", function() {
            pinwheel_slider_1_c.next();
            return false;
        });
        jQuery("#pinwheel_slider_1").touchwipe({
            wipeLeft: function() {
                pinwheel_slider_1_c.next();
            },
            wipeRight: function() {
                pinwheel_slider_1_c.prev();
            },
            preventDefaultEvents: false
        });

    });

</script>
<?php
    function check_custom_aboutlink2($arglink)
    {
        $httpPost = strpos($arglink,'http');
        if(strlen($arglink)==0)
        {
            $link = 'javascript:;';
        }
        elseif(strlen($httpPost)==0)
        {
           $link = 'http://'.$arglink;
        }
        else
        {
           $link = $arglink;
        }
        return $link;
    }
?>
