<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $posts = $this->getLatestBlogPostCollection(); ?>
<?php if (count($posts) > 0): ?>
	<div class="section-title">
		<h2><?php echo $this->__('Today’s <strong>Top Stories</strong>'); ?></h2>
	</div>
	<div class="post-list latestpost">
		<ul id="post-list">
			<?php foreach($posts as $post): ?>
				<li class="item<?php if ($post->isSticky()): ?> featured is-sticky<?php endif; ?> <?php echo $post->getPostFormat() ?>">
					<?php //echo $this->getPostRenderer($post)->toHtml() ?>
					<div class="post-list-item">
						<div class="post-entry entry post-entry-with-image">
						  <div class="featured-image left">
						  <?php $bannerImag = get_field('post_large_image',$post->getID());
							if(!empty($bannerImag)){
								$imgSrc = $bannerImag['sizes']['large'];
							}else{

								$imgSrc = '';
							}?>
							<a href="<?php echo  $post->getPermalink() ; ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><img src="<?php echo $imgSrc; ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"></a>
						  </div>
						  <div class="category-name">
							<?php
								$cate = wp_get_post_categories($post->getId());
								if(!empty($cate)){
									$catArg =  get_term_by('id', $cate[0], 'category');
									echo $catArg->name;
								}
							?>	
						  </div>
						  <h2 style="height: 112px;"><a href="<?php echo $post->getPermalink() ; ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><?php echo $this->escapeHtml($post->getPostTitle()) ?></a></h2>
						  <div class="post-date">
							<div class="date"><?php echo $post->getPostDate();?></div>
						  </div>
						  <div class="author-name">
						 
							By <span><?php echo $post->getAuthor()->getDisplayName(); ?></span>
						  </div>
						  <div class="sharethis">
										<div class="sharethis-inline-share-buttons"></div>
										<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5aa7706835937200136183e9&product=inline-share-buttons"></script>
									</div>
						  <div class="descriptipn">
							<?php echo $post->post_excerpt; ?>			
						  </div>
						  <a class="readmore" href="<?php echo  $post->getPermalink() ; ?>">Explore More</a>
						</div>
					  </div>
				</li>
			<?php endforeach; ?>
		</ul>
		<script type="text/javascript">decorateList($('post-list'));</script>
		<?php echo $this->getPagerHtml() ?>
	</div>
<?php endif; ?>
