<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php echo $this->getLayout()->createBlock('latestblogpost/latestblogpost')->setTemplate('wordpress/post/top-featured.phtml')->toHtml(); ?>  
<?php echo $this->getLayout()->createBlock('latestblogpost/latestblogpost')->setTemplate('wordpress/post/latestpost.phtml')->toHtml(); ?>
<?php echo $this->getLayout()->createBlock('latestblogpost/latestblogpost')->setTemplate('wordpress/post/bottom-featured.phtml')->toHtml(); ?>  
<?php echo $this->getLayout()->createBlock('latestblogpost/latestblogpost')->setTemplate('wordpress/post/all-time-favourite.phtml')->toHtml(); ?>
<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('newsletter/blog-subscribe.phtml')->toHtml(); ?>     
<?php //$posts = $this->getLatestBlogPostCollection() ?>  
<?php /*$posts = $this->getPosts(); echo '<prE>';print_r($posts->getData());?>
<?php if (count($posts) > 0): ?>
	<div class="post-list">
		<ul id="post-list">
			<?php foreach($posts as $post): ?>
				<li class="item<?php if ($post->isSticky()): ?> featured is-sticky<?php endif; ?> <?php echo $post->getPostFormat() ?>">
					<?php echo $this->getPostRenderer($post)->toHtml() ?>
				</li>
			<?php endforeach; ?>
		</ul>
		<script type="text/javascript">decorateList($('post-list'));</script>
		<?php echo $this->getPagerHtml() ?>
	</div>
<?php endif;*/ ?>
