<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $posts = $this->getLatestTopPostCollection() ?>
<?php if (count($posts) > 0): ?>
	<div class="post-list top">
		<div id="post-list">
			<?php foreach($posts as $post): ?>
				<div class="item<?php if ($post->isSticky()): ?> featured is-sticky<?php endif; ?> <?php echo $post->getPostFormat() ?>">
					<?php //echo $this->getPostRenderer($post)->toHtml() ?>
					<div class="post-list-item row">
						<?php echo $this->getBeforePostContentHtml() ?>
						<?php
							$bannerImag = get_field('post_large_image',$post->getID());
							if(!empty($bannerImag)){
								$imgSrc = $bannerImag['sizes']['large'];
							}else{

								$imgSrc = '';
							}

						?>

						<div class="col-sm-7 col-md-9 pull-right">
							<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>">
								<img class="top-img" src="<?php echo $imgSrc; ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/>
							</a>
						</div>
						<div class="col-sm-5 col-md-3 post-entry entry<?php if ($post->getFeaturedImage()): ?><?php endif; ?>">
							<h2>
								<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>">
									<?php echo $this->escapeHtml($post->getPostTitle()) ?>
								</a>
							</h2>
							<div class="category-name">
								<?php
									$cate = wp_get_post_categories($post->getId());
									if(!empty($cate)){
										$catArg =  get_term_by('id', $cate[0], 'category');
										echo $catArg->name;
									}
								?>
							</div>
							<?php if ($post->isViewableForVisitor()): ?>
								<?php if ($featuredImage = $post->getFeaturedImage()): ?>

								<?php endif; ?>
								<?php if ($this->displayExcerptInFeed() || $post->hasMoreTag()): ?>
									<?php
										/**
										* You can pass the number of words you want the excerpt to be shortened to like so
										* The below code will only show the first 50 words of the excerpt
										* <?php echo $post->getPostExcerpt(50) ?>
										*
										**/
									?>
									<?php echo $post->getPostExcerpt(50) ?>
								<?php else: ?>

									<div class="post-date">
										<div class="date"><?php echo $post->getPostDate() ?></div>
									</div>
									<div class="author-name">
										 By <span><?php echo $post->getAuthor()->getDisplayName() ?></span>
									</div>
									<div class="sharethis">
										<div class="sharethis-inline-share-buttons"></div>
										<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5aa7706835937200136183e9&product=inline-share-buttons"></script>
									</div>
									<div class="descriptipn">
										<?php //echo $post->getPostContent() ?>
										<?php //echo substr(strip_tags($post->post_content), 0, 142);?>
										<?php echo strip_tags($post->post_excerpt);?>
									</div>
									<a class="readmore" href="<?php echo $post->getPermalink() ?>">Explore More</a>
								<?php endif; ?>
							<?php else: ?>

								<?php echo $this->getPasswordProtectHtml($post) ?>
							<?php endif; ?>
						</div>

						<?php echo $this->getAfterPostContentHtml() ?>
					</div>
				</div>
			<?php endforeach; ?>
		</div>
		<script type="text/javascript">decorateList($('post-list'));</script>
		<?php echo $this->getPagerHtml() ?>
	</div>
<?php endif; ?>