<div class="shipping-offer" data-class="shipping-offer-2">
    <div class="shipping-inner">
        <div class="shipping-wrapper">
            <div class="shop">
               <a href="<?php echo Mage::getUrl('multiwishlist') ?>">
                <div class="item wishlist">
                    <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?> <span>
                      <?php
                            $customer = Mage::getSingleton('customer/session')->getCustomer();
                            $wishlist = Mage::getModel('wishlist/wishlist')->loadByCustomer($customer, true);
                            echo $wishlist->getItemsCount();
                        ?>
                      </span>
                    <?php endif; ?>
                </div>
              </a>
                <a href="<?php echo $this->getUrl('checkout/cart'); ?>">
                    <div class="item cart">
                        <?php
                                  //$count = $this->helper('checkout/cart')->getSummaryCount();  //get total items in cart
                                  $count = Mage::Helper('wizard')->getCartTotalItem();  //get total items in cart
                                  $total = $this->helper('checkout/cart')->getQuote()->getGrandTotal(); //get total price
                                  if($count==0) 
                                  {
                                    echo $this->__('<span> 0</span>',$count);
                                  }
                                  if($count==1)
                                  {
                                    echo $this->__('<span> 1 </span>',$count);
                                  }
                                  if($count>1)
                                  {
                                    echo $this->__('<span> %s </span>',$count);
                                  }
                                  echo $this->__('', $this->helper('core')->formatPrice($total, false));
                        ?>
					</div>
                </a>
            </div>
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('shipping-offer')->toHtml(); ?>
        </div>
    </div>
</div>
