<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_GiftCard
 */
?>
<script type="text/javascript">
    //<![CDATA[
    function removeGiftCard(code) {
        var data = {};
        data['amgiftcard_remove'] = code;
        order.loadArea(['totals', 'billing_method', 'items'], true, data);
    }

    function applyGiftCard() {
        var data = {};
        data['amgiftcard_add'] = $('am_giftcard_code').value;
        order.loadArea(['totals', 'billing_method', 'items'], true, data);
    }
    //]]>
</script>