<?php
/**
 * MageWorkshop
 * Copyright (C) 2016 MageWorkshop <info@mage-review.com>
 *
 * @category   MageWorkshop
 * @package    MageWorkshop_DetailedReview
 * @copyright  Copyright (c) 2016 MageWorkshop Co. (https://mage-review.com/)
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU General Public License, version 3 (GPL-3.0)
 * @author     MageWorkshop <info@mage-review.com>
 */

/** @var MageWorkshop_DetailedReview_Block_Rating_Entity_Detailed $this */
$currentUrl = preg_replace('/\?.*/', '', $this->helper('core/url')->getCurrentUrl());
$helperDetailedreview = $this->helper('detailedreview');
$isCustomerLogged = $this->helper('customer')->isLoggedIn();
$isGuestAllowToWrite = $this->helper('review')->getIsGuestAllowToWrite();
$arrayQtyMarks = $this->getQtyMarks();
$countReviewsWithRating = array_sum($arrayQtyMarks);
$ratingsEnabled = Mage::helper('detailedreview')->checkEnabledRatings();
$showRating = Mage::helper('detailedreview')->checkFieldAvailable('review_graph', 'info');
$isShowFilters = Mage::getStoreConfig('detailedreview/show_review_info_settings/allow_result_filters');
?>
<div class="review-top" <?php if (!$isShowFilters) : ?> style="border-bottom: 1px solid #CCCCCC;" <?php endif; ?>>
<div class="review-top-wrapper">
    
        <?php if ($this->_avgRating && $ratingsEnabled): ?>
            <div class="average-rating">
                <?php /* ?><div class="average-caption"><span class="average-rating-text"><?php echo $this->__('Overall Average Rating:') ?></span></div><?php */ ?>
                <div class="rating-stars-views ratings">
                    <div class="rating-box">
                        <div class="rating" style="width:<?php echo $this->_avgRating; ?>%;"></div>
                    </div>
                </div>
                <div class="average-based-on">
                        <?php if ($countReviewsWithRating == 1): ?>
                            <?php echo $this->__(' %s total ratings', $countReviewsWithRating); ?>
                        <?php else: ?>
                            <?php echo $this->__(' %s total ratings', $countReviewsWithRating); ?>
                        <?php endif; ?>
                </div>
            </div>
           
        <?php endif; ?>
        
    
    <div class="ratings-and-size">
        <?php if ($showRating && $this->_avgRating && $ratingsEnabled): ?>
            <div class="review-right">
                <div class="separate-rating">
                    <?php for ($key=0;$key<5;$key++){ ?>
                        <div class="mark-rating">
                            <div class="rating-box">
                                <div class="rating"><span><?php echo (5-$key); ?><?php echo $this->__(' star'); ?></span></div>
                            </div>
                            <div class="scroll-box">
                                <div class="scroll-rating" style="width:<?php echo ( isset($arrayQtyMarks[5-$key]) && $this->_reviewCount != 0 ) ? ceil(100*$arrayQtyMarks[5-$key]/$this->_reviewCount) : 0 ?>%;"></div>
                            </div>
                            <div class="rating-percent">
                                <span><?php echo ( isset ($arrayQtyMarks[5-$key]) && $this->_reviewCount != 0 ) ? $arrayQtyMarks[5-$key] : '0'; ?></span>
                            </div>
                        </div>
                    <?php } ?>
                    <div class="clearboth"></div>
                </div>
            </div>
            </div>
        <?php endif; ?>
        
        <?php if ( $helperDetailedreview->checkFieldAvailable('sizing', 'form') && $sizing = $this->getAverageSizing()):?>
            <div class="average-sizing-box">
                <div class="average-caption"><span><?php echo $this->__('Size') ?></span></div>
                <?php $reviewSizing = Mage::getSingleton('detailedreview/review_sizing'); ?>
                <div class="sizing-bar average">
                    <div style="width:<?php echo $reviewSizing->getOptionWidth($sizing) ?>%;"></div>
                    <p class="sizing-pointer" style="margin-left: <?php echo($reviewSizing->getOptionWidth($sizing) . '%'); ?>"></p>
                    <p class="sizing-label" style="margin-left: <?php echo($reviewSizing->getOptionWidth($sizing) . '%'); ?>;right: <?php echo $reviewSizing->getIndent($sizing); ?>">
                          <?php echo $reviewSizing->getOptionValue($sizing); ?>
                    </p>
                </div>
            </div>
        <?php endif;?>
    </div>
            <?php if ($isShowFilters) : ?>
                 <?php /* ?><div class="filters">
                    <h4><?php echo $this->__('Result filter:') ?></h4>
                   <ul class="review-date-filters" id="dateFilter" onchange="setLocation(this.value)">
                        <li class="top-dropdown"><a href="javascript:void(0)" rel="nofollow" class="dateFilter"><span class="top-title"><?php echo $this->__('All Reviews')?></span></a></li>
                        <?php foreach ($this->getAvailableDateRanges() as $k => $v): ?>
                            <?php $sumByRange = $this->getQtyByRange($k); ?>
                            <?php if(($k == 1) && (!Mage::getSingleton( 'customer/session' )->isLoggedIn())) continue; ?>
                            <li <?php if ($helperDetailedreview->isInGetParams('st', $k)):?> class="active"<?php endif; ?>>
                                <a data-type="range-filter" data-value="<?php echo $k; ?>" href="#" rel="nofollow">
                                    <span class="range-filter-title"><?php echo $v .'<span class="range-filter-value"> (' . $sumByRange . ')</span>';?></span>
                                </a>
                            </li>
                        <?php endforeach;?>
                    </ul>
                </div><div class="form-filters-wrapper">
                <ul class="attr-rating">
                    <?php $reviewFilter = 1; ?>
                    <?php foreach ( $this->getAvailableFilterAttributes() as $k => $v ):?>
                        <?php if ($helperDetailedreview->checkAvailableFilter($k)):?>
                            <li>
                                <input id="reviewfilter-<?php echo $reviewFilter ?>" type="checkbox" data-type="review-filter" data-filter="<?php echo $k; ?>" <?php if ($helperDetailedreview->isInGetParams($k,'true')):?>checked="checked"<?php endif;?> value="<?php echo $k; ?>"/>
                                <span></span>
                                <label for="reviewfilter-<?php echo $reviewFilter ?>"><?php echo $this->__($v);?></label>
                            </li>
                        <?php endif; ?>
                        <?php $reviewFilter++; ?>
                    <?php endforeach;?>
                </ul>
                <form method="get" action="<?php echo $this->escapeHtml( $currentUrl ); ?>" id="review_search_mini_form" data-type="search">
                    <div class="form-search">
                        <input type="hidden" value="1" name="feedback"/>
                        <?php if ($request = $this->getRequest()) : ?>
                            <?php foreach ($request->getParams()  as $key => $value): ?>
                                <?php if ($key == 'feedback' || $key == 'keywords' || '__status__') continue; ?>
                                <?php if (is_array($value)) $value = serialize($value); ?>
                                <input type="hidden" value="<?php echo $this->escapeHtml($value) ?>" name="<?php echo $this->escapeHtml($key) ?>"/>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        <?php $keywords = isset($request) ? $request->getParam('keywords') : ''; ?>
                        <input type="text" class="input-text ac-off" value="<?php echo $this->escapeHtml($keywords) ?>" name="keywords" placeholder="<?php echo $this->__('search in reviews') ?>" id="review-search"/>
                        <button type="submit" class="search-review-button"><span><span><?php echo $this->__('Go') ?></span></span></button>
                    </div>
                </form>
            </div><?php */ ?>
            <?php endif; ?>
            <div class="review-sorts">
                <?php /* <span>Showing <?php echo $this->_reviewCount;?> of <?php echo $tempSum;?> reviews <a href="<?php echo $currentUrl?>?feedback=1#feedback" >Clear Filters</a></span> */ ?>
                <label><?php echo $this->__('Sort by:'); ?></label>
                <?php $selectedOrder = $this->getCurrentSorting();
                $availableSorts = $this->getAvailableSorts($ratingsEnabled); ?>
                <ul class="select-review-sorts" onchange="setLocation(this.value)">
                    <?php if (count($availableSorts) == 1): ?>
                        <li class="single-top-sorts option"><span class="top-title"><?php echo $this->__('Sort By: %s', array_shift($availableSorts)); ?></span></li>
                    <?php else: ?>
                        <li class="option"><a href="javascript:void(0)" rel="nofollow" class="sortsLink"><span class="top-title"><?php echo $this->__('Date - Newest First')?></span></a></li>
                        <?php foreach ($availableSorts as $sort => $label): ?>
                            <li class="option" <?php if ($selectedOrder == $sort): ?> class="selected option"<?php endif; ?> data-type="sort" data-sort="<?php echo $sort; ?>"><?php echo $this->__($label) ?></li>
                        <?php endforeach;?>
                    <?php endif; ?>
                </ul>
            </div>
        <div class="button-write-review">
            <?php if ( !$helperDetailedreview->isUserAbleToWriteReview() ): ?>
                <span class="error"><?php echo $this->__('You are not Allowed to Write a Review.'); ?></span>
            <?php else: ?>
                <?php $redirectUrl = $currentUrl  . $helperDetailedreview->getCurrentUrlWithNewParam('show_popup','1'); ?>
                <input type="hidden" value="<?php echo $this->escapeHtml($redirectUrl); ?>" />
                <input type="hidden" value="<?php echo $this->helper('core/url')->getEncodedUrl($redirectUrl);?>" />
                <?php if(Mage::helper('detailedreview/config')->isSeparateForm()): ?>
                    <a type="button" class="review-dialog" href="<?php echo Mage::getUrl("detailedreview/index/submitpage/", array('product' => Mage::registry('current_product')->getId(), '_secure' => true))?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/write-review-icon.png'); ?>" alt="" /> <?php echo $this->__('Write a Review') ?></a>
                <?php else: ?>
                    <a type="button" class="review-dialog" href="#review-dialog-block" ><img src="<?php echo $this->getSkinUrl('images/write-review-icon.png'); ?>" alt="" /> <?php echo $this->__('Write a Review') ?></a>
                <?php endif; ?>
            <?php endif; ?>
      </div>  </div>
</div>
<div id="star-five"></div>

<script type="text/javascript">
    jQuery(document).ready(function () {
       
         jQuery('.review-sorts .select-review-sorts li.option').click(function() {
            jQuery(this).siblings().addBack().children().remove();
            var a = jQuery(this).siblings().toggle();
            jQuery(this).parent().prepend(this);
          })
        
    });
</script>