<?php
/**
 * MageWorkshop
 * Copyright (C) 2016 MageWorkshop <info@mage-review.com>
 *
 * @category   MageWorkshop
 * @package    MageWorkshop_DetailedReview
 * @copyright  Copyright (c) 2016 MageWorkshop Co. (https://mage-review.com/)
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU General Public License, version 3 (GPL-3.0)
 * @author     MageWorkshop <info@mage-review.com>
 */

if(!MageWorkshop_DetailedReview_Helper_Config::isDRjQuery()) : ?>
    <script type="text/javascript">
        if (typeof jQuery === 'undefined') {
            console.log("<?php echo $this->__("jQuery is not installed. Please enable jQuery in Detailed Review plugin settings."); ?>");
        } else {
            //adds 0 as first digit if necessary to the version
            if (jQuery.fn.jquery.split('.').map(function (i) {
                    return ('0' + i).slice(-2)
                }).join('.') < '01.08.03') {
                console.log("<?php echo $this->__("Version of included jQuery by some other plugin is lower then 1.8.3. Please enable jQuery in Detailed Review plugin settings."); ?>");
            }
        }
    </script>
<?php endif; ?>