<?php $wordpressPageId = $this->getWordpressID();
$title = get_field('diamonds_grown_title' ,$wordpressPageId);
$description = get_field('diamonds_grown_description' ,$wordpressPageId);
?>
<div class="diamond-grown-catagory">
    <div class="description">
        <h2><?php echo $title;?></h2>
        <p><?php echo $description;?></p>
    </div>
    <?php if(have_rows('diamonds_grown_reapeter',$wordpressPageId)):  ?>  
    <div class="category-grid owl-carousel">        
           <?php  while(have_rows('diamonds_grown_reapeter',$wordpressPageId)): the_row(); ?> 
                     <?php
                        $diamondTitle = get_sub_field('diamond_title',$wordpressPageId);
                        $diamondDescription = get_sub_field('diamond_description',$wordpressPageId);
                        $diamondImage = get_sub_field('diamond_image',$wordpressPageId);?>
                        <div class="item">
                            <div class="info">
                                <h3><?php echo $diamondTitle;?></h3>
                                <?php $diamondDescription = strip_tags(preg_replace("/<img[^>]+\>/i", "", $diamondDescription));?>
                                <p><?php echo Mage::helper('core/string')->truncate($diamondDescription, '130');?></p>
                                <div class="image">
                                    <img src="<?php echo $diamondImage['url']; ?>" alt="">
                                </div>
                            </div>
                        </div>
             <?php endwhile; ?>
             </div> 
    <?php endif; ?>             
    </div>


    <script type="text/javascript">
        jQuery(document).ready(function () {
           jQuery('.category-grid').owlCarousel({
                    loop:false,
                    items:1,
                    margin:20,
                    mouseDrag:false,
                    nav:(jQuery(".category-grid .item").length > 4) ? true : false,
                    dots:true,            
                    responsive:{
                        0:{
                            items:1,
                            nav:(jQuery(".category-grid .item").length > 1) ? true : false,
                            margin:0,
                            autoHeight: true
                        },
                        600:{
                            items:2,
                            nav:(jQuery(".category-grid .item").length > 2) ? true : false,
                            margin:10,
                        },
                        768:{
                            items:3,
                            nav:(jQuery(".category-grid .item").length > 3) ? true : false,
                            margin:10,
                        },
                        1000:{
                            items:4,
                            nav:(jQuery(".category-grid .item").length > 4) ? true : false,
                        }
                    }
                })       

        })
    </script>