<?php if(have_rows('proposal_with_faaya_repeater','option')):  ?> 
<?php 
$title =  get_field('proposal_propose_with_faaya_title','option');
$description =  get_field('proposal_propose_with_faaya_short_description','option');
?>
<section class="propose-category-section">   
        <div class="description">
            <h2><?php echo $title;?></h2>
            <p><?php echo $description;?></p>
        </div>
        <div class="content">
            <ul class="grid">
                <?php  while(have_rows('proposal_with_faaya_repeater','option')): the_row(); ?>
                 <?php
                      $partnerStep = get_sub_field('proposal_step','option');
                      $proposeTitle = get_sub_field('proposal_title','option');
                      $proposeDescription = get_sub_field('proposal_description','option');  
                      $proposeLable = get_sub_field('proposal_label','option');
                      $proposeLink = get_sub_field('proposal_link','option');
                      $proposeImage = get_sub_field('proposal_image','option');
                      $proposeClass = get_sub_field('proposal_class','option');
                      /*$image = Mage::helper('latestblogpost')->getResizedHomeNewsImage($proposeImage['url'], 428, 387,"proposal-propose");*/
                      $image = $proposeImage['url'];
                      $cLink = "javascript:void(0);";?>
                      <?php
                        if($proposeLink):
                           $cLink = check_custom_proposelink($proposeLink);
                        endif;
                 ?>
                <li class="item <?php echo $proposeClass;?>">
                    <div class="details">
                        <span class="number visible-in-device"><?php echo $partnerStep;?></span>
                        <h3><?php echo $proposeTitle;?></h3>
                        <p><?php echo $proposeDescription;?></p>
                        <?php if($proposeClass): ?>
                          <a class="readmore" href="javascript:void(0)" title="<?php echo $proposeLable;?>"><?php echo $proposeLable;?></a>
                        <?php else: ?>
                            <a class="readmore" href="<?php echo $cLink;?>" title="<?php echo $proposeLable;?>"><?php echo $proposeLable;?></a>
                        <?php endif; ?>
                    </div>
                    <div class="image"><img src="<?php echo $image ?>" alt="<?php echo $proposeLable;?>" /></div>
                </li>
               <?php endwhile; ?>                 
            </ul>
        </div>

    <!-- Popup -->
    <div class="personalised-popup">
        <a href="javascript:void(0);" class="close-popup global-close-icon"></a>
        <h2>Which <strong>Faaya Diamond</strong> do you own?</h2>
        <form method="post" id="personalised-id" name="personalised-id">
            <div class="fieldset">
                <ul class="form-list">
                    <li class="fields">
                        <div class="input-box">
                           <label for="uid">Diamond certificate</label>
                            <input name="uid" placeholder="LD000" title="" value="" class="input-text required-entry" type="text" />
                        </div>
                    </li>
                    <li class="fields">
                        <div class="input-box">
                           <label for="emailid">Email ID</label>
                            <input name="emailid" placeholder="Enter Email Address" title="" value="" class="input-text required-entry validate-email" type="email" />
                        </div>
                    </li>
                    <li class="fields">
                        <div class="input-box">
                           <label for="contactno">Contact No.</label>
                            <input name="contactno" placeholder="00000000" title="" value="" class="input-text required-entry validate-number" type="text" />
                        </div>
                    </li>
                </ul>
            </div>
            <div class="buttons-set">
                <input type="text" name="hideit" id="hideit" value="1" style="display:none !important;" />
                <button type="button" title="" class="btn btn-link assist-btn"><span><span>Let Faaya Assist</span></span></button>
            </div>
        </form>
    </div>
</section>
<?php endif;?>
<?php
    function check_custom_proposelink($arglink)
    {
        $httpPost = strpos($arglink,'http');
        if(strlen($arglink)==0)
        {
            $link = 'javascript:;';
        }
        elseif(strlen($httpPost)==0)
        {
           $link = 'http://'.$arglink;
        }
        else
        {
           $link = $arglink;
        }
        return $link;
    }
?>

<script type="text/javascript">
    var personalisedform = new VarienForm('personalised-id', true);
    jQuery(document).ready(function () {

      jQuery('.personalize-popup-link').on('click',function (e) {
         e.stopPropagation();
        jQuery('.personalised-popup').parent().addClass('personalised-popup-open');
      });
      jQuery('.close-popup').on('click',function () {
        jQuery('.personalised-popup').parent().removeClass('personalised-popup-open');
      });
      jQuery('.personalised-popup').on('click',function (e) {
        e.stopPropagation();
      });

      jQuery(document).click(function(event){
        jQuery('.personalised-popup').parent().removeClass('personalised-popup-open');
     });
      jQuery('.assist-btn').click(function(){
            var uid = jQuery('input[name="uid"]').val();
            var emailid = jQuery('input[name="emailid"]').val();
            var contactno = jQuery('input[name="contactno"]').val();
            if (personalisedform.validator.validate()) {
                jQuery.ajax({
                  url: "<?php echo Mage::getUrl('assist'); ?>",
                  type: "POST",
                  data:{uid:uid,emailid:emailid,contactno:contactno},
                  success: function(data){
                    var response = JSON.parse(data);
                    jQuery('.personalised-popup').find('.buttons-set').html(response);
                    setTimeout(function(){
                        location.reload(true);
                    },100)
                  }
                });
            }
      })

    });


</script>
