<?php
$product = $this->getProduct();
$price = ($product->getSpecialPrice() && $product->getSpecialPrice() < $product->getPrice())?$product->getSpecialPrice():$product->getPrice();
$product->load('media_gallery');
$gallery = $product->getMediaGallery();
?>
<span class="zoom-icon">
    <a href="<?php echo Mage::helper('catalog/image')->init($product, 'image')->resize(500);?>" data-fancybox data-src="#modal<?php echo $product->getId();?>" title="<?php echo $product->getId()?>">
        <img src="<?php echo Mage::getBaseUrl('media').'wizard/zoom-icon.png';?>" alt="<?php echo $product->getSku()?>" class="mCS_img_loaded">
    </a>
    <div style="display: none;" class="custom-popup" id="modal<?php echo $product->getId();?>">
        <div class="popup-slider">
            <div class="popup-main-image">
                <?php if(count($gallery['images'])>0){ ?>
                    <?php foreach ($gallery['images'] as $img) : ?>
                        <div class="item"><img src="<?php echo Mage::helper('catalog/image')->init($product, 'thumbnail', $img['file'])->backgroundColor(255,255,255)->resize(100,100);?>" alt="<?php echo $product->getName();?>" /></div>
                    <?php endforeach; ?>
                <?php }else{ ?>
                    <div class="item"><img src="<?php echo Mage::getSingleton('catalog/product_media_config')->getBaseMediaUrl(). '/placeholder/' .Mage::getStoreConfig("catalog/placeholder/small_image_placeholder"); ?>" alt="" /></div>
                <?php } ?>
            </div>
            <div class="links">
                <a class="link wishlist-link" href="#"><span>Wish It</span></a>
                <a class="link" href="javascript:void(0);">
                    <div class="sharethis-inline-share-buttons"></div>
                    <script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a423282c4203c00110b8eca&product=unknown" async="async"></script>
                </a>
            </div>
        </div>
        <div class="popup-details">
            <input type="hidden" value="<?php echo $product->getId(); ?>">
            <h2><?php echo $product->getVariantRemark()?></h2>
            <p><?php echo $product->getItemName();?></p>
            <div class="price-box"><span class="price"><?php echo Mage::helper('core')->currency($price, true, false);?></span></div>
            <div class="links"> <a href="javascript:loadAjaxList(<?php echo $product->getId(); ?>);" class="link">View More</a> <a href="javascript:loadAjaxList(<?php echo $product->getId(); ?>);" class="link">I’ll Take This</a> </div>
            <div class="popup-thumb-image">
                <?php foreach ($gallery['images'] as $img) : ?>
                    <div class="item">
                        <img src="<?php echo Mage::helper('catalog/image')->init($product, 'thumbnail', $img['file'])->backgroundColor(255,255,255)->resize(100,100);?>" alt="<?php echo $product->getName();?>" /></div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</span>
<input type="hidden" class="productid" value="<?php echo $product->getId();?>">