<?php
$prms = $this->getRequest()->getParam('prms');
$editid = $this->getRequest()->getParam('editid');
$prid = $this->getRequest()->getParam('prid');
$promise = $this->getPromise($prid);
$selectedLength = '';
$helper = Mage::Helper('wizard');
$ringData = Mage::getSingleton('core/session')->getRingData();
$promiseSet = Mage::getSingleton('core/session')->getPromiseRing();

if($editid && !$prid){
    $pid = $promiseSet['did'];
}else{
    $promiseSet['promise'] = $promise['pid'];
    $promiseSet['chain'] = $chainid;
    $pid = $promiseSet['did'];
    Mage::getSingleton('core/session')->setPromiseRing($promiseSet);
}

//$helper->getRedirect($pid,'wizard');
$proceedUrl = Mage::getUrl('wizard/index/addtocart', array('did'=>$pid));

if(!empty($promise)):

$product = Mage::getModel('catalog/product')->load($promise['pid']);
$product->setVideo(Mage::getUrl().'media/video/Faaya-proposal-3-steps-final-video-FINAL-DESKTOP-4.mp4');
$gallery = $product->getMediaGallery();
$price = ($product->getSpecialPrice() && $product->getSpecialPrice() < $product->getPrice())?$product->getSpecialPrice():$product->getPrice();
$receiveDay =  $helper->getOrderDate($promise['pid']);
$rcdate = date('y-m-d',strtotime($receiveDay));
$rcdate = date_format(date_create($rcdate),"dS F, Y");

$promiseMetal = $this->getPromiseMetal();

$chainlength = Mage::Helper('wizard')->getChainlength($promise['pid']);
$chainType = Mage::Helper('wizard')->getChainType($promise['pid'],$chainlength[0]);
if(!empty($chainlength) && !empty($chainType)){
    $chainid = Mage::Helper('wizard')->getChainId($promise['pid'],$chainlength[0],$chainType[0]['chain_type']);
    $chainid = $chainid['pid'];
}else{
    $chainid = 0;
}

if($editid && !$prid){
    $selectedLength = Mage::Helper('wizard')->getSelectedlength($chainid);
    $chainid = $promiseSet['chain'];
}

$statictext = '';
$updateData = array();
if(isset($ringData[$promise['pid']]) && $ringData[$promise['pid']]['text'] != ''){
    $statictext = $ringData[$promise['pid']]['text'];
    $ringData[$promise['pid']]['text'] =  $statictext;
}else{
    $ringData[$promise['pid']]['text'] =  $statictext;
    $ringData[$promise['pid']]['fontfamily'] =  'Libre Baskerville';
}

if(isset($ringData[$promise['pid']]) && $ringData[$promise['pid']]['size'] != ''){
    $ringsize = $ringData[$promise['pid']]['size'];
    $ringData[$promise['pid']]['size'] =  $ringsize;
}else{
    $ringsize = $helper->getAttributeValue('product_size',$product->getProductSize());
    $ringData[$promise['pid']]['size'] =  $ringsize;
    Mage::getSingleton('core/session')->setRingData($ringData);
}


if($prms){
    $actionurl = Mage::getUrl('wizard/index/index/prms/1');
    $stepList = $helper->promisestepList(0,0,true);
}else{
    if($pid > 0){
        $actionurl = Mage::getUrl('wizard/completedset/index');
        $stepList = $helper->promisestepList(1,1,true);
    }else{
        $actionurl = Mage::getUrl('wizard/index/index/prms/1');
        $stepList = $helper->promisestepList(0,0,true);
    }
}
$promiseStart = ($prms)?true:false;
if($pid == 0){
    $promiseStart = true;
}
if($editid){
    $actionurl = $actionurl.'editid/'.$editid;
    $proceedUrl = Mage::getUrl('wizard/index/addtocart', array('did'=>$pid,'editid'=>$editid));
}


?>
<form method="POST" action="<?php echo $actionurl;?>" id="promiseform" name="promiseform">
<section class="main-content view-page">
        <div class="tabs">
            <ul>
                <?php foreach ($stepList as $value) { ?>
                    <li class="<?php echo $value['class'];?>">
                        <a href="<?php echo Mage::app()->getStore()->getUrl($value['url'])?>">
                            <span class="tab-info">
                                <span class="title"><?php echo $value['title'];?></span>
                                    <?php if($value['text'] != ''){
                                    echo $value['text'];
                                    }?>
                            </span>
                        </a>
                      </li>
                <?php } ?>
            </ul>
        </div>




        <?php if(!empty($chainlength) && !empty($chainType)){ ?>
            <input type="hidden" name="chain" value="<?php echo $chainid;?>">
        <?php } ?>

        <input type="hidden" name="did" value="<?php echo $pid;?>">
        <input type="hidden" name="promise" value="<?php echo $promise['pid'];?>">
        <input type="hidden" name="id" value="<?php echo $promise['pid'];?>">

        <div class="header-block-mobile">
            <div class="image">
                <img src="<?php echo $this->getSkinUrl('css/images/2.png'); ?>">
            </div>
            <div class="details">
                <h3><?php echo $product->getDescription();?></h3>
                <p class="desc"><?php echo $product->getItemName();?></p>
                <div class="price-box">
                    <span class="price"><?php echo Mage::helper('core')->currency($price, true, false);?></span>
                </div>
            </div>
        </div>
        <div class="col-right-side">
            <div class="title product-title-price title-mobile">
                <h2><?php echo $product->getDescription();?></h2>
            </div>
            <div class="view-completed-slider">
            <div class="view-completed-slider-product">
                <div class="view-completed-slider-links links">
                    <a class="link wish-it" href="#"><span><?php echo $this->__('Wish It');?></span></a>
                    <div class="sharethis-product">
                        <div class="sharethis-inline-share-buttons"></div>
                        <script type='text/javascript' src='//platform-api.sharethis.com/js/sharethis.js#property=5a423282c4203c00110b8eca&product=unknown' async='async'></script>
                    </div>
                </div>
                <div class="viewcomplete-image">
                    <?php if(count($gallery['images']) > 0 || $product->getVideo()){ ?>


                        <?php if(Mage::helper('wizard')->checkRemoteFile($product->getVideo())){ ?>
                        <div class="item">
                             <a class="icon-zoom video-zoom-icon" href="<?php echo $product->getVideo();?>" data-fancybox="wizard-slider"></a>
                            <div class="slick-video slick-video-2 video-box">
                              <video loop autobuffer>
                                  <source src="<?php echo $product->getVideo();?>" type=video/mp4>
                              </video>
                               <div class="control">
                                  <a href="javascript:void(0);" class="btnPlay pause"><i class="icon-play-pause" aria-hidden="true"></i></a>
                                  <a href="javascript:void(0);" class="muted" ><i class="icon-volume" aria-hidden="true"></i></a>
                              </div>
                          </div>
                        </div>
                        <?php } ?>
                        <?php foreach ($gallery['images'] as $item) {
                             $imageUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'catalog/product' . $item['file'];
                            ?>
                            <div class="item">
                                <a class="icon-zoom" href="<?php echo $imageUrl ?>" data-fancybox="wizard-slider">
                                    <img src="<?php echo Mage::helper('catalog/image')->init($product, 'thumbnail', $item['file'])->backgroundColor(255,255,255)->resize(600); ?>" alt="" />
                                </a>
                            </div>
                        <?php } ?>
                    <?php }else{ ?>
                        <div class="item">
                             <a class="icon-zoom" href="<?php echo Mage::getSingleton('catalog/product_media_config')->getBaseMediaUrl(). '/placeholder/' .Mage::getStoreConfig("catalog/placeholder/small_image_placeholder"); ?>" data-fancybox="wizard-slider">
                                <img src="<?php echo Mage::getSingleton('catalog/product_media_config')->getBaseMediaUrl(). '/placeholder/' .Mage::getStoreConfig("catalog/placeholder/small_image_placeholder"); ?>" alt="" />
                            </a>
                        </div>
                    <?php } ?>
                </div>
                <div class="viewcomplete-thumb">
                    <?php if(Mage::helper('wizard')->checkRemoteFile($product->getVideo())){ ?>
                        <div class="item"><img src="<?php echo $this->getSkinUrl('css/images/play-blue.png'); ?>" alt="" /></div>
                    <?php } ?>
                    <?php foreach ($gallery['images'] as $item) { ?>
                        <div class="item">
                            <img src="<?php echo Mage::helper('catalog/image')->init($product, 'thumbnail', $item['file'])->backgroundColor(255,255,255)->resize(90); ?>" alt="" />
                        </div>
                    <?php } ?>

                </div>

                <?php if(Mage::helper('wizard')->checkRemoteFile($product->getCertificatePdf())){ ?>
                <a class="certificate-pdf" href="<?php echo $product->getCertificatePdf();?>" style="text-align: center;display: table;margin: 0 auto;text-decoration: underline;" target="_blank" ><span><?php echo $this->__('Download Diamond Certificate');?></span></a>
                <?php } ?>
            </div>
            <div class="title product-title-price title-mobile">
                <h2><?php echo $product->getVariantRemark();?></h2>
                <p class="variant-name"><?php echo $product->getVariantName();?></p>
                 <div class="price-box">
                    <span class="price"><?php echo Mage::helper('core')->currency($price, true, false);?></span>
                </div>
            </div>
        </div>
        </div>
    <div class="col-left-side">
        <div class="details-blocks">
            <!-- <div class="blocks-navs">
                <?php /* ?><div class="backlink">
                    <a href="#"><?php echo $this->__('BACK');?></a>
                </div><?php */ ?>

            </div> -->
            <div class="title desktop product-title-price">
                <h1><?php echo $product->getDescription();?></h1>
                <div class="price-box">
                    <span class="price"><?php echo Mage::helper('core')->currency($price, true, false);?></span>
                </div>
            </div>
            <div class="col-sm-6 pull-right blocks-navs blocks-navs-btns">
                <button class="link next-links proceed btn addpromise"><?php echo $this->__('Add promise ring');?></button>
                <span id="errormessage" style="display: none;"><i class="fa fa-warning"></i> <?php echo $this->__('Please select ring size');?></span>
                 <?php if(!$promiseStart){ ?>
                 <a href="<?php echo $proceedUrl;?>" class="link next-links proceed btn"><?php echo $this->__('Checkout with diamond'); ?></a>
                 <?php } ?>
             </div>

            <?php /* ?><div class="delivery-date">
                <span class="date"><?php echo $this->__('Order now for delivery by');?> <strong><?php echo $rcdate;?></strong></span>
            </div><?php */ ?>
            <div class="details-content-section wizard-details-content-section">
                <div class="row">
                    <div class="col-sm-12 col-md-6 left">
                        <div class="preset-options wizard-preset-options metal-options">
                           <h3><?php echo $this->__('Choose color'); ?></h3>
                           <div class="options">
                              <ul class="metalkarat">
                                <?php foreach ($promiseMetal as $metal): ?>
                                    <?php $checked = ($metal['metal_color'] == $promise['metal_color'] && $metal['karat'] == $promise['karat'])?'checked="checked"':''; ?>
                                    <li>
                                        <input type="radio" name="metalkarat[]" id="metal_<?php echo $metal['metal_color'].'-'.$metal['karat']?>" <?php echo $checked;?> data-metal="<?php echo $metal['metal_color'];?>" data-karat="<?php echo $metal['karat'];?>" >
                                        <label for="metal_<?php echo $metal['metal_color'].'-'.$metal['karat']?>">
                                            <img src="<?php echo Mage::getBaseUrl('media').'wizard/metalcolor/'.strtolower($metal['metal_color'].'_'.$metal['karat']).'.png';?>">
                                            <span class="palettext">PLATED</span>
                                        </label>
                                    </li>
                                <?php endforeach;?>
                              </ul>
                           </div>
                        </div>
                        <div class="display-image">
                            <div class="image-wrapper">
                                <img src="<?php echo Mage::Helper('wizard')->getResizeImage($promise['image'],500,500); ?>" alt="Display image" />
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6 right">

                        <div class="inscription-block">
                            <h3><?php echo $this->__('Add an Inscription');?></h3>
                            <div class="preview-fonts-block">
                                <div class="predefined-fonts block">
                                    <select class="selectpicker" id="predefined" name="predefined">
                                        <option><?php echo $this->__('Select text')?></option>
                                        <option value="Amore fate">Amore fate</option>
                                        <option value="Only for you">Only for you</option>
                                        <option value="Just for you">Just for you</option>
                                    </select>
                                </div>
                                <div class="typing-field block">
                                    <input type="text" maxlength="20" name="promisetext" class="changeMe textchange" placeholder="Type here" value="<?php echo $statictext;?>">
                                    <p class="character-limit-text">Character left: <span id="charNum">20</span></p>
                                </div>
                            </div>
                            <div class="preview-text-block">
                                <div class="block preview-text">
                                    <h3><?php echo $this->__('Preview');?></h3>
                                    <div id="container" class="changeMe">
                                        <img src="<?php echo $this->getSkinUrl('images/change-image.jpg'); ?>" alt="" />
                                            <div class="sub" id="sub1">
                                                <div class="example">
                                                    <h3 class="centered" id="curvetext"><?php echo $statictext;?></h3>
                                                </div>
                                            </div>
                                    </div>
                                    <input type="hidden" name="prtext" id="prtext" value="<?php echo $statictext;?>">
                                </div>
                                 <div class="block fonts-define">
                                    <h3><?php echo $this->__('Font');?></h3>
                                    <ul id="fs">
                                       <li>
                                            <input type="radio" class="radio" id="afterschool" name="fonts-family" value="afterschool_festivalregular">
                                            <label style="font-family: 'afterschool_festivalregular' !important;" for="afterschool">Aa</label>
                                        </li>
                                         <li>
                                            <input type="radio" id="Baskerville" class="radio" name="fonts-family" checked="checked" value="Libre Baskerville">
                                            <label style="font-family: 'Libre Baskerville' !important;" for="Baskerville">Aa</label>
                                        </li>
                                    </ul>
                                </div>
                                <div class="save-button-block">
                                    <button type="button" onclick="savetext()" class="button save-button">Save</button>
                                    <span id="rpmessage"></span>
                                </div>
                            </div>
                        </div>

                         <div class="select-chain-block">
                            <h3><?php echo $this->__('Select Chain');?></h3>
                            <select class="selectpicker" id="chain_length" name="chain_length">
                                <?php foreach ($chainlength as $key=>$option): ?>
                                    <option value="<?php echo $option;?>" <?php if($selectedLength != '' && $selectedLength == $option){ echo 'selected="selected"'; } ?> ><?php echo $option;?></option>
                                <?php endforeach;?>
                            </select>
                             <select class="selectpicker" id="chain_type" name="chain_type">
                                <?php foreach ($chainType as $key=>$option) : ?>
                                    <option value="<?php echo $option['chain_type'];?>"><?php echo $option['chain_type'];?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                          <div class="ring-size-block ring-size-radio-block clickable">
                            <h3><?php echo $this->__('Ring Size');?></h3>
                            <?php $availableSizes = Mage::getModel('wizard/wizardrelation')->getAvailbleSizes($product,false);?>
                            <div class="ring-size-block-select">
                                <span class="selected-value"><span>6.0</span></span>
                                <ul class="ring-size-radio size-dropdown">
                                    <?php foreach ($availableSizes as $key=>$value) { ?>
                                        <?php //$cls = ($ringsize == $value)?'checked="checked"':'';?>
                                        <li>
                                            <input type="radio" <?php echo $cls;?> class="radio" id="<?php echo number_format($value,1);?>" name="availblesize" value="<?php echo number_format($value,1);?>">
                                            <label for="<?php echo number_format($value,1);?>"><?php echo number_format($value,1);?></label>
                                    <?php } ?>
                                </ul>
                            </div>
                            <a target="_blank" class="size-guide" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."wizard/sizeguide/sizeguide.pdf";?>"><?php echo $this->__('Size Guide');?></a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="blocks-navs bottom-block mobile-btn">
            <a class="link next-links proceed button" href="<?php echo $proceedUrl;?>" class="notnow-link"><?php echo $this->__('Not Now'); ?></a>
            <a class="link next-links proceed btn button" href="#"><?php echo $this->__('yes');?></a>
        </div>
    </div>
</section>
</form>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/wizard/circletype.min.js'); ?>"></script>
<script type="text/javascript">
        var BASE_URL = '<?php echo Mage::getBaseURL();?>';
        var pid='<?php echo $promise['pid'];?>';
        var promisestep='<?php echo $promiseStart;?>';
        var editid='<?php echo $editid;?>';

        jQuery(".textchange").keyup(function() {
            var val = jQuery('input[name="promisetext"]').val();
            var len = val.length;
            if (len > 20) {
                val = val.substring(0, 20);
            }else{
                jQuery('#charNum').text(20 - len);
            }
            jQuery('#container .centered').text(jQuery('input[name="promisetext"]').val());
            jQuery('#prtext').val(jQuery('input[name="promisetext"]').val());
             renderDemo();
        });
        jQuery("#fs").click(function() {
            var radioValue = jQuery("input[name='fonts-family']:checked").val();
            jQuery('.changeMe,.changeMe #curvetext').css("font-family", radioValue);
            renderDemo();
        });
        jQuery("#predefined").change(function() {
            jQuery('#container .centered').text(jQuery(this).val());
            jQuery('#prtext').val(jQuery(this).val());
             renderDemo();
        });

        function renderDemo() {
            new CircleType(document.getElementById('curvetext')).dir(-1).radius(275);
          }

         jQuery(window).load(function(){
            renderDemo();
         });

        jQuery(document).ready(function(){
            renderDemo();
            jQuery(".metalkarat input").click(function() {
                var metal = jQuery(this).data('metal');
                var karat = jQuery(this).data('karat');

                jQuery.ajax({
                    url: BASE_URL+"wizard/index/promiseupdate",
                    type: "POST",
                    data: { metal:metal,karat:karat,promisestep:promisestep,editid:editid},
                    success: function(redata){
                        window.location = redata;
                    },error: function(xhr){
                        window.location = xhr.responseText;
                    }
                })
            });
            jQuery(document).on('change','#chain_length',function () {
                var length = jQuery(this).val();
                jQuery.ajax({
                    url: BASE_URL+"wizard/index/chainoption",
                    type: "POST",
                    data: {pid:pid,length:length},
                    success: function(response){
                        response = JSON.parse(response);
                        jQuery('#chain_type').html(response.html);
                        jQuery('input[name="chain"]').val(response.id);
                    },error: function(xhr){
                        response = JSON.parse(xhr.responseText);
                        jQuery('#chain_type').html(response.html);
                        jQuery('input[name="chain"]').val(response.id);
                    }
                })
            })
            jQuery(document).on('change','#chain_type',function () {
                var length = jQuery('#chain_length').val();
                var type = jQuery(this).val();
                jQuery.ajax({
                    url: BASE_URL+"wizard/index/setchainid",
                    type: "POST",
                    data: {pid:pid,length:length,type:type},
                    success: function(response){
                        jQuery('input[name="chain"]').val(response);
                    },error: function(xhr){
                        jQuery('input[name="chain"]').val(xhr.responseText);
                    }
                })
            })
            jQuery(document).on('change','input[name="availblesize"]',function () {
                var ringsize = jQuery(this).val();
                jQuery.ajax({
                    url: BASE_URL+"wizard/index/setinscriptionsize",
                    type: "POST",
                    data: {pid:pid,size:ringsize}
                })
            })
            jQuery('.addpromise').click(function(e){
              if(jQuery('input[name="availblesize"]:checked').val() != undefined){
                jQuery("#promiseform").submit();
              }else{
                jQuery('#errormessage').show();
                setTimeout(function(){
                  jQuery('#errormessage').hide();
                },2000)
                return false;
              }
            })
        });
        function savetext(){
            var text = jQuery('#prtext').val();
            var fontfamily = jQuery('input[name="fonts-family"]:checked').val();
             jQuery('#rpmessage').html("<span>Processing...</span>").hide().fadeIn(1000, function() {
                jQuery('#rpmessage');
            });
            jQuery.ajax({
                url: BASE_URL+"wizard/index/setinscription",
                type: "POST",
                data: {pid:pid,text:text,fontfamily:fontfamily},
                 success: function(){
                    jQuery('#rpmessage').html("<span>Saved!</span>").hide().fadeIn(1000, function() {
                        jQuery('#rpmessage');
                    });
                    setTimeout(function() {
                      jQuery('#rpmessage').fadeOut("slow");
                    }, 3000 );

                  }
            })
        }

        //jQuery('.viewcomplete-image').on('afterChange', function(event, slick, currentSlide, nextSlide){
            //jQuery('#videoId')[0].play();
        //});
         jQuery(window).load(function(){
          if(jQuery('video').length > 0){
            jQuery('.slick-video video')[0].play();
          }
          jQuery('.viewcomplete-image').on('afterChange', function(event, slick, currentSlide, nextSlide){
              jQuery('.slick-video video').trigger('pause');
              jQuery('.btnPlay').addClass('pause');
              if(jQuery('.viewcomplete-image').find('.slick-current').find('video').length > 0){
                setTimeout(function () {
                    //jQuery('.slick-video video').trigger('play');
                     jQuery('.slick-video video')[0].play();
                },200);
              }
          });
      });
      VideoControls();
</script>
<?php else:?>
    <section class="main-content view-page">
        <?php echo $this->__("There is no promise ring availble."); ?>
        <a href="<?php echo Mage::getUrl('wizard');?>" class="backlink"><?php echo $this->__('Back to diamond'); ?></a>
        <a href="<?php echo $proceedUrl;?>" class="notnow-link"><?php echo $this->__('Not Now'); ?></a>
    </section>

<?php endif;?>