<?php $product = $this->getProduct();
$price = ($product['special_price'] && $product['special_price'] < $product['price'])?$product['special_price']:$product['price'];

if (@getimagesize($product['image'])) {
    $image = $product['image'];
}else{
    $image = Mage::getSingleton('catalog/product_media_config')->getBaseMediaUrl(). '/placeholder/' .Mage::getStoreConfig("catalog/placeholder/small_image_placeholder");
}
?>
<?php $currencyCode = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();?>
<li class="item" data-order="<?php echo $product['pid'];?>" data-price="<?php echo $price;?>">
    <div class="title-block">
        <h2 class="title"><a href="javascript:loadAjaxList(<?php echo $product['pid'];?>)"><?php echo $product['variant_name'];?></a></h2>
        <a class="compare-icon" href="javascript:void(0);"></a>
    </div>
    <div class="product-image">
        <a href="javascript:loadAjaxList(<?php echo $product['pid'];?>)"><img src="<?php echo $image;?>" alt=""></a>
    </div>
    <div class="product-zoom"><a href="javascript:void(0);" data-fancybox data-src="#custom-popup<?php echo $product['pid'];?>"><img src="<?php echo Mage::getBaseUrl('media').'wizard/zoom-icon.png' ?>" alt=""></a></div>
    <div class="product-info">
        <div class="price-box">
            <span class="price"><span class="price"><?php echo Mage::helper('core')->currency($price, true, false);?></span></span>
        </div>
        <div class="info"><?php //echo $product['variant_remark'];?></div>
    </div>
    <a class="compare-icon mobile" href="javascript:void(0);"></a>
</li>