<?php
$sku = $this->getRequest()->getParam('sku');
$helper = Mage::Helper('wizard');
$selected = $helper->getSelectedValue();
$diamondId = ($selected)?$selected['productId']:0;

$ringSelected = $helper->getRingSelected();
if($sku){
    $skufromId = Mage::getModel('catalog/product')->loadByAttribute('sku',$sku);
    //echo "<pre/>";print_r($skufromId->getId());exit;
    if($skufromId && $skufromId->isSaleable()){
        if($ringSelected){
                $ringSelected['productId'] = $skufromId->getId();
        }else{
                $ringSelected = array('productId'=>$skufromId->getId());
        }
        Mage::getSingleton('core/session')->setRingSelected(serialize($ringSelected));
        $ringSelected =  Mage::getSingleton('core/session')->getRingSelected();
        $ringSelected = unserialize($ringSelected);
    } else {
        $helper -> clearselection();
        Mage::app()->getFrontController()->getResponse()->setRedirect(Mage::app()->getStore()->getUrl('wizard'))->sendResponse();
    }
    //echo "<pre/>";print_r(unserialize(Mage::getSingleton('core/session')->getSelectedValue()));exit;
}
$pid = ($ringSelected)?$ringSelected['productId']:0;
$curCode = $helper->getCurSymbol();

$productSizeId = $helper->getAttributeId('product_size');
$shapeId = $helper->getAttributeId('stone_shape');
$metalTypeId = $helper->getAttributeId('metal_type');
$helper->getRedirect($pid,'wizard');

$shape = $helper->getShapeValue($selected,$ringSelected);

$product = $this->getProduct($pid);

if(!$product->isSaleable()){
    $helper -> clearselection();
    Mage::app()->getFrontController()->getResponse()->setRedirect(Mage::app()->getStore()->getUrl('wizard'))->sendResponse();
}

$gallery = $product->getMediaGallery();

$price = ($product->getSpecialPrice() && $product->getSpecialPrice() < $product->getPrice())?$product->getSpecialPrice():$product->getPrice();

$ringData =  Mage::getSingleton('core/session')->getRingData();
if(empty($ringData)){
    $ringData = array();
}

/*if(!isset($ringData[$product->getId()]['size'])){
    $ringData[$product->getId()]['size'] = Mage::Helper('wizard')->getAttributeValue('product_size',$product->getProductSize());
    Mage::getSingleton('core/session')->setRingData($ringData);
}*/

$stepOrder = ($diamondId > 0)?1:0;
$stepList = $helper->stepList(1,$stepOrder,false);
$proceedUrl = Mage::app()->getStore()->getUrl($stepList[$stepOrder+1]['url']);
$backlink = Mage::app()->getStore()->getUrl($stepList[$stepOrder]['backurl']);
if($product->getId()){
    $checkMetalOption = Mage::getModel('wizard/wizardrelation')->checkMetalOption($product);
}

$pinfo = $helper->getPinfo($pid);

$attribute = Mage::helper('wizard')->getAllAttribute();
?>
<input type="hidden" value="<?php echo $product->getId();?>">
<section class="main-content view-page">
    <div class="tabs">
            <ul>
                <?php foreach ($stepList as $value) { ?>
                    <li class="<?php echo $value['class'];?>">
                    <a href="<?php echo Mage::app()->getStore()->getUrl($value['url'])?>">
                        <span class="tab-info">
                            <span class="title"><?php echo $value['title'];?></span>
                                <?php if($value['text'] != ''){
                                echo $value['text'];
                                }?>
                        </span>
                    </a>
                  </li>
                <?php } ?>
            </ul>
        </div>
        <div class="col-right-side">
        <div class="view-completed-slider">
            <div class="view-completed-slider-product">
                <div class="view-completed-slider-links links">
                    <a class="link wish-it" href="#"><span><?php echo $this->__('Wish It');?></span></a>
                    <div class="sharethis-product">
                        <div class="sharethis-inline-share-buttons"></div>
                        <script type='text/javascript' src='//platform-api.sharethis.com/js/sharethis.js#property=5a423282c4203c00110b8eca&product=unknown' async='async'></script>
                    </div>
                </div>
                <div class="viewcomplete-image">
                    <?php if(count($gallery['images']) > 0 || $product->getVideo()){ ?>
                        <?php foreach ($gallery['images'] as $item) {

                           $imageUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'catalog/product' . $item['file'];
                          ?>
                            <div class="item">
                               <a class="icon-zoom" href="<?php echo $imageUrl ?>" data-fancybox="wizard-slider">
                                <img src="<?php echo Mage::helper('catalog/image')->init($product, 'thumbnail', $item['file'])->backgroundColor(255,255,255)->resize(600); ?>" alt="" />
                              </a>
                            </div>
                        <?php } ?>

                        <?php if(Mage::helper('wizard')->checkRemoteFile($product->getVideo())){ ?>
                        <div class="item">
                            <!-- <a class="icon-zoom video-zoom-icon" data-fancybox="wizard-slider" href=""></a> -->
                            <a class="icon-zoom video-zoom-icon" href="<?php echo $product->getVideo();?>" data-fancybox="wizard-slider"></a>
                            <div class="slick-video slick-video-2 video-box">
                              <video id="videoId" autoplay="autoplay" loop="loop" onstart="this.play();" onended="this.play();" autobuffer>
                                  <source src="<?php echo $product->getVideo();?>" type=video/mp4>
                              </video>
                              <div class="control">
                                  <a href="javascript:void(0);" class="btnPlay pause"><i class="icon-play-pause" aria-hidden="true"></i></a>
                                  <a href="javascript:void(0);" class="muted" ><i class="icon-volume" aria-hidden="true"></i></a>
                              </div>

                          </div>
                        </div>
                        <?php } ?>
                    <?php }else{ ?>
                        <div class="item">
                          <a  class="icon-zoom" href="<?php echo Mage::getSingleton('catalog/product_media_config')->getBaseMediaUrl(). '/placeholder/' .Mage::getStoreConfig("catalog/placeholder/small_image_placeholder"); ?>" data-fancybox="wizard-slider">
                            <img src="<?php echo Mage::getSingleton('catalog/product_media_config')->getBaseMediaUrl(). '/placeholder/' .Mage::getStoreConfig("catalog/placeholder/small_image_placeholder"); ?>" alt="" />
                          </a>
                        </div>
                    <?php } ?>
                </div>
                <div class="viewcomplete-thumb">
                    <?php foreach ($gallery['images'] as $item) { ?>
                        <div class="item">
                            <img src="<?php echo Mage::helper('catalog/image')->init($product, 'thumbnail', $item['file'])->backgroundColor(255,255,255)->resize(90); ?>" alt="" />
                        </div>
                    <?php } ?>
                    <?php if(Mage::helper('wizard')->checkRemoteFile($product->getVideo())){ ?>
                        <div class="item"><img src="<?php echo $this->getSkinUrl('css/images/video-icons.png'); ?>" alt="" /></div>
                    <?php } ?>
                </div>

                <?php if(Mage::helper('wizard')->checkRemoteFile($product->getCertificatePdf())){ ?>
                <a class="certificate-pdf" href="<?php echo $product->getCertificatePdf();?>" style="text-align: center;display: table;margin: 0 auto;text-decoration: underline;" target="_blank" ><span><?php echo $this->__('Download Diamond Certificate');?></span></a>
                <?php } ?>
            </div>
            <div class="title product-title-price title-mobile">
                <h2><?php echo $product->getVariantRemark();?></h2>
                <p class="variant-name"><?php echo $product->getDescription();?></p>
                 <div class="price-box">
                    <span class="price"><?php echo Mage::helper('core')->currency($price, true, false);?></span>
                </div>
            </div>
        </div>
    </div>
    <div class="col-left-side">
        <div class="details-blocks">
			<div class="blocks-navs">
				<div class="backlink">
					<a href="<?php echo $backlink;?>"><?php echo $this->__('SELECT SETTING');?></a>
				</div>
        <div class="proceed-btns">
				 <a class="link next-links proceed btn" href="javascript:void(0)" data-proceed="<?php echo $proceedUrl;?>"><?php echo $this->__('proceed');?></a>
          <span id="errormessage" style="display: none;"><i class="fa fa-warning"></i> <?php echo $this->__('Please select ring size');?></span>
        </div>

			</div>
            <div class="title desktop product-title-price">
                <h1><?php echo $product->getVariantRemark()?>
                    <p class="variant-name"><?php echo $product->getDescription();?></p>
                </h1>

				 <div class="price-box">
					<span class="price"><?php echo Mage::helper('core')->currency($price, true, false);?></span>
                </div>
            </div>
            <div class="details-content-section">
                <div class="row">
                    <div class="col-sm-12 col-md-6 left">
                        <h3><?php echo $this->__('Summary');?></h3>
                        <div class="details-tbl">
                            <ul>
                                <?php foreach ($this->getRingArry('left') as $item) { ?>
                                <li>
                                    <span class="title"><?php echo $helper->getAttrTitle($item);?>
                                        <?php if($helper->getTooltip($item)){ ?>
                                        <div class="tooltip-options">
                                            <div class="tooltip-image">
                                                <img src="<?php echo $this->getSkinUrl('css/images/info-icon.png') ?>" alt="">
                                            </div>
                                            <div class="tooltip-content">
                                                <a class="close-btn" href="javascript:void(0)"><img src="<?php echo $this->getSkinUrl('css/images/close-icon2.png'); ?>" alt=""></a>
                                                <h3><?php echo $helper->getAttrTitle($item);?></h3>
                                                    <?php echo $helper->getTooltip($item);?>
                                            </div>
                                        </div>
                                        <?php } ?>
                                   </span>
                                   <span class="value">
                                    <?php
                                    $function = (string)$item['function'];
                                    if($item['function'] != '' && Mage::getModel('wizard/wizardrelation')->$function($product,true)){
                                        echo  Mage::getModel('wizard/wizardrelation')->$function($product,true);
                                    }elseif($item['oid']){
                                        echo $helper->getAttributeValue($item['code'],$product->getData($item['code']));
                                    }elseif($product->getData($item['code']) != ''){
                                        echo $product->getData($item['code']);
                                    }else{
                                        echo "N/A";
                                    }
                                    ?>
                                    </span>
                                </li>
                                <?php } ?>
                            </ul>
                        </div>
                        <?php if($pinfo){ ?>
                                    <?php
                                    $pinfo = unserialize($pinfo);
                                    $pieces = 0;
                                    $piecesweight = 0;
                                    if(count($pinfo) > 0){
                                      foreach ($pinfo as $pinfoitem) {
                                        $pieces += $pinfoitem['PIECES'];
                                        $piecesweight += $pinfoitem['WEIGHT'];
                                      }
                                      $pinfo['STONE_COLOR'] = $pinfo[0]['STONE_COLOR'];
                                      $pinfo['QUALITY'] = $pinfo[0]['QUALITY'];
                                      $pinfo['PIECES'] = $pieces;
                                      $pinfo['WEIGHT'] = $piecesweight;
                                    }else{
                                        $pinfo = $pinfo;
                                    }
                                    ?>
                                <h3><?php echo $this->__('SUMMARY - '); ?><span><?php echo $this->__('Pave set diamond'); ?></span></h3>
                                <p class="p_detail"><?php echo $this->__('Closely spaced gemstone are set with tiny prongs so that the surface appears to be “paved” with gemstones.'); ?></p>
                                <div class="details-tbl">
                                   <ul>
                                      <li>
                                         <span class="title"><?php echo $this->__('Minimum number of round diamonds'); ?>
                                         </span>
                                         <span class="value"><?php echo $pinfo['PIECES']; ?></span>
                                      </li>
                                      <li>
                                         <span class="title"><?php echo $this->__('Minimum carat total weight (CT. W.)'); ?>
                                            <div class="tooltip-options">
                                               <div class="tooltip-image">
                                                  <img src="<?php echo $this->getSkinUrl('css/images/info-icon.png'); ?>" alt="">
                                               </div>
                                               <div class="tooltip-content">
                                                  <a class="close-btn" href="javascript:void(0)">
                                                    <img src="<?php echo $this->getSkinUrl('css/images/close-icon2.png'); ?>" alt="">
                                                  </a>
                                                 <?php echo $helper->getTooltip($attribute['WEIGHT'],$titleHelper);?>
                                               </div></div>
                                         </span>
                                         <span class="value"><?php echo $pinfo['WEIGHT']; ?></span>
                                      </li>
                                      <li>
                                         <span class="title"><?php echo $this->__('Average Colour') ?>
                                         <div class="tooltip-options">
                                               <div class="tooltip-image">
                                                  <img src="<?php echo $this->getSkinUrl('css/images/info-icon.png'); ?>" alt="">
                                               </div>
                                               <div class="tooltip-content">
                                                  <a class="close-btn" href="javascript:void(0)">
                                                    <img src="<?php echo $this->getSkinUrl('css/images/close-icon2.png'); ?>" alt="">
                                                  </a>
                                                  <?php echo $helper->getTooltip($attribute['STONE_COLOR'],$titleHelper);?>
                                               </div></div>
                                         </span>
                                         <span class="value"><?php echo $pinfo['STONE_COLOR']; ?></span>
                                      </li>
                                      <li>
                                         <span class="title"><?php echo $this->__('Average Clarity'); ?>
                                            <div class="tooltip-options">
                                               <div class="tooltip-image">
                                                  <img src="<?php echo $this->getSkinUrl('css/images/info-icon.png'); ?>" alt="">
                                               </div>
                                               <div class="tooltip-content">
                                                  <a class="close-btn" href="javascript:void(0)">
                                                    <img src="<?php echo $this->getSkinUrl('css/images/close-icon2.png'); ?>" alt="">
                                                  </a>
                                                  <?php echo $helper->getTooltip($attribute['STONE_QUALITY'],$titleHelper);?>
                                               </div></div>
                                         </span>
                                         <span class="value"><?php echo $pinfo['QUALITY']; ?></span>
                                      </li>
                                   </ul>
                                </div>
                        <?php } ?>

                    </div>
                    <div class="mobile-cirtificate">
                        <?php if(Mage::helper('wizard')->checkRemoteFile($product->getCertificatePdf())){ ?>
                            <a class="certificate-pdf" href="<?php echo $product->getCertificatePdf();?>" style="text-align: center;display: table;margin: 0 auto;text-decoration: underline;" target="_blank" ><span><?php echo $this->__('Download Diamond Certificate');?></span></a>
                        <?php } ?>
                    </div>
                    <div class="col-sm-12 col-md-6 right">
                        <div class="ring-size-block ring-size-radio-block clickable">
                            <h3><?php echo $this->__('Ring Size');?></h3>
                            <div class="ring-size-block-select">
                              <span class="selected-value"><span>6.0</span></span>
                              <ul class="cls<?php echo $productSizeId;?> size-dropdown">
                                  <?php
                                  $availableSizes = Mage::getModel('wizard/wizardrelation')->getAvailbleSizes($product,false);
                                  ?>
                                  <?php foreach ($availableSizes as $key=>$value) { ?>
                                      <?php $cls = ($ringData[$product->getId()]['size'] == $value)?'selected':'';?>
                                      <li class="<?php echo $cls;?>">
                                        <a href="javascript:void(0)" id="<?php echo 'size_'.$value;?>" data-index="<?php echo $key;?>" data-id="<?php echo $productSizeId;?>"><?php echo number_format($value,1);?></a></li>
                                  <?php } ?>
                              </ul>
                            </div>
                            <a target="_blank" class="size-guide" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."wizard/sizeguide/sizeguide.pdf";?>"><?php echo $this->__('Size Guide');?></a>
                        </div>
                        <?php if($helper->getOptionbyItem('stone_shape',$product->getItemId())){ ?>

                         <div class="round-shape-option">
                            <h3><?php echo $this->__('Sets with'); ?></h3>
                             <ul>
                            <?php
                             foreach ($helper->getOptionbyItem('stone_shape',$product->getItemId()) as $diShape) {
                                $cls = (strtolower($shape) == strtolower($diShape['label']))?'selected':'';
                                ?>
                                <li class="<?php echo $cls;?>"><a href="javascript:void(0)" id="<?php echo $diShape['value'].'_'.$product->getItemId();?>" class="shapeOpt"><img src="<?php echo Mage::getBaseUrl('media').'wizard/shapes/'.strtolower(str_replace(' ', '_', $diShape['label'])).'.png'; ?>">
                                  <span><?php echo $diShape['label'] ?></span>
                                </a></li>
                            <?php } ?>

                         </div>
                         <?php } ?>

                          <div class="metal-option clickable">
                             <h3><?php echo $this->__('Metal');?> <span>- <?php echo strtoupper($helper->getAttributeValue('metal_color',$product->getMetalColor()));?></span></h3>
                             <ul>
                                <?php
                                 foreach ($helper->getAllOptions('metal_color') as $mColor) {

                                    foreach ($helper->getAllOptions('karat') as $karat) {
                                        if(!in_array($mColor['value'].'-'.$karat['value'], array_keys($checkMetalOption))){
                                            continue;
                                        }
                                        $cls = ($product->getMetalColor() == $mColor["value"] && $product->getKarat() == $karat["value"])?'selected':'';
                                        ?>
                                        <li class="<?php echo $cls;?>">
                                            <a href="javascript:void(0)" id="<?php echo $metalTypeId.'_'.$mColor["value"].'_'.$karat["value"];?>" class="metalOpt">
                                                <img src="<?php echo $this->getSkinUrl('css/images/'.strtolower(str_replace(' ', '_', $mColor["label"])).'_'.$karat["label"].'.png'); ?>">
                                            </a>

                                        </li>
                                    <?php }
                                }
                                ?>

                             </ul>
                         </div>

                    </div>
                </div>
            </div>
        </div>


    </div>

</section>


<script type="text/javascript">




   var BASE_URL='<?php echo preg_replace('/(.*?)(index.php\/?)?/','\1',Mage::getBaseURL());?>';
    var productId='<?php echo $product->getId();?>';
    jQuery(document).ready(function(){


        jQuery('.next-links').click(function(e){
          var href = jQuery(this).data('proceed');
          e.preventDefault();
          if(jQuery(".size-dropdown").find('li.selected').length > 0){
            window.location = href;
          }else{
            jQuery('#errormessage').show();
            setTimeout(function(){
              jQuery('#errormessage').hide();
            },2000)
            return false;
          }
        })


        jQuery('.clickable ul li a').click(function(){
            var metalOption = jQuery(this).hasClass('metalOpt');
            var shapeOption = jQuery(this).hasClass('shapeOpt');
            var dataindex = jQuery(this).data('index');
            var dataid = jQuery(this).data('id');
            setData(jQuery(this).attr('id'),metalOption,shapeOption,dataindex,dataid);
        })

        jQuery('.backlink a').click(function(e){
            var href = jQuery(this).attr('href');
            e.preventDefault();
            jQuery.fancyConfirm({
              title: "Setting selection",
              message: "Please note that your setting selection will be refreshed and you will have to select a setting again.",
              okButton: 'Ok, I understand',
              noButton: 'No, I like this',
              helpers : {
                  overlay : {
                      locked: false
                  }
              },
              callback: function (value) {
                if(value){
                  window.location = href;
                }else{
                  return false;
                }
              }
            });
            return false;
        })
    })
    var detailsSidebarSticky = jQuery('.wizard-ringdetail-index .page-header').offset().top;
    jQuery(window).scroll(function (){
        jQuery('.col-right-side').removeClass('sidebar-fixed');
        if (jQuery(window).scrollTop() >= detailsSidebarSticky) {
           jQuery('.col-right-side').addClass('sidebar-fixed');
        }
        else {
           jQuery('.col-right-side').removeClass('sidebar-fixed');
        }
    });
    function setData(id,metalOption,shapeOption,dataindex,dataid){
        jQuery.ajax({
            url: BASE_URL+"wizard/index/setringdata",
            type: "POST",
            data: {id:id,pid:productId,metaloption:metalOption,shapeoption:shapeOption},
            success: function(redata){
                if(metalOption || shapeOption){
                    location.reload();
                }else{
                    jQuery('.cls'+dataid).find('li').removeClass('selected');
                    jQuery('.cls'+dataid).find('li').eq(dataindex).addClass('selected');
                }
            },error: function(xhr){
                if(metalOption || shapeOption){
                    location.reload();
                }else{
                    jQuery('.cls'+dataid).find('li').removeClass('selected');
                    jQuery('.cls'+dataid).find('li').eq(dataindex).addClass('selected');
                }
            }
        })
    }


       jQuery(window).load(function(){
          if(jQuery('video').length > 0){
            jQuery('.slick-video video').trigger('play');
          }
          jQuery('.viewcomplete-image').on('afterChange', function(event, slick, currentSlide, nextSlide){
              jQuery('.slick-video video').trigger('pause');
              jQuery('.btnPlay').addClass('pause');
              if(jQuery('.viewcomplete-image').find('.slick-current').find('video').length > 0){
                setTimeout(function () {
                    jQuery('.slick-video video').trigger('play');
                },200);
              }
          });
      });
      VideoControls();

</script>