<?php
$editid = $this->getRequest()->getParam('editid');
$helper = Mage::Helper('wizard');
$attribute = Mage::helper('wizard')->getAllAttribute();
$ringSelected = $helper->getRingSelected();
$pid = ($ringSelected)?$ringSelected['productId']:0;
$ringId = $pid;
$helper->getRedirect($ringId,'wizard/ring');


$selected =  Mage::getSingleton('core/session')->getSidestone();
if($selected != ''){
    $selected = unserialize($selected);
    $pid1 = $selected['pid1'];
    $pid2 = $selected['pid2'];
}else{
    $pid1 = 0;
    $pid2 = 0;
}
$pid = $pid1;

$id = $this->getRequest()->getParam('id');
if($id){
    if($id == 'dmd2'){
        $pid = $pid2;
    }
}

$product = Mage::getModel('catalog/product')->load($pid);
$product->load('media_gallery');
$stoneShape =  strtolower($helper->getAttributeValue('stone_shape',$product->getStoneShape()));
$gallery = $product->getMediaGallery();
$price = ($product->getSpecialPrice() && $product->getSpecialPrice() < $product->getPrice())?$product->getSpecialPrice():$product->getPrice();

$curCode = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();

$helper = Mage::Helper('wizard');
$proceedUrl = ($editid)?Mage::app()->getStore()->getUrl('wizard/completed/index/editid/'.$editid):Mage::app()->getStore()->getUrl('wizard/completed');

$stepList = $helper->stepList(2,2,false);
$backlink = Mage::app()->getStore()->getUrl($stepList[2]['backurl']);
?>
<section class="main-content view-page">
    <div class="tabs">
        <ul>
            <?php foreach ($helper->stepList(2,2,false) as $value) { ?>
                <li class="<?php echo $value['class'];?>">
                    <a href="<?php echo Mage::app()->getStore()->getUrl($value['url'])?>">
                        <span class="tab-info">
                            <span class="title"><?php echo $value['title'];?></span>
                                <?php if($value['text'] != ''){
                                echo $value['text'];
                                }?>
                        </span>
                    </a>
                  </li>
            <?php } ?>
        </ul>
    </div>

    <div class="col-right-side">
        <div class="view-completed-slider">
            <div class="view-completed-slider-product">
                <div class="view-completed-slider-links links">
                    <a class="link-wishlist link wish-it" href="<?php echo $this->helper('wishlist')->getAddUrl($product) ?>"><span><?php echo $this->__('Wish It');?></span></a>
                    <div class="sharethis-product">
                        <div class="sharethis-inline-share-buttons"></div>
                        <script type='text/javascript' src='//platform-api.sharethis.com/js/sharethis.js#property=5a423282c4203c00110b8eca&product=unknown' async='async'></script>
                    </div>
                </div>
                <?php //if(count($gallery['images']) > 0 || $product->getVideoUrl()){ ?>
                <div class="viewcomplete-image">
                    <?php foreach ($gallery['images'] as $item) { ?>
                        <div class="item">
                            <img src="<?php echo Mage::helper('catalog/image')->init($product, 'thumbnail', $item['file'])->resize(600); ?>" alt="" />
                        </div>
                    <?php } ?>

                    <?php if(Mage::helper('wizard')->checkRemoteFile($product->getVideo())){ ?>
                    <div class="item">
                        <div class="slick-video slick-video-2 video-box">
                            <video id="videoId" autoplay="autoplay" loop="loop" onstart="this.play();" onended="this.play();" autobuffer>
                                <source src="<?php echo $product->getVideo();?>" type=video/mp4>
                            </video>
                            <div class="control">
                              <a href="javascript:void(0);" class="btnPlay pause"><i class="icon-play-pause" aria-hidden="true"></i></a>
                              <a href="javascript:void(0);" class="muted" ><i class="icon-volume" aria-hidden="true"></i></a>
                          </div>

                        </div>
                    </div>
                    <?php } ?>
                    <div class="item">
                        <img src="<?php echo $this->getSkinUrl('images/hand.png'); ?>" alt="" />
                    </div>
                </div>
                <?php /* }else{ ?>
                    <div class="item">
                        <img src="<?php echo Mage::getSingleton('catalog/product_media_config')->getBaseMediaUrl(). '/placeholder/' .Mage::getStoreConfig("catalog/placeholder/small_image_placeholder"); ?>" alt="" />
                    </div>
                <?php } */ ?>
                <div class="viewcomplete-thumb">
                   <?php foreach ($gallery['images'] as $item) { ?>
                        <div class="item">
                            <img src="<?php echo Mage::helper('catalog/image')->init($product, 'thumbnail', $item['file'])->backgroundColor(255,255,255)->resize(90); ?>" alt="" />
                        </div>
                    <?php } ?>
                    <?php if(Mage::helper('wizard')->checkRemoteFile($product->getVideo())){ ?>
                        <div class="item"><img src="<?php echo $this->getSkinUrl('css/images/video-icons.png'); ?>" alt="" /></div>
                    <?php } ?>
                    <div class="item">
                        <img src="<?php echo $this->getSkinUrl('images/hand.png'); ?>" alt="" />
                    </div>
                </div>
                    <?php if($ringId == 0){ ?>
                        <div class="addtolinks" style="display: none;"><!-- Only for testing Please remove dipaly:none -->
                            <ul>
                                <?php /*if(!$looseDiamond): ?>
                                <li>
                                    <a class="link add-your-ring" href="<?php echo Mage::app()->getStore()->getUrl('wizard/ring')?>"><img src="<?php echo $this->getSkinUrl('css/images/ring.png'); ?>" alt=""><span><?php echo $this->__('Add to your Ring');?></span></a>
                                </li>
                                <?php endif;*/ ?>
                                <li>
                                    <a class="link add-personal-ring" href="#"><img src="<?php echo $this->getSkinUrl('css/images/per-ring.png'); ?>" alt=""><span><?php echo $this->__('Add a Proposal Ring');?></span></a>
                                </li>
                            </ul>
                        </div>
                    <?php } ?>

                    <?php if(Mage::helper('wizard')->checkRemoteFile($product->getCertificatePdf())){ ?>
                    <a class="certificate-pdf" href="<?php echo $product->getCertificatePdf();?>" target="_blank" ><span><?php echo $this->__('Download Diamond Certificate');?></span></a>
                    <?php } ?>
            </div>
            <div class="title product-title-price title-mobile">
                <h2><?php echo $product->getVariantRemark()?></h2>
                <p><?php echo $product->getItemName();?></p>
                 <div class="price-box">
                    <span class="price"><?php echo Mage::helper('core')->currency($price, true, false);?></span>
                </div>
            </div>
        </div>

    </div>
    <div class="col-left-side">
        <div class="details-blocks">
            <div class="backlink">
                <a href="<?php echo $backlink;?>"><?php echo $this->__('SELECT SIDESTONES');?></a>
            </div>
            <div class="title product-title-price desktop">
                <h1><?php echo $product->getName();?></h1>
                <div class="price-box">
                    <span class="price"><?php echo Mage::helper('core')->currency($price, true, false);?></span>
                </div>
            </div>
            <div class="sidestone hidden-xs">
                <a class="btn <?php if($pid == $pid1){ echo "selected"; }?>" href="" id="dmd1">Diamond1</a>
                <a class="btn <?php if($pid == $pid2){ echo "selected"; }?>" href="" id="dmd2">Diamond2</a>
            </div>
            <div class="blocks-navs">
                <a class="link next-links proceed btn" href="<?php echo $proceedUrl;?>"><?php echo $this->__('Next');?></a>
            </div>
            <div class="delivery-date">
                <ul class="links">
                    <li><?php echo $this->__('Free Shipping');?></li>
                    <li><?php echo $this->__('Free returns');?></li>
                    <li><?php echo $this->__('Free resizing');?></li>
                </ul>
            </div>
            <div class="details-content-section">
                <div class="row">
                    <div class="col-sm-12 col-md-6 left">
                        <h3><?php echo $this->__('Summary');?> - <span><?php echo $this->__('Diamond');?></span></h3>
                        <div class="details-tbl">
                            <ul>
                                <?php foreach ($this->getAttributeArry('left') as $item) { ?>
                                    <li>
                                        <span class="title"><?php echo $helper->getAttrTitle($item);?>
                                            <?php if($helper->getTooltip($item)){ ?>
                                            <div class="tooltip-options">
                                                <div class="tooltip-image">
                                                    <img src="<?php echo $this->getSkinUrl('css/images/info-icon.png') ?>" alt="">
                                                </div>
                                                <div class="tooltip-content">
                                                    <a class="close-btn" href="javascript:void(0);">
                                                        <img src="<?php echo $this->getSkinUrl('css/images/close-icon2.png'); ?>" alt="">
                                                    </a>
                                                    <?php echo $helper->getTooltip($item);?>
                                                </div>
                                            </div>
                                            <?php } ?>
                                        </span>
                                        <span class="value">
                                            <?php
                                            if($item['oid']){
                                                echo $helper->getAttributeValue($item['code'],$product->getData($item['code']));
                                            }elseif($product->getData($item['code']) != ''){
                                                if($item['number_format']){
                                                    echo number_format($product->getData($item['code']),2);
                                                }else{
                                                    if($item['code'] == 'certificate_no' && Mage::helper('wizard')->checkRemoteFile($product->getCertificatePdf())){ ?>

                                                        <a class="diamond-pdf" href="<?php echo $product->getCertificatePdf();?>" target="_blank" ><span><?php echo $product->getData($item['code']);?></span></a>

                                                        <?php
                                                    }else{
                                                        echo $product->getData($item['code']);
                                                    }
                                                }
                                            }else{
                                                echo "N/A";
                                            }
                                            ?>
                                        </span>
                                    </li>
                                <?php } ?>
                            </ul>
                        </div>

                    </div>
                    <div class="col-sm-12 col-md-6 right">
                        <div class="details-tbl top-mrgn">
                            <ul>
                                <?php foreach ($this->getAttributeArry('right') as $item) { ?>
                                    <li>
                                        <span class="title"><?php echo $item['title'];?>
                                            <?php if($item['tooltip'] != ''){ ?>
                                            <div class="tooltip-options">
                                                <div class="tooltip-image">
                                                    <img src="<?php echo $this->getSkinUrl('css/images/info-icon.png') ?>" alt="">
                                                </div>
                                                <div class="tooltip-content">
                                                    <a class="close-btn" href="javascript:void(0);"><img src="<?php echo $this->getSkinUrl('css/images/close-icon2.png'); ?>" alt=""></a>
                                                    <h3><?php echo $this->__('Color Grade');?></h3>
                                                    <img src="<?php echo $this->getSkinUrl('css/images/tooltip-img1.png'); ?>" alt="">
                                                    <p><?php echo $this->__('Near-colorless.');?> <br><?php echo $this->__('Slightly detected color—a good value.');?></p>
                                                </div>
                                            </div>
                                            <?php } ?>
                                        </span>
                                        <span class="value">
                                            <?php
                                            if($item['oid']){
                                                echo $helper->getAttributeValue($item['code'],$product->getData($item['code']));
                                            }elseif($product->getData($item['code']) != ''){
                                                echo $product->getData($item['code']);
                                            }else{
                                                echo "N/A";
                                            }

                                            ?>
                                        </span>
                                    </li>
                                <?php } ?>
                            </ul>
                        </div>

                    </div>
                </div>
                <div class="diamond-type details-diamond-type">
                    <div class="item diamond-item diamond-color-item">
                        <div class="content">
                            <h3><?php echo $helper->getAttributeValue('stone_color',$product->getStoneColor());?><?php echo $this->__(' Colour');?>
                            <div class="tooltip-options">
                                    <div class="tooltip-image">
                                        <img src="<?php echo $this->getSkinUrl('css/images/tootlp-icon.png'); ?>" alt="">
                                    </div>
                                    <div class="tooltip-content">
                                        <a class="close-btn" href="javascript:void(0);"><img src="<?php echo $this->getSkinUrl('css/images/close-icon2.png');?>" alt=""></a>
                                        <p><?php echo $helper->getTooltip($attribute['STONE_COLOR'],$titleHelper);?></p>
                                    </div>
                                </div>
                            </h3>
                            <p><?php echo $this->__('The lesser the color, the higher the diamond grade.');?></p>
                        </div>
                        <div class="item-option">
                            <ul>
                                <?php foreach ($helper->getChangeAttrribute('stone_color') as $value) { ?>
                                        <li class="<?php if(strtolower($value) == strtolower($helper->getAttributeValue('stone_color',$product->getStoneColor()))){ echo 'active';} ?>">
                                            <img src="<?php echo Mage::getBaseUrl('media').'wizard/colour/'.strtolower($value).'.png';?>">

                                            <span><?php echo $value;?></span>
                                        </li>
                                    <?php
                                } ?>
                            </ul>
                        </div>
                    </div>
                    <div class="item caratr-item">
                        <div class="content">
                            <h3><?php echo round($product->getCarat(), 2);?> <?php echo $this->__('Carat');?><div class="tooltip-options">
                                    <div class="tooltip-image">
                                        <img src="<?php echo $this->getSkinUrl('css/images/tootlp-icon.png'); ?>" alt="">
                                    </div>
                                    <div class="tooltip-content">
                                        <a class="close-btn" href="javascript:void(0);"><img src="<?php echo $this->getSkinUrl('css/images/close-icon2.png');?>" alt=""></a>
                                        <p><?php echo $helper->getTooltip($attribute['WEIGHT'],$titleHelper);?></p>
                                    </div>
                                </div></h3>
                            <p><?php echo $this->__('Carat is the total weight of the diamond and not its size.');?></p>
                        </div>
                        <div class="item-option ">
                            <ul>
                                <?php for ($i = 0; $i < 7; $i++) { ?>
                                    <li><img src="<?php echo Mage::getBaseUrl('media').'wizard/carat/'.($i+1).'.png';?>"><span><?php echo $i;?> Ct</span>
                                    <?php
                                    $caratValue = round($product->getCarat(), 2);
                                    $left = 50;
                                    if($caratValue > $i-0.5 && $caratValue <= $i+0.5){
                                        $whole = floor($caratValue);
                                        $fraction = $caratValue - $whole;
                                        $fraction = explode('.', $fraction);
                                        if(strlen($fraction[1]) == 1){
                                            $fraction[1] = $fraction[1].'0';
                                        }
                                        if($caratValue != $i && $caratValue != $i+0.5){
                                            if($caratValue > $i){
                                                $left = $fraction[1]+50;
                                            }else{
                                                $left = $fraction[1]-50;
                                            }
                                        }else if($caratValue == $i+0.5){
                                            $left = 100;
                                        }
                                     ?>
                                        <i style="left: <?php echo $left;?>%"><?php echo $caratValue;?></i>
                                    <?php } ?>
                                </li>
                                <?php } ?>
                            </ul>
                        </div>
                    </div>
                    <div class="item diamond-item clarity-item">
                        <div class="content">
                            <h3><?php echo $helper->getAttributeValue('stone_quality',$product->getStoneQuality());?> <?php echo $this->__('Clarity');?><div class="tooltip-options">
                                    <div class="tooltip-image">
                                        <img src="<?php echo $this->getSkinUrl('css/images/tootlp-icon.png'); ?>" alt="">
                                    </div>
                                    <div class="tooltip-content">
                                        <a class="close-btn" href="javascript:void(0);"><img src="<?php echo $this->getSkinUrl('css/images/close-icon2.png');?>" alt=""></a>
                                        <p><?php echo $helper->getTooltip($attribute['STONE_QUALITY'],$titleHelper);?></p>
                                    </div>
                                </div></h3>
                            <p><?php echo $this->__('Clarity depends on the tiny imperfections of a diamond.');?></p>
                        </div>
                        <div class="item-option">
                            <ul>
                                <?php foreach ($helper->getChangeAttrribute('stone_quality') as $value) { ?>
                                        <li class="<?php if(strtolower($value) == strtolower($helper->getAttributeValue('stone_quality',$product->getStoneQuality()))){ echo 'active';} ?>"><a href="javascript:void(0);">
                                            <img src="<?php echo Mage::getBaseUrl('media').'wizard/claritydetail/'.$value.'.png';?>">
                                            </a><span><?php echo $value;?></span>
                                        </li>

                                    <?php
                                } ?>
                            </ul>
                        </div>
                    </div>
                    <div class="item diamond-item diamond-cut-item ideal-item">
                        <div class="content">
                            <h3><?php echo $helper->getAttributeValue('stone_cut',$product->getStoneCut());?> <?php echo $this->__('Cut');?><div class="tooltip-options">
                                    <div class="tooltip-image">
                                        <img src="<?php echo $this->getSkinUrl('css/images/tootlp-icon.png'); ?>" alt="">
                                    </div>
                                    <div class="tooltip-content">
                                        <a class="close-btn" href="javascript:void(0);"><img src="<?php echo $this->getSkinUrl('css/images/close-icon2.png');?>" alt=""></a>
                                        <p><?php echo $helper->getTooltip($attribute['STONE_CUT'],$titleHelper);?></p>
                                    </div>
                                </div></h3>
								<p><?php echo $this->__("Cut influences the diamond's sparkle.");?></p>
                        </div>
                        <div class="item-option">
                            <ul>
                                <?php foreach ($helper->getChangeAttrribute('stone_cut') as $value) {
                                    $hoverimg = Mage::getBaseUrl('media').'wizard/dimond-details-cut/'.strtolower(str_replace(" ", '_', $value)).'-h.png';
                                    $img = Mage::getBaseUrl('media').'wizard/dimond-details-cut/'.strtolower(str_replace(" ", '_', $value)).'.png';
                                    ?>
                                        <li class="<?php if(strtolower($value) == strtolower($helper->getAttributeValue('stone_cut',$product->getStoneCut()))){ echo 'active';} ?>"><a href="javascript:void(0);">
                                            <img class="active-img" src="<?php echo $hoverimg;?>">
                                            <img class="origanl-img" src="<?php echo $img;?>">

                                            </a><span><?php echo $value;?></span>
                                        </li>

                                    <?php
                                } ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>

<script type="text/javascript">
    jQuery('body').on("click",".sidestone .btn",function(e){
        var id = jQuery(this).attr('id');
        e.preventDefault(); // cancel click
        var page = jQuery(this).attr('href');
        window.location = page+'?id='+id;
        //jQuery('body').load(page+'?id='+id);
    });

    var detailsSidebarSticky = jQuery('.wizard-sidedetail-index .page-header').offset().top;
    jQuery(window).scroll(function (){
        jQuery('.col-right-side').removeClass('sidebar-fixed');
        if (jQuery(window).scrollTop() >= detailsSidebarSticky) {
           jQuery('.col-right-side').addClass('sidebar-fixed');
        }
        else {
           jQuery('.col-right-side').removeClass('sidebar-fixed');
        }
    });
     jQuery(window).load(function(){
          if(jQuery('video').length > 0){
            jQuery('.slick-video video').trigger('play');
          }
          jQuery('.viewcomplete-image').on('afterChange', function(event, slick, currentSlide, nextSlide){
              jQuery('.slick-video video').trigger('pause');
              jQuery('.btnPlay').addClass('pause');
              if(jQuery('.viewcomplete-image').find('.slick-current').find('video').length > 0){
                setTimeout(function () {
                    jQuery('.slick-video video').trigger('play');
                },200);
              }
          });
      });
      VideoControls();

</script>
<style type="text/css">
.sidestone .selected {
    color: blue;
}
</style>