<?php
$editid = $this->getRequest()->getParam('editid');
$resource = Mage::getSingleton('core/resource');
$readConnection = $resource->getConnection('core_read');
$promisedata = Mage::getSingleton('core/session')->getPromiseRing();


$diaPid = $promisedata['did'];
$promiseId = $promisedata['promise'];
$chainPid = $promisedata['chain'];

$helper = Mage::Helper('wizard');
$titleHelper =  $helper->getAlltitle();
//$helper->getRedirect($diaPid,'wizard');


$ringProduct = Mage::getModel('catalog/product')->load($promiseId);



$ringProduct->load('media_gallery');
$gallery = $ringProduct->getMediaGallery();
$price = ($ringProduct->getSpecialPrice() && $ringProduct->getSpecialPrice() < $ringProduct->getPrice())?$ringProduct->getSpecialPrice():$ringProduct->getPrice();


$diamondProduct = Mage::getModel('catalog/product')->load($diaPid);
$diamondProduct->load('media_gallery');
$diagallery = $diamondProduct->getMediaGallery();

$price += ($diamondProduct->getSpecialPrice() && $diamondProduct->getSpecialPrice() < $diamondProduct->getPrice())?$diamondProduct->getSpecialPrice():$diamondProduct->getPrice();
if($chainPid){
$chainPrice = $readConnection->fetchOne("select price from wizardmaster where pid=".$chainPid);
    $price += $chainPrice;
}



$ringData =  Mage::getSingleton('core/session')->getRingData();
if(empty($ringData)){
    $ringsize = $helper->getAttributeValue('product_size',$ringProduct->getProductSize());
    $ringData[$promiseId]['size'] = $ringsize;
    Mage::getSingleton('core/session')->setRingData($ringData);
}
$productSizeId = $helper->getAttributeId('product_size');
$shapeId = $helper->getAttributeId('stone_shape');
$metalTypeId = $helper->getAttributeId('metal_type');

/*
$stepList = $helper->stepList(2,2,false);
if(count($stepList) > 3){
    $stepList = $helper->stepList(3,3,false);
}*/

if($ringProduct->getId()){
    $checkMetalOption = Mage::getModel('wizard/wizardrelation')->checkMetalOption($ringProduct);
}


if(isset($_COOKIE['developer']) && $_COOKIE['developer'] == 1) {
    echo 'ring-'.$ringProduct->getId();
    echo "<br>";
    echo 'diamond-'.$diamondProduct->getId();
    echo "<br>";
}

$params = array('sid'=>$promiseId,'did'=>$diaPid,'chain'=>$chainPid,'promise'=>1);

$checkoutText = $this->__('Checkout');
if($editid){
    $params['editid'] = $editid;
    $checkoutText = $this->__('Checkout');
}
$sidestone =  Mage::getSingleton('core/session')->getSidestone();

/*  code for order date */
$receiveDay =  $helper->getOrderDate($promiseId);
$rcdate = date('y-m-d',strtotime($receiveDay));
$rcdate = date_format(date_create($rcdate),"dS F, Y");
/* end code for order date */


$metalColor = $helper->getAttributeValue('metal_color',$ringProduct->getMetalColor());
$metalKarat = $helper->getAttributeValue('karat',$ringProduct->getKarat());
$stepList = $helper->promisestepList(2,2,false);
$ringProduct->setVideo(Mage::getUrl().'media/video/Faaya-proposal-3-steps-final-video-FINAL-DESKTOP-4.mp4');
?>

<section class="main-content view-page">
    <div class="tabs">
            <ul>
                    <?php foreach ($stepList as $value) { ?>
                    <li class="<?php echo $value['class'];?>">
                        <a href="<?php echo Mage::app()->getStore()->getUrl($value['url'])?>">
                            <span class="tab-info">
                                <span class="title"><?php echo $value['title'];?></span>
                                    <?php if($value['text'] != ''){
                                    echo $value['text'];
                                    }?>
                            </span>
                        </a>
                      </li>
                    <?php } ?>
            </ul>
        </div>
    <div class="col-right-side">
        <div class="view-completed-slider col-sm-6">
            <div class="view-completed-slider-product">
            <div class="view-completed-slider-links links">
                <a class="link wish-it" href="#"><span><?php echo $this->__('');?></span></a>
            </div>
            <div class="sharethis-product">
                <div class="sharethis-inline-share-buttons"></div>
                <script type='text/javascript' src='//platform-api.sharethis.com/js/sharethis.js#property=5a423282c4203c00110b8eca&product=unknown' async='async'></script>
            </div>
            <div class="viewcomplete-image viewcomplete-image-ring">
                <?php if(count($gallery['images']) > 0 || Mage::helper('wizard')->checkRemoteFile($ringProduct->getVideo())){ ?>

                    <?php if(Mage::helper('wizard')->checkRemoteFile($ringProduct->getVideo())){ ?>
                    <div class="item">
                        <a class="icon-zoom video-zoom-icon" href="<?php echo $ringProduct->getVideo();?>" data-fancybox="wizard-slider"></a>
                        <div class="slick-video slick-video-2 video-wrapper video-box">
                            <video loop>
                                <source src="<?php echo $ringProduct->getVideo();?>" type=video/mp4>
                            </video>
                            <div class="control">
                                  <a href="javascript:void(0);" class="btnPlay pause"><i class="icon-play-pause" aria-hidden="true"></i></a>
                                  <a href="javascript:void(0);" class="muted" ><i class="icon-volume" aria-hidden="true"></i></a>
                              </div>
                        </div>
                    </div>
                    <?php } ?>
                     <?php foreach ($gallery['images'] as $item) {

                        $imageUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'catalog/product' . $item['file'];
                        ?>
                        <div class="item">
                            <a class="icon-zoom" href="<?php echo $imageUrl ?>" data-fancybox="wizard-slider">
                                <img src="<?php echo Mage::helper('catalog/image')->init($ringProduct, 'thumbnail', $item[' file'])->backgroundColor(255,255,255)->resize(600); ?>" alt="" />
                            </a>
                        </div>
                    <?php } ?>

                <?php }else{ ?>
                    <div class="item">
                        <a class="icon-zoom" href="<?php echo Mage::getSingleton('catalog/product_media_config')->getBaseMediaUrl(). '/placeholder/' .Mage::getStoreConfig("catalog/placeholder/small_image_placeholder"); ?>" data-fancybox="wizard-slider">
                            <img src="<?php echo Mage::getSingleton('catalog/product_media_config')->getBaseMediaUrl(). '/placeholder/' .Mage::getStoreConfig("catalog/placeholder/small_image_placeholder"); ?>" alt="" />
                        </a>
                    </div>
                <?php } ?>
            </div>
            <div class="viewcomplete-thumb viewcomplete-thumb-ring">
                  <?php if(Mage::helper('wizard')->checkRemoteFile($ringProduct->getVideo())){ ?>
                    <div class="item"><img src="<?php echo $this->getSkinUrl('css/images/video-icons.png'); ?>" alt="" /></div>
                <?php } ?>
                <?php foreach ($gallery['images'] as $item) { ?>
                    <div class="item">
                        <img src="<?php echo Mage::helper('catalog/image')->init($ringProduct, 'thumbnail', $item['file'])->backgroundColor(255,255,255)->resize(90); ?>" alt="" />
                    </div>
                <?php } ?>

            </div>
        </div>
        </div>

        <div class="view-completed-slider col-sm-6">
            <div class="view-completed-slider-product">
            <div class="view-completed-slider-links links">
                <a class="link wish-it" href="#"><span><?php echo $this->__('');?></span></a>
            </div>
            <div class="sharethis-product">
                <div class="sharethis-inline-share-buttons"></div>
                <script type='text/javascript' src='//platform-api.sharethis.com/js/sharethis.js#property=5a423282c4203c00110b8eca&product=unknown' async='async'></script>
            </div>
            <div class="viewcomplete-image viewcomplete-image-dimond">
                <?php if(count($diagallery['images']) > 0 || Mage::helper('wizard')->checkRemoteFile($diamondProduct->getVideo())){ ?>
                  <?php if(Mage::helper('wizard')->checkRemoteFile($diamondProduct->getVideo())){ ?>
                    <div class="item">
                        <a class="icon-zoom video-zoom-icon" href="<?php echo $diamondProduct->getVideo();?>" data-fancybox="wizard-slider"></a>
                        <div class="slick-video slick-video-2 video-wrapper video-box">
                            <video loop>
                                <source src="<?php echo $diamondProduct->getVideo();?>" type=video/mp4>
                            </video>
                            <div class="control">
                                  <a href="javascript:void(0);" class="btnPlay pause"><i class="icon-play-pause" aria-hidden="true"></i></a>
                                  <a href="javascript:void(0);" class="muted" ><i class="icon-volume" aria-hidden="true"></i></a>
                              </div>
                        </div>
                    </div>
                    <?php } ?>

                     <?php foreach ($diagallery['images'] as $item) {
                         $imageUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'catalog/product' . $item['file'];

                        ?>
                        <div class="item">
                            <a class="icon-zoom" href="<?php echo $imageUrl ?>">
                                <img src="<?php echo Mage::helper('catalog/image')->init($diamondProduct, 'thumbnail', $item['file'])->backgroundColor(255,255,255)->resize(600); ?>" alt="" />
                             </a>
                        </div>
                    <?php } ?>


                <?php }else{ ?>
                    <div class="item">
                         <a class="icon-zoom" href="<?php echo Mage::getSingleton('catalog/product_media_config')->getBaseMediaUrl(). '/placeholder/' .Mage::getStoreConfig("catalog/placeholder/small_image_placeholder"); ?>">
                            <img src="<?php echo Mage::getSingleton('catalog/product_media_config')->getBaseMediaUrl(). '/placeholder/' .Mage::getStoreConfig("catalog/placeholder/small_image_placeholder"); ?>" alt="" />
                        </a>
                    </div>
                <?php } ?>
            </div>
            <div class="viewcomplete-thumb viewcomplete-thumb-dimond">
                 <?php if(Mage::helper('wizard')->checkRemoteFile($diamondProduct->getVideo())){ ?>
                    <div class="item"><img src="<?php echo $this->getSkinUrl('css/images/video-icons.png'); ?>" alt="" /></div>
                <?php } ?>
                <?php foreach ($diagallery['images'] as $item) { ?>
                    <div class="item">
                        <img src="<?php echo Mage::helper('catalog/image')->init($diamondProduct, 'thumbnail', $item['file'])->backgroundColor(255,255,255)->resize(90); ?>" alt="" />
                    </div>
                <?php } ?>

            </div>
            </div>
        </div>
    </div>
    <div class="col-left-side completed-left-side">
        <div class="mobile-btn">
            <a class="link proceed button" href="<?php echo Mage::getUrl('wizard/index/addtocart',$params)?>"><span><?php echo $this->__('Proceed');?></span></a>
             <a class="link next-links proceed btn button" href="<?php echo Mage::getUrl('wizard/index/addtocart', $params) ?>"><span><?php echo $checkoutText;?></span></a>
        </div>
        <div class="details-blocks">
            <div class="blocks-navs col-sm-6 pull-right hidden-xs">
                <a class="link next-links proceed btn" href="<?php echo Mage::getUrl('wizard/index/addtocart', $params) ?>"><span><?php echo $checkoutText;?></span></a>
            </div>
            <div class="title desktop product-title-price">
                <h1><?php echo $ringProduct->getVariantRemark();?></h1>
                <div class="price-box">
                    <span class="price"><?php echo Mage::helper('core')->currency($price, true, false);?></span>
                </div>
                <div class="sub-title"><?php echo $ringProduct->getDescription();?></div>
            </div>
            <div class="delivery-date">
                <span class="date"><?php echo $this->__('Order now for dispatch by');?> <strong><?php echo $rcdate;?></strong></span>
            </div>
            <div class="details-content-section">
                <div class="row">
                    <div class="col-sm-12 col-md-6 left">
                        <h3><?php echo $this->__('Summary');?> - <span><?php echo $this->__('Diamond');?></span></h3>
                        <div class="details-tbl">
                            <ul>
                                <?php foreach ($this->getAttributeArry('left') as $item) { ?>
                                    <li>
                                        <span class="title"><?php echo $helper->getAttrTitle($item,$titleHelper);?>
                                            <?php if($helper->getTooltip($item,$titleHelper)){ ?>
                                            <div class="tooltip-options">
                                                <div class="tooltip-image">
                                                    <img src="<?php echo $this->getSkinUrl('css/images/info-icon.png') ?>" alt="">
                                                </div>
                                                <div class="tooltip-content">
                                                    <a class="close-btn" href="javascript:void(0);"><img src="<?php echo $this->getSkinUrl('css/images/close-icon2.png'); ?>" alt=""></a>
                                                    <?php echo $helper->getTooltip($item,$titleHelper);?>
                                                </div>
                                            </div>
                                            <?php } ?>
                                        </span>
                                        <span class="value">
                                            <?php
                                            if($item['oid']){
                                                echo $helper->getAttributeValue($item['code'],$diamondProduct->getData($item['code']));
                                            }elseif($diamondProduct->getData($item['code']) != ''){
                                                if($item['number_format']){
                                                    echo number_format($diamondProduct->getData($item['code']),2);
                                                }else{
                                                    if($item['code'] == 'certificate_no' && Mage::helper('wizard')->checkRemoteFile($diamondProduct->getCertificatePdf())){ ?>

                                                        <a class="diamond-pdf" href="<?php echo $diamondProduct->getCertificatePdf();?>" target="_blank" ><span><?php echo $diamondProduct->getData($item['code']);?></span></a>

                                                    <?php
                                                    }else{
                                                        echo $diamondProduct->getData($item['code']);
                                                    }
                                                }
                                            }else{
                                                echo "N/A";
                                            }
                                            ?>
                                        </span>
                                    </li>
                                <?php } ?>
                            </ul>
                            <ul>
                                <?php foreach ($this->getAttributeArry('right') as $item) { ?>
                                    <li>
                                        <span class="title"><?php echo $helper->getAttrTitle($item,$titleHelper);?>
                                            <?php if($helper->getTooltip($item,$titleHelper)){ ?>
                                            <div class="tooltip-options">
                                                <div class="tooltip-image">
                                                    <img src="<?php echo $this->getSkinUrl('css/images/info-icon.png') ?>" alt="">
                                                </div>
                                                <div class="tooltip-content">
                                                    <a class="close-btn" href="javascript:void(0);"><img src="<?php echo $this->getSkinUrl('css/images/close-icon2.png'); ?>" alt=""></a>
                                                    <?php echo $helper->getTooltip($item,$titleHelper);?>
                                                </div>
                                            </div>
                                            <?php } ?>
                                        </span>
                                        <span class="value">
                                            <?php
                                            if($item['oid']){
                                                echo $helper->getAttributeValue($item['code'],$diamondProduct->getData($item['code']));
                                            }elseif($diamondProduct->getData($item['code']) != ''){
                                                echo $diamondProduct->getData($item['code']);
                                            }else{
                                                echo "N/A";
                                            }
                                            ?>
                                        </span>
                                    </li>
                                <?php } ?>
                            </ul>
                        </div>
                        <h3><?php echo $this->__('Summary');?> - <span><?php echo $ringProduct->getDescription();?></span></h3>
                        <div class="preset-options metal-options wizard-preset-options">
                            <h3><?php echo $this->__('Color');?></h3>
                            <ul class="options">
                                <li><img src="<?php echo Mage::getBaseUrl('media').'wizard/metalcolor/'.strtolower(str_replace(' ', '_', $metalColor)).'_'.$metalKarat.'.png';?>"><span class="palettext">PLATED</span></li>
                            </ul>
                         </div>
                    </div>
                    <div class="col-sm-12 col-md-6 right">
                        <div class="ring-size-block ring-size-radio-block clickable">
                            <h3><?php echo $this->__('Ring Size');?></h3>
                            <?php $availableSizes = Mage::getModel('wizard/wizardrelation')->getAvailbleSizes($ringProduct,false);?>
                            <div class="ring-size-block-select">
                                <span class="selected-value"><span>6.0</span></span>
                                <ul class="ring-size-radio size-dropdown">
                                    <?php foreach ($availableSizes as $key=>$value) { ?>
                                        <?php $cls = ($ringData[$promiseId]['size'] == $value)?'checked="checked"':'';?>
                                        <li>
                                            <input type="radio" <?php echo $cls;?> class="radio" id="size_<?php echo number_format($value,1);?>" name="availblesize" value="<?php echo number_format($value,1);?>">
                                            <label for="<?php echo number_format($value,1);?>"><?php echo number_format($value,1);?></label>
                                    <?php } ?>
                                </ul>
                            </div>
                            <a target="_blank" class="size-guide" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."wizard/sizeguide/sizeguide.pdf";?>"><?php echo $this->__('Size Guide');?></a>
                        </div>
                        <?php if($weddingband['pinfo']){ ?>
                            <?php $weddinginfo = unserialize($weddingband['pinfo']);$weddinginfo= $weddinginfo[0];?>
                        <div class="wedding-band-block">
                            <input type="hidden" name="weddingid" id="weddingid" value="<?php echo $weddingband['pid'];?>">
                            <button class="button"><?php echo $this->__('add wedding band'); ?></button>
                            <div class="wedding-block-content">
                                <h3><?php echo $weddingband['variant_remark']; ?> <span class="price"><?php echo Mage::helper('core')->currency($weddingband['price'], true, false);?></span></h3>
                                <p><?php echo $weddingband['variant_name']; ?></p>
                                <div class="details-tbl">
                                    <ul>
                                        <li>
                                            <span class="title"><?php echo $this->__('Minimum number of round diamonds'); ?>
                                                <div class="tooltip-options">
                                                <div class="tooltip-image">
                                                    <img src="<?php echo $this->getSkinUrl('css/images/info-icon.png'); ?>" alt="">
                                                </div>
                                                <div class="tooltip-content">
                                                    <a class="close-btn" href="javascript:void(0)"><img src="<?php echo $this->getSkinUrl('css/images/close-icon2.png'); ?>" alt=""></a>
                                                    <h3><?php echo $this->__('Metal Type'); ?></h3>
                                                    <img src="<?php echo Mage::getBaseUrl('media');?>/wizard/tooltip-img1.png" alt="Metal Type"><p><?php echo $this->__('Metal type tooltip'); ?></p></div></div>
                                            </span>
                                            <span class="value"><?php echo $weddinginfo['PIECES']; ?></span>
                                        </li>
                                        <li>
                                            <span class="title"><?php echo $this->__('Minimum carat total weight (CT. TW.)'); ?>
                                                <div class="tooltip-options">
                                                <div class="tooltip-image">
                                                    <img src="<?php echo $this->getSkinUrl('css/images/info-icon.png'); ?>" alt="">
                                                </div>
                                                <div class="tooltip-content">
                                                    <a class="close-btn" href="javascript:void(0)"><img src="<?php echo $this->getSkinUrl('css/images/close-icon2.png'); ?>" alt=""></a>
                                                    <h3><?php echo $this->__('Metal Type'); ?></h3>
                                                    <img src="<?php echo Mage::getBaseUrl('media');?>/wizard/tooltip-img1.png" alt="Metal Type"><p><?php echo $this->__('Metal type tooltip'); ?></p></div></div>
                                            </span>
                                            <span class="value"><?php echo $weddinginfo['WEIGHT']; ?></span>
                                        </li>
                                        <li>
                                            <span class="title"><?php echo $this->__('Average Colour'); ?>
                                                <div class="tooltip-options">
                                                <div class="tooltip-image">
                                                    <img src="<?php echo $this->getSkinUrl('css/images/info-icon.png'); ?>" alt="">
                                                </div>
                                                <div class="tooltip-content">
                                                    <a class="close-btn" href="javascript:void(0)"><img src="<?php echo $this->getSkinUrl('css/images/close-icon2.png'); ?>" alt=""></a>
                                                    <h3><?php echo $this->__('Metal Type'); ?></h3>
                                                    <img src="<?php echo Mage::getBaseUrl('media');?>/wizard/tooltip-img1.png" alt="Metal Type"><p><?php echo $this->__('Metal type tooltip'); ?></p></div></div>
                                            </span>
                                            <span class="value"><?php echo $weddinginfo['STONE_COLOR']; ?></span>
                                        </li>
                                        <li>
                                            <span class="title"><?php echo $this->__('Average Clarity'); ?>
                                                <div class="tooltip-options">
                                                <div class="tooltip-image">
                                                    <img src="<?php echo $this->getSkinUrl('css/images/info-icon.png'); ?>" alt="">
                                                </div>
                                                <div class="tooltip-content">
                                                    <a class="close-btn" href="javascript:void(0)"><img src="<?php echo $this->getSkinUrl('css/images/close-icon2.png'); ?>" alt=""></a>
                                                    <h3><?php echo $this->__('Metal Type'); ?></h3>
                                                    <img src="<?php echo Mage::getBaseUrl('media');?>/wizard/tooltip-img1.png" alt="Metal Type"><p><?php echo $this->__('Metal type tooltip'); ?></p></div></div>
                                            </span>
                                            <span class="value"><?php echo $weddinginfo['QUALITY']; ?></span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <?php } ?>
                    </div>

                </div>
            </div>
        </div>
        <div class="mobile-btn">
            <a class="link proceed button" href="<?php echo Mage::getUrl('wizard/index/addtocart', array('sid'=>$promiseId,'did'=>$diaPid)) ?>"><span><?php echo $this->__('Proceed');?></span></a>
        </div>
    </div>

</section>
<script type="text/javascript">
    var BASE_URL='<?php echo preg_replace('/(.*?)(index.php\/?)?/','\1',Mage::getBaseURL());?>';
    var productId='<?php echo $ringProduct->getId();?>';
    jQuery(document).ready(function(){
        jQuery('.clickable ul li input').click(function(){
            var metalOption = false;
            var dataindex = false;
            var dataid = jQuery(this).data('id');
            setData(jQuery(this).attr('id'),metalOption,dataindex,dataid);
            //jQuery('.slick-video video').trigger('play');
        })

       /* jQuery(window).on('load',function () {
          jQuery('.slick-video video').trigger('play');
        });*/


        //var btnName = jQuery('.wedding-band-block > .button').text('add wedding band');
        jQuery('.wedding-band-block .button').click(function (){
            var $this = jQuery(this);
            jQuery(this).toggleClass('remove');
            jQuery('.wedding-block-content').slideToggle();
            var wed = jQuery('#weddingid').val();
            wed = 'wedding/'+wed;
            if($this.hasClass('remove')){
                $this.text('remove wedding band');
                var existurl = jQuery('.next-links').attr('href');
                existurl = existurl+wed;
                jQuery('.next-links').attr('href',existurl);
            } else {
                var existurl = jQuery('.next-links').attr('href');
                $this.text('add wedding band');
                existurl = existurl.replace(wed, "");
                jQuery('.next-links').attr('href',existurl);
            }

        })

    })

    var detailsSidebarSticky = jQuery('.wizard-completedset-index .page-header').offset().top;
    jQuery(window).scroll(function (){
        jQuery('.col-right-side').removeClass('sidebar-fixed');
        if (jQuery(window).scrollTop() >= detailsSidebarSticky) {
           jQuery('.col-right-side').addClass('sidebar-fixed');
        }
        else {
           jQuery('.col-right-side').removeClass('sidebar-fixed');
        }
    });

    function setData(id,metalOption,dataindex,dataid){
        jQuery.ajax({
            url: BASE_URL+"wizard/index/setringdata",
            type: "POST",
            data: {id:id,pid:productId,metaloption:metalOption},
            success: function(redata){
                if(metalOption){
                    location.reload();
                }else{
                    jQuery('.cls'+dataid).find('li').removeClass('selected');
                    jQuery('.cls'+dataid).find('li').eq(dataindex).addClass('selected');
                }
            },error: function(xhr){
                if(metalOption){
                    location.reload();
                }else{
                    jQuery('.cls'+dataid).find('li').removeClass('selected');
                    jQuery('.cls'+dataid).find('li').eq(dataindex).addClass('selected');
                }
            }
        })
    }

    jQuery(window).load(function(){
          if(jQuery('video').length > 0){
            jQuery('.slick-video video').trigger('play');
          }
          jQuery('.viewcomplete-image').on('afterChange', function(event, slick, currentSlide, nextSlide){
              jQuery('.slick-video video').trigger('pause');
              jQuery('.btnPlay').addClass('pause');
              if(jQuery('.viewcomplete-image').find('.slick-current').find('video').length > 0){
                setTimeout(function () {
                    //jQuery('.slick-video video').trigger('play');
                     jQuery('.slick-video video')[0].play();
                },200);
              }
          });
          VideoControls();
      });


</script>
