<?php /** MageWorkshop_CommentOnReview_Block_Adminhtml_Notification_Message $this */?>

<?php
$commentOnReviewUrl = $this->getCommentOnReviewAdminUrl();

/** @var MageWorkshop_Core_Helper_Data $mageWorkshopCoreHelper */
$mageWorkshopCoreHelper = Mage::helper('drcore');

$reCaptchaPingResult  = $mageWorkshopCoreHelper->pingMageWorkshopReCaptcha(
    Mage::getStoreConfig(MageWorkshop_CommentOnReview_Helper_Data::COMMENT_XML_PATH_CAPTCHA_PRIVATE_KEY)
);
?>

<?php if (Mage::getStoreConfig(MageWorkshop_CommentOnReview_Helper_Data::COMMENT_XML_PATH_CAPTCHA_ENABLED) && !$reCaptchaPingResult): ?>
    <div class="notification-global">
        <?php
        echo $this->__(
            '<strong class="label">MageWorkshop CommentOnReview: </strong><strong>Please check ReCaptcha "Private Key" configuration in "Captcha Options" </strong><a href="%s">go to MageWorkshop CommentOnReview configuration</a>',
            $commentOnReviewUrl
        );
        ?>
    </div>
<?php endif; ?>