<?php /** @var MageWorkshop_ReviewWall_Block_Widget_Part_SocialShare_Facebook $this */ ?>
<?php $facebookPingResult = Mage::helper('drcore')->pingDetailedReviewFacebook();?>
<?php if($facebookPingResult !== false && !isset($facebookPingResult['error'])): ?>
    <?php
    $review = $this->getReview();
    $shareUrl = $this->getShareUrl();
    $product = $review->getProduct();
    //TODO use not load
    $reviewImage = $review->getImage();
    $image = (!empty($reviewImage)) ? Mage::getBaseUrl('media') . $reviewImage : Mage::getModel('catalog/product')->load($product->getId())->getImageUrl();

    $commentFBDetail[$review->getId()] = array(
        'name'=> $product->getName(),
        'url'=> $shareUrl,
        'detail' => $review->getDetail(),
        'image' => $image
    );
    ?>

    <?php if ($review && $shareUrl ): ?>
        <div class="drw-share-fb" onclick="fbShare(<?php echo $review->getId();?>)"></div>

        <?php
        $commentFBDetail['success'] = $this->__('Post was published.');
        $commentFBDetail['error'] = $this->__('Post was not published.');
        ?>
        <script type="text/javascript">
            var fbShareComment<?php echo $review->getId(); ?> = <?php echo json_encode($commentFBDetail); ?>;
        </script>


    <?php endif; ?>
<?php endif; ?>
