<?php if (Mage::getStoreConfig('detailedreview/social_share_optios/twitt_review')): ?>
    <?php
        $review = $this->getReview();
        $shareUrl = $this->getShareUrl();
        $product = $review->getProduct();
        $helperDetailedreview = Mage::helper('detailedreview');
    ?>
    <?php if ($product && $shareUrl ): ?>
        <div class="drw-share-twitter">
            <a href="<?php echo $this->escapeHtml('https://twitter.com/share?dtn=true&count=none&lang=en&via=DetailedReview&text=')?><?php echo urlencode($helperDetailedreview->smartyModifierTruncate($product->getName(), 30)); ?><?php echo $this->escapeHtml('&url=')?><?php echo urlencode($shareUrl); ?>"
               target="_blank"
               class="twitter-share-button"
               data-url="<?php echo $shareUrl; ?>"
               data-text="<?php echo urlencode($helperDetailedreview->smartyModifierTruncate($this->escapeHtml($product->getName()), 30)); ?>"
               data-via="DetailedReview"
               data-social-type="twitter"
               data-action="<?php echo Mage::getUrl('detailedreview/product/getShortLink', array('_secure' => Mage::app()->getStore()->isCurrentlySecure())); ?>">
            </a>
        </div>
    <?php endif; ?>
<?php endif; ?>
