<?php
$record_id = $this->getRecordId();
?>
<div class="abuse-action">
    <i class="complaint-icon" id="complaint-<?php echo $record_id ?>" style="background: url(<?php echo $this->getSkinUrl('images/detailedreview/ic_more.png'); ?>) no-repeat 1px 2px;"></i>
    <div class="report-button-wrapper complaint-<?php echo $record_id ?>">
        <span class="report-abuse"><?php echo Mage::helper('detailedreview')->__('Report spam or abuse')?></span>
    </div>
</div>
