<?php if(have_rows('promise_select_promise_repeater','option')):  ?>
<?php
$title =  get_field('promise_title','option');
$description =  get_field('promise_description','option');
?>

<?php
    function check_custom_proposallink($arglink)
    {
        $httpPost = strpos($arglink,'http');
        if(strlen($arglink)==0)
        {
            $link = 'javascript:;';
        }
        elseif(strlen($httpPost)==0)
        {
           $link = Mage::getBaseUrl().$arglink;
        }
        else
        {
           $link = $arglink;
        }
        return $link;
    }
?>
<div class="select-promise-ring">
    <div class="description">
        <h2><?php echo $title;?></h2>
        <p><?php echo $description;?></p>
    </div>
    <div class="blocks">
       <?php  while(have_rows('promise_select_promise_repeater','option')): the_row(); ?>
             <?php
                  $proposeTitle = get_sub_field('promise_ring_title','option');
                  $proposeLink = get_sub_field('promise_ring_link','option');
                  $proposeImage = get_sub_field('promise_ring_image','option');
                  $image = Mage::helper('latestblogpost')->getResizedHomeNewsImage($proposeImage['url'], 450, 465,"proposal-select-promising");
                  $cLink = "javascript:void(0);";?>
                  <?php
                    if($proposeLink):
                       $cLink = check_custom_proposallink($proposeLink);
                    endif;
             ?>
            <div class="block">
                <div class="image"><img src="<?php echo $image; ?>" alt="" /></div>
                <h3><a href="<?php echo $cLink;?>"><?php echo $proposeTitle;?></a></h3>
            </div>
        <?php endwhile; ?>
    </div>
</div>

<?php endif;  ?>


