<script type="text/javascript">
    (function ($) {
        $(document).ready(function() {
            var $containerClass = $('.drw-container'),
                $containerId = $('#drw-container');
            var $grid = $containerClass.masonry({
                itemSelector: '.drw-grid-item',
                columnWidth: '.drw-grid-sizer',
                gutter: '.drw-gutter-sizer'
            });

            $grid.imagesLoaded().progress( function() {
                $grid.masonry('layout');
            });

            $containerId.reviewWall({
                template: "<?php echo $this->getChildHtml('template', false); ?>",
                filter: "<?php echo $this->getFilter(); ?>",
                cssClassName: "<?php echo Mage::helper('reviewwall')->getCssClassName() ?>",
                baseUrl: "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, Mage::app()->getStore()->isCurrentlySecure()); ?>",
                baseUrlMedia: "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA, Mage::app()->getStore()->isCurrentlySecure()); ?>",
                endReviewMessage: "<?php echo $this->__('All reviews were loaded'); ?>",
                unknownSearchCriteriaMessage: "<?php echo $this->__('Sorry, no reviews matched your criteria.') ?>"
            });

            $containerId.reviewShare({
                customerName: "<?php echo Mage::getSingleton('customer/session')->isLoggedIn() ? Mage::getSingleton('customer/session')->getCustomer()->getName() : $this->__('Guest'); ?>",
                customerEmail: "<?php echo Mage::getSingleton('customer/session')->isLoggedIn() ? Mage::getSingleton('customer/session')->getCustomer()->getEmail() : null; ?>",
                shareReviewByEmailUrl: "<?php echo Mage::getUrl('mageworkshop_reviewwall/ajax/shareEmail', array('_secure' => Mage::app()->getStore()->isCurrentlySecure())); ?>",
                defaultFailMessage: "<?php echo $this->__('Something went wrong.'); ?>",
                currentRecipientCount: 1,
                recipientMaxCount: "<?php echo Mage::helper('sendfriend')->getMaxRecipients(); ?>",
                maxRecipientMessage: "<?php echo $this->__('Maximum %s email addresses allowed.', Mage::helper('sendfriend')->getMaxRecipients()); ?>"
            });

            $('#drw-review-search-mini-form').submit(function (e) {
                e.preventDefault();

                $containerId.reviewWall('searchEvent');
            });

            $(document).on("click", '.drw-review-vote-rating', function (event) {
                $containerId.reviewWall('voteEvent', this);
            });
        });
    }(DRjQuery));
</script>
