<?php if(have_rows('homepartner_propose_reapeter','option')):  ?> 
<?php 
$title =  get_field('homepartner_propose_title','option');
$description =  get_field('homepartner_propose_description','option');
?>
<section class="propose-category-section">   
        <div class="description">
            <h2><?php echo $title;?></h2>
            <p><?php echo $description;?></p>
        </div>
        <div class="content">
            <ul class="grid">
                <?php  while(have_rows('homepartner_propose_reapeter','option')): the_row(); ?>
                 <?php
                      $proposeTitle = get_sub_field('partner_propose_title','option');
                      $proposeDescription = get_sub_field('partner_propose_description','option');  
                      $proposeLable = get_sub_field('partner_propose_label','option');
                      $proposeLink = get_sub_field('partner_propose_link','option');
                      $proposeImage = get_sub_field('partner_propose_image','option');
                      //$image = Mage::helper('latestblogpost')->getResizedHomeNewsImage($proposeImage['url'], 428, 387,"homepartner-proposal");
					           $image = $proposeImage['url'];
                      $cLink = "javascript:void(0);";?>
                      <?php
                        if($proposeLink):
                           $cLink = check_custom_proposelink($proposeLink);
                        endif;
                 ?>
                <li class="item">
                    <div class="details">
                        <h3><?php echo $proposeTitle;?></h3>
                        <p><?php echo $proposeDescription;?></p>
                        <a class="readmore" href="<?php echo $cLink;?>" title="<?php echo $proposeLable;?>"><?php echo $proposeLable;?></a>
                    </div>
                    <div class="image"><img src="<?php echo $image ?>" alt="<?php echo $proposeLable;?>" /></div>
                </li>
               <?php endwhile; ?>                 
            </ul>
        </div>
</section>
<?php endif;?>
<?php
    function check_custom_proposelink($arglink)
    {
        $httpPost = strpos($arglink,'http');
        if(strlen($arglink)==0)
        {
            $link = 'javascript:;';
        }
        elseif(strlen($httpPost)==0)
        {
           $link = 'http://'.$arglink;
        }
        else
        {
           $link = $arglink;
        }
        return $link;
    }
?>


