<?php
/**
 * @var $this Cminds_Multiwishlist_Block_Customer_Multiwishlist_List
 */
$wishlists = $this->getItems();
?>

<div class="dashboard">
    <div class="page-title">
        <h1><?php echo $this->__('List of your Wishlist') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('pager'); ?>
    <?php if (count($wishlists)): ?>
        <table class="data-table" id="list-multiwishlist-table">
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <thead>
            <tr>
                <th><?php echo $this->__('Name') ?></th>
                <th><?php echo $this->__('Items') ?></th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <?php $_odd = ''; ?>
            <?php foreach ($wishlists as $wishlist): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($wishlist->getName()) ?></td>
                    <td><?php echo $this->escapeHtml($wishlist->getItemsCount()) ?></td>
                    <td><a href="<?php echo $this->escapeHtml($this->getViewUrl($wishlist->getId())); ?>"><?php echo $this->__('View') ?></a></td>
                    <td>
                        <a href="<?php echo $this->escapeHtml($this->getRemoveUrl($wishlist->getId()))?>"
                           onclick=" return confirm('Are you sure you want to remove this Wishlist?')"
                        >
                            <?php echo $this->__('Remove') ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('list-multiwishlist-table')</script>
    <?php else: ?>
        <p style="padding: 20px;"><?php echo $this->__('No Wishlist Found') ?></p>
    <?php endif; ?>
    <?php echo $this->getChildHtml('pager'); ?>
</div>
