<?php if ($_review = $this->getReview()): ?>
    <div class="drw-social-share <?php echo Mage::helper('reviewwall')->getCssClassName(); ?> social-share">
        <?php $_product = $_review->getProduct(); ?>
        <?php $shareFbUrl = Mage::getModel('core/url')->sessionUrlVar(urldecode($_product->getProductUrl() . '%23rw_' . $_review->getId())); ?>
        <?php $shareUrl = Mage::getModel('core/url')->sessionUrlVar($_product->getProductUrl() . '#rw_'.$_review->getId()); ?>

        <?php $this->getChild('facebook')->setData(array(
            'review' => $_review,
            'share_url' =>$shareFbUrl
        )); ?>
        <?php echo $this->getChildHtml('facebook', false); ?>


        <?php $this->getChild('twitter')->setData(array(
            'review' => $_review,
            'share_url' =>$shareUrl
        )); ?>
        <?php echo $this->getChildHtml('twitter', false); ?>

        <?php if ($_review->getImage()): ?>
            <?php $this->getChild('pinterest')->setData(array(
                'review' => $_review,
                'share_url' =>$shareUrl
            )); ?>
            <?php echo $this->getChildHtml('pinterest', false); ?>
        <?php endif; ?>

        <?php $this->getChild('email')->setData(array(
            'review' => $_review,
            'share_url' =>$shareUrl
        )); ?>
        <?php echo $this->getChildHtml('email', false); ?>
    </div>
<?php endif; ?>
