<?php
/** @var MageWorkshop_ReviewWall_Block_Widget_Part_TotalRating $this */

/** @var MageWorkshop_ReviewWall_Helper_Data $helper */
$helper = Mage::helper('reviewwall');
$averageRating = $helper->getAverageRatingByTotalReviews();
$totalReviews = $helper->getTotalReviewsCount();
$countOfStars = 5;
$numberForTransform = 20;
?>
<div class="drw-total-average-rating-wrapper">
    <div class="drw-total-rating">
        <div class="ratings-table">
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $averageRating; ?>%;"></div>
            </div>
        </div>
        <div>
            <?php echo $helper->__("Rated %s out of %s stars. Based on %s Reviews", round($averageRating/$numberForTransform, 1), $countOfStars, $totalReviews)?>
        </div>
    </div>
</div>
