<?php
$currentCategory = Mage::registry('current_category');
$categoryId = $currentCategory->getId();

$ringfilter = Mage::getBlockSingleton('layernavigation/layernavigation')->getRingfilter($categoryId);

$getDiamondFilterAttribute = Mage::getBlockSingleton('layernavigation/layernavigation')->getDiamondShapeFilter($categoryId);

$metalColor = $ringfilter['metal_color'];
$karat = $ringfilter['karat'];
asort($karat);
$karat = array_filter($karat);
$stoneShape = $getDiamondFilterAttribute;
$stoneShape = array();
$subCategory = $ringfilter['sub_category'];

$_caratCollection = Mage::getModel('catalog/product')->getCollection()
             ->joinField('category_id', 'catalog/category_product', 'category_id', 'product_id = entity_id', null, 'left')
             ->addAttributeToSelect('*')
             ->addAttributeToFilter('category_id',$categoryId)
             ->addAttributeToFilter('sub_category',array("neq"=>""))
             ->addAttributeToFilter('metal_color',array("neq"=>""));
?>
<?php
$changeAttributeName = array('metal color'=>'metal','karat'=>'metal karat','sub category'=>'style');
$ringAttribute = array('metal_color','karat','sub_category'); ?>
    <div class="block-content toggle-content">
        <div id="narrow-by-list">
        <div class="filter-options diamond_size">
          <div class="filter-label">
            <?php echo $this->__('Diamond Size');?>
          </div>
          <div class="list">
            <a class="selectAll" href="javascript:void(0)"><?php echo $this->__('Show all');?></a>
             <ol>
               <?php $i=1;foreach($ringfilter['total_dia_wt'] as $range => $size):?>
                    <li><input type="checkbox" name="diamond_size" data-optionval="<?php echo $size;?>" id="<?php echo "size-".$i;?>" value="<?php echo $size;?>" class="shopby-attr" data-attname="diamond_size" data-id="<?php echo "size-".$i;?>">
                    <label for="<?php echo "size-".$i;?>"><span><?php echo $range;?></span></label>
                    </li>
               <?php $i++; endforeach;?>
             </ol>
          </div>
        </div>
        <?php // Metal Color ?>
        <?php if(count($metalColor) > 0):?>
            <div class="filter-options metal">
              <div class="filter-label">
                <?php echo $this->__('Metal');?>
              </div>
              <div class="list">
                <a class="selectAll" href="javascript:void(0)"><?php echo $this->__('Show all');?></a>
                 <ol>
                   <?php foreach($metalColor as $metalId =>$metal):?>
                    <?php $imageName = strtolower(str_replace(' ',"_",$metal)).".png"; ?>
                    <?php $imagePath = Mage::getBaseUrl('media')."wizard". DS."category-listing" . DS .$imageName;?>
                        <li><input type="checkbox" name="metal" data-optionval="<?php echo $metal;?>" id="<?php echo $metalId;?>" value="<?php echo $metalId;?>" class="shopby-attr" data-attname="metal" data-id="<?php echo $metalId;?>">
                        <label for="<?php echo $metalId;?>"><span><?php echo ucfirst(strtolower($metal));?></span>
                        <img src="<?php echo $imagePath; ?>" alt="<?php echo $imageName;?>"/>
                        </label>


                        </li>
                   <?php endforeach;?>
                 </ol>
              </div>
            </div>
        <?php endif; ?>
        <?php // Karat ?>
        <?php if(count($karat) > 0):?>
            <div class="filter-options metal_karat">
              <div class="filter-label">
                <?php echo $this->__('Metal Karat');?>
              </div>
              <div class="list">
                <a class="selectAll" href="javascript:void(0)"><?php echo $this->__('Show all');?></a>
                 <ol>
                   <?php foreach($karat as $karatId =>$karatVal):?>
                        <li><input type="checkbox" name="metal_karat" data-optionval="<?php echo $karatVal;?>" id="<?php echo $karatId;?>" value="<?php echo $karatId;?>" class="shopby-attr" data-attname="metal_karat" data-id="<?php echo $karatId;?>">
                        <label for="<?php echo $karatId;?>"><span><?php echo ucfirst(strtolower($karatVal));?></span></label>
                        </li>
                   <?php endforeach;?>
                 </ol>
              </div>
            </div>
        <?php endif; ?>
        <?php // StoneShape ?>
        <?php if(count($stoneShape) > 0):?>
            <div class="filter-options shape">
              <div class="filter-label">
                <?php echo $this->__('Shape');?>
              </div>
              <div class="list">
                <a class="selectAll" href="javascript:void(0)"><?php echo $this->__('Show all');?></a>
                 <ol>
                   <?php foreach($stoneShape as $shape):?>
                        <li><input type="checkbox" name="shape" data-optionval="<?php echo $shape;?>" id="<?php echo $shape;?>" value="<?php echo $shape;?>" class="shopby-attr" data-attname="shape" data-id="<?php echo $shape;?>">
                        <label for="<?php echo $shape;?>"><span><?php echo ucfirst(strtolower($shape));?></span></label>
                        </li>
                   <?php endforeach;?>
                 </ol>
              </div>
            </div>
        <?php endif;  ?>
        <?php // Sub Category ?>
        <?php if(count($subCategory) > 0):?>
            <div class="filter-options style">
              <div class="filter-label">
                <?php echo $this->__('Style');?>
              </div>
              <div class="list">
                <a class="selectAll" href="javascript:void(0)"><?php echo $this->__('Show all');?></a>
                 <ol>
                   <?php foreach($subCategory as $styleId=>$style):?>
                        <li><input type="checkbox" name="style" data-optionval="<?php echo $style;?>" id="<?php echo $styleId;?>" value="<?php echo $styleId;?>" class="shopby-attr" data-attname="sub_category" data-id="<?php echo $styleId;?>">
                        <label for="<?php echo $styleId;?>"><span><?php echo ucfirst(strtolower($style));?></span></label>
                        </li>
                   <?php endforeach;?>
                 </ol>
              </div>
            </div>
        <?php endif; ?>

        <div class="filter-options sort-by">
          <div class="filter-label">
            <?php echo $this->__('Sort by');?>
          </div>
          <div class="list">
             <ol>
               <li><a href="javascript:void(0);" class="shopby-attr sort-by" data-sort="asc" data-order="price"><?php echo $this->__("Price(Ascending Direction)");?></a></li>
               <li><a href="javascript:void(0);" class="shopby-attr sort-by" data-sort="desc" data-order="price"><?php echo $this->__("Price(Descending Direction)");?></a></li>
               <li><a href="javascript:void(0);" class="shopby-attr sort-by" data-sort="asc" data-order="bestseller"><?php echo $this->__("Best Sellers");?></a></li>
             </ol>
          </div>
        </div>

        <div class="filter-options price_range_filter">
          <div class="filter-label">
            <?php echo $this->__('Price');?>
          </div>
          <div class="list">
            <input type="text" id="min-priceval" class="updateclass">
            <input type="text" id="max-priceval" class="updateclass">
          <div id="price_range_filter"></div>
          </div>
        </div>
    </div>
  </div>