<?php
$ringfilter = Mage::getBlockSingleton('layernavigation/layernavigation')->getCollectionfilter();
$metalColor = $ringfilter['metal_color'];
$karat = $ringfilter['karat'];
$collection = $ringfilter['collection'];
$productType = $ringfilter['product_type'];
asort($karat);
$karat = array_filter($karat);

$subCategory = $ringfilter['sub_category'];
$subCategory = array();

?>
<?php
$changeAttributeName = array('metal color'=>'metal','karat'=>'metal karat','sub category'=>'ring style');
$ringAttribute = array('metal_color','karat','sub_category'); ?>

    <div class="block-content toggle-content">
        <div id="narrow-by-list">
        <div class="filter-options diamond_size">
          <div class="filter-label">
            <?php echo $this->__('Diamond Size');?>
          </div>
          <div class="list">
            <a class="selectAll" href="javascript:void(0)"><?php echo $this->__('Show all');?></a>
             <ol>
               <?php $i=1;foreach($ringfilter['total_dia_wt'] as $range => $size):?>
                    <li><input type="checkbox" name="diamond_size" data-optionval="<?php echo $size;?>" id="<?php echo "size-".$i;?>" value="<?php echo $size;?>" class="shopby-attr" data-attname="diamond_size" data-id="<?php echo "size-".$i;?>">
                    <label for="<?php echo "size-".$i;?>"><span><?php echo $range;?></span></label>
                    </li>
               <?php $i++; endforeach;?>
             </ol>
          </div>
        </div>
        <?php // Metal Color ?>
        <?php if(count($metalColor) > 0):?>
            <div class="filter-options metal">
              <div class="filter-label">
                <?php echo $this->__('Metal');?>
              </div>
              <div class="list">
                <a class="selectAll" href="javascript:void(0)"><?php echo $this->__('Show all');?></a>
                 <ol>
                   <?php foreach($metalColor as $metalId =>$metal):?>
                    <?php $imageName = strtolower(str_replace(' ',"_",$metal)).".png"; ?>
                    <?php $imagePath = Mage::getBaseUrl('media')."wizard". DS."category-listing" . DS .$imageName;?>
                        <li><input type="checkbox" name="metal" data-optionval="<?php echo $metal;?>" id="<?php echo $metalId;?>" value="<?php echo $metalId;?>" class="shopby-attr" data-attname="metal" data-id="<?php echo $metalId;?>">
                        <label for="<?php echo $metalId;?>"><span><?php echo ucfirst(strtolower($metal));?></span>
                        <img src="<?php echo $imagePath; ?>" alt="<?php echo $imageName;?>"/>
                        </label>


                        </li>
                   <?php endforeach;?>
                 </ol>
              </div>
            </div>
        <?php endif; ?>
        <?php // Karat ?>
        <?php if(count($karat) > 0):?>
            <div class="filter-options metal_karat">
              <div class="filter-label">
                <?php echo $this->__('Metal Karat');?>
              </div>
              <div class="list">
                <a class="selectAll" href="javascript:void(0)"><?php echo $this->__('Show all');?></a>
                 <ol>
                   <?php foreach($karat as $karatId =>$karatVal):?>
                        <li><input type="checkbox" name="metal_karat" data-optionval="<?php echo $karatVal;?>" id="<?php echo $karatId;?>" value="<?php echo $karatId;?>" class="shopby-attr" data-attname="metal_karat" data-id="<?php echo $karatId;?>">
                        <label for="<?php echo $karatId;?>"><span><?php echo ucfirst(strtolower($karatVal));?></span></label>
                        </li>
                   <?php endforeach;?>
                 </ol>
              </div>
            </div>
        <?php endif; ?>
        <?php if(count($collection) > 0):?>
            <div class="filter-options collection">
              <div class="filter-label">
                <?php echo $this->__('Collection');?>
              </div>
              <div class="list">
                <a class="selectAll" href="javascript:void(0)"><?php echo $this->__('Show all');?></a>
                 <ol>
                   <?php foreach($collection as $colId =>$colVal):?>
                        <li><input type="checkbox" name="collection" data-optionval="<?php echo $colVal;?>" id="<?php echo $colId;?>" value="<?php echo $colId;?>" class="shopby-attr" data-attname="collection" data-id="<?php echo $colId;?>">
                        <label for="<?php echo $colId;?>"><span><?php echo ucfirst(strtolower($colVal));?></span></label>
                        </li>
                   <?php endforeach;?>
                 </ol>
              </div>
            </div>
        <?php endif; ?>
        <?php if(count($productType) > 0):?>
            <div class="filter-options jewelry">
              <div class="filter-label">
                <?php echo $this->__('Jewelry');?>
              </div>
              <div class="list">
                <a class="selectAll" href="javascript:void(0)"><?php echo $this->__('Show all');?></a>
                 <ol>
                   <?php foreach($productType as $colId =>$colVal):?>
                        <li><input type="checkbox" name="product_type" data-optionval="<?php echo $colVal;?>" id="<?php echo $colId;?>" value="<?php echo $colId;?>" class="shopby-attr" data-attname="product_type" data-id="<?php echo $colId;?>">
                        <label for="<?php echo $colId;?>"><span><?php echo ucfirst(strtolower($colVal));?></span></label>
                        </li>
                   <?php endforeach;?>
                 </ol>
              </div>
            </div>
        <?php endif; ?>
        <?php if(count($subCategory) > 0):?>
            <div class="filter-options ring_style">
              <div class="filter-label">
                <?php echo $this->__('Ring Style');?>
              </div>
              <div class="list">
                <a class="selectAll" href="javascript:void(0)"><?php echo $this->__('Show all');?></a>
                 <ol>
                   <?php foreach($subCategory as $styleId=>$style):?>
                        <li><input type="checkbox" name="ring_style" data-optionval="<?php echo $style;?>" id="<?php echo $styleId;?>" value="<?php echo $styleId;?>" class="shopby-attr" data-attname="sub_category" data-id="<?php echo $styleId;?>">
                        <label for="<?php echo $styleId;?>"><span><?php echo ucfirst(strtolower($style));?></span></label>
                        </li>
                   <?php endforeach;?>
                 </ol>
              </div>
            </div>
        <?php endif; ?>

        <div class="filter-options sort-by">
          <div class="filter-label">
            <?php echo $this->__('Sort by');?>
          </div>
          <div class="list">
             <ol>
               <li><a href="javascript:void(0);" class="shopby-attr sort-by" data-sort="asc" data-order="price"><?php echo $this->__("Price(Ascending Direction)");?></a></li>
               <li><a href="javascript:void(0);" class="shopby-attr sort-by" data-sort="desc" data-order="price"><?php echo $this->__("Price(Descending Direction)");?></a></li>
               <li><a href="javascript:void(0);" class="shopby-attr sort-by" data-sort="asc" data-order="bestseller"><?php echo $this->__("Best Sellers");?></a></li>
             </ol>
          </div>
        </div>

        <div class="filter-options price_range_filter">
          <div class="filter-label">
            <?php echo $this->__('Price');?>
          </div>
          <div class="list">
            <input type="text" id="min-priceval" class="updateclass">
            <input type="text" id="max-priceval" class="updateclass">
          <div id="price_range_filter"></div>
          </div>
        </div>
    </div>
  </div>
