<?php $urlJs = Mage::helper('detailedreview')->getDetailReviewJsUrl(); ?>
<?php if (Mage::getStoreConfig('detailedreview/datetime_options/enable_to_set_timezone')): ?>
    <script type="text/javascript">
        window.addEventListener('updateDateDR', function (e) {
            $$('.review-date').each(function(e) {
                var d = new Date(),
                    date = {
                        utc: e.readAttribute('data-utc'),
                        offset: d.getTimezoneOffset() * -1,
                        format: e.readAttribute('data-format')
                    };
                if (moment.utc(date.utc).utcOffset(date.offset).isValid()) {
                    e.innerHTML = moment.utc(date.utc).utcOffset(date.offset).format(date.format);
                } else {
                    e.innerHTML = '';
                    console.log('Invalid date format');
                }
            });
        });
    </script>
<?php endif; ?>