<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_GiftCard
 */
?>
<?php /* @var $this Amasty_GiftCard_Block_Catalog_Product_Price */ ?>
<?php
$_coreHelper = $this->helper('core');
$_weeeHelper = $this->helper('weee');
$_taxHelper = $this->helper('tax');

$_product = $this->getProduct();
$_minPrice = $this->getMinPrice();
$_exclTax = $_taxHelper->getPrice($_product, $_minPrice);
$_inclTax = $_taxHelper->getPrice($_product, $_minPrice, true);

$_id = $_product->getId();
?>
<?php if ($_product->getCanShowPrice() !== false && $_minPrice):?>
	<div class="price-box">
		<p<?php if ($this->isMultiAmount()): ?> class="minimal-price"<?php endif ?>>
			<?php if($this->isMultiAmount()): ?>
				<span class="price-label" id="min-product-price-<?php echo $_product->getId(); ?>-label<?php echo $this->getIdSuffix(); ?>"><?php echo Mage::helper('amgiftcard')->__('From'); ?></span>
			<?php endif; ?>


			<?php if ($_taxHelper->displayBothPrices()): ?>
				<span class="price-excluding-tax">
							<span class="label"><?php echo $_taxHelper->__('Excl. Tax:') ?></span>
							<span class="price"
								  id="price-excluding-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
								<?php echo $_coreHelper->currency($_exclTax, true, false) ?>
							</span>
						</span>
				<span class="price-including-tax">
							<span class="label"><?php echo $_taxHelper->__('Incl. Tax:') ?></span>
							<span class="price"
								  id="price-including-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
								<?php echo $_coreHelper->currency($_inclTax, true, false) ?>
							</span>
						</span>
			<?php else: ?>
				<?php
				$_showPrice = $_inclTax;
				if (!$_taxHelper->displayPriceIncludingTax()) {
					$_showPrice = $_exclTax;
				}
				?>
				<span class="price" id="product-minimal-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
						<?php echo $_coreHelper->currency($_showPrice, true, false) ?>
					</span>
			<?php endif; ?>

			<?php if ($this->isMultiAmount()): ?>
				<span class="price-label" id="product-price-<?php echo $_product->getId(); ?>-label<?php echo $this->getIdSuffix(); ?>">
					<?php echo Mage::helper('amgiftcard')->__('Price as calculated'); ?>
					<?php if ($_taxHelper->displayBothPrices() || $_taxHelper->displayPriceIncludingTax()): ?>

						<?php echo $_taxHelper->__('Excl. Tax:') ?>

					<?php endif; ?>
				</span>

				<span class="price" id="min-product-price-<?php echo $_product->getId(); ?><?php echo $this->getIdSuffix(); ?>">
					<?php echo $_coreHelper->currency($_minPrice,true,false);?>
				</span>
			<?php endif ?>
		</p>
	</div>
<?php endif; ?>
