<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_GiftCard
 */
?>
<?php
/* @var $this Amasty_GiftCard_Block_Sales_Order_GiftCards */
?>
<?php
$_order  = $this->getOrder();
$_source = $this->getSource();
$_cards  = $this->getGiftCards();
?>
<?php if ($_cards):?>
	<?php foreach ($_cards as $_card): ?>
		<tr>
			<td <?php echo $this->getLabelProperties()?>>
				<?php echo Mage::helper('amgiftcard')->__('Gift Card (%s)', $_card['c']); ?>
			</td>
			<td <?php echo $this->getValueProperties()?>>-<?php echo $_order->formatPrice($_card['a']) ?></td>
		</tr>
	<?php endforeach; ?>
<?php elseif ($_source->getAmGiftCardsAmount()>0): ?>
	<tr>
		<td <?php echo $this->getLabelProperties()?>>
			<?php echo Mage::helper('amgiftcard')->__('Gift Card'); ?>
		</td>
		<td <?php echo $this->getValueProperties()?>>-<?php echo $_order->formatPrice($_source->getAmGiftCardsAmount()) ?></td>
	</tr>
<?php endif?>
