<a href='{{!it.review.product.drw_url}}#rw_{{!it.review.review_id}}' target='_blank'>
    <div class='drw-image-box'>
        <div class='drw-image-review'>
            <img src='{{!it.review.image}}' alt='' />
        </div>
    </div>
</a>

<div class='drw-item-info'>
    {{?it.review.rating}}
        <div class='ratings-table'>
            <div class='rating-box'>
                <div class='rating' style='width:{{=it.review.rating}}%;'></div>
            </div>
        </div>
    {{?}}
    <div class='drw-review-dt image' id='rw_{{=it.review.review_id}}'>
        <span class='drw-title'>{{!it.review.title}}</span>
        <span class='drw-nickname'>{{!it.review.nickname}}</span>
    </div>
    
    {{=it.review.vote}}
    <div class='drw-review-dd'>
        <div class='drw-social-share image social-share'>
            {{? it.review.fb}}
                {{=it.review.fb}}
            {{?}}
            {{? it.review.tw}}
                {{=it.review.tw}}
            {{?}}
            {{? it.review.pt}}
                {{=it.review.pt}}
            {{?}}
            {{? it.review.mailto}}
                {{=it.review.mailto}}
            {{?}}
        </div>
    </div>
</div>

