<?php
/** @var Cminds_Multiwishlist_Block_Popup_Form $this */

$items = $this->getItems();
$helper = Mage::helper('cminds_multiwishlist');
?>

<div class="multiwishlist_popup">
    <div class="popup-left">
        <span class="loggedin"><?php echo $this->__('Please login first') ?> <a href="<?php echo Mage::getUrl('customer/account/login'); ?>">Login</a> </span>
        <h3 class="title"><?php echo $this->__('Create board') ?></h3>
        <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
            <div class="field">
                <div class="input-box savebox">
                    <input type="radio" name="wishlist_id" value="new-wishlist" title="<?php echo $helper->__('create new Wishlist'); ?>" class="checkbox" />
                    <input type="text" name="new_wishlist_name" id="new_wishlist_name" placeholder="Name"/>
                </div>
                <span class="saveaction"><a href="javascript:void(0);"><?php echo $this->__('Save') ?></a></span>
            </div>
            <input type="hidden" name="multiwishlist-product-id" id="multiwishlist-product-id" />
            <input type="hidden" name="multiwishlist-ajax-url" id="multiwishlist-ajax-url" value="<?php echo Mage::app()->getStore()->getUrl('wizard/index/productimage');?>" />
            <?php echo $this->getBlockHtml('formkey')?>
            <div class="choose-board-block">
                <h3 class="title"><?php echo $this->__('Choose board') ?></h3>
                <div class="fieldset">
                <ul class="form-list">
                    <li class="fields">
                        <?php if(count($items) > 0): ?>
                            <?php foreach($items as $item): ?>
                                <div class="field">
                                    <div class="input-box">
                                        <input type="radio" name="wishlist_id" id="Wishlist<?php echo $item->getWishlistId();?>"
                                               value="<?php echo $this->escapeHtml($item->getWishlistId()); ?>"
                                               title="<?php echo $this->escapeHtml($item->getName()) ?>" class="radio"
                                        />
                                        <label for="Wishlist<?php echo $item->getWishlistId();?>"><?php echo $this->escapeHtml($item->getName()); ?></label>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </li>
                </ul></div>
            </div>
            <div class="suggested-board-block">
                <h4 class="title"><?php echo $this->__('Suggested board names') ?></h4>
                <ul class="suggested"></ul>
            </div>
        </form>
    </div>
    <div class="popup-right"></div>
</div>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    //]]>
    jQuery(document).ready(function(){
        jQuery('.saveaction').click(function(){
            jQuery('.savebox input[name="wishlist_id"]').prop('checked', true);
            document.getElementById('form-validate').submit();
        })
        jQuery('.form-list input[name="wishlist_id"]').click(function(){
            jQuery(this).prop('checked', true);
            document.getElementById('form-validate').submit();
        })
        jQuery(document).on('click', '.suggested li', function(){
            var value = jQuery(this).text();
            jQuery('input[name="new_wishlist_name"]').val(value);
            jQuery('.savebox input[name="wishlist_id"]').prop('checked', true);
            document.getElementById('form-validate').submit();
        })
    })
</script>