<?php if (Mage::getStoreConfig('detailedreview/social_share_optios/share_review_by_email')): ?>
    <div class="drw-email-popup-wrapper email-share-hide">
        <div class="email-popup-background"></div>
        <div class="email-popup-wrapper">
            <div class="drw-email-popup-header">
                <h2><?php echo $this->__('Share Review By Email'); ?></h2>
            </div>
            <div class="drw-email-popup-content">
                <ul class="drw-share-email-messages messages email-share-hide">
                </ul>
                <div class="drw-email-popup-image"></div>
                <form id="drw-email-share-form" class="drw-email-share-form" action="" name="drw-email-form">
                    <div class="drw-email-input-wrapper">
                        <div class="drw-form-group">
                            <a class="drw-email-message-link" href="#" target="_blank">
                                <?php echo $this->__('Link to Review'); ?>
                            </a>
                        </div>
                        <div class="drw-form-group">
                            <label for="drw-email-share-name" class="required"><em>*</em><?php echo $this->__('Your name'); ?></label>
                            <div>
                                <input type="text" id="drw-email-share-name" name="drw-email-share-customer-name" class="drw-email-share-name input-text required-entry">
                            </div>
                        </div>

                        <div class="drw-form-group">
                            <label for="drw-email-share-email" class="required"><em>*</em><?php echo $this->__('Your e-mail address'); ?></label>
                            <div>
                                <input type="email" id="drw-email-share-email" name="drw-email-share-customer-email" class="drw-email-share-email input-text required-entry validate-email">
                            </div>
                        </div>

                        <div class="drw-form-group">
                            <label for="drw-email-share-mail-to" class="required"><em>*</em><?php echo $this->__('Email address of your friend'); ?></label>
                            <div>
                                <input type="email" id="drw-email-share-mail-to" name="drw-email-share-mail-to[]" class="drw-email-share-mail-to input-text required-entry validate-email">
                            </div>
                            <span class="add-recipient-button"><a href="#"><?php echo $this->__('Add Recipient'); ?></a></span>
                        </div>

                        <div class="drw-form-group">
                            <label for="drw-email-share-subject" class="required"><em>*</em><?php echo $this->__('Subject'); ?></label>
                            <div>
                                <input type="text" id="drw-email-share-subject" name="drw-email-share-subject" class="drw-email-share-subject input-text required-entry">
                            </div>
                        </div>

                        <div class="drw-form-group">
                            <label for="drw-email-share-mail-body" class="required"><em>*</em><?php echo $this->__('Your message'); ?></label>
                            <div>
                                <textarea id="drw-email-share-mail-body" name="drw-email-share-mail-body" class="required-entry drw-email-share-mail-body"></textarea>
                            </div>
                        </div>
                        <div class="drw-form-group">
                            <div>
                                <input type="hidden" id="drw-email-share-image" name="drw-email-share-image" class="drw-email-share-image">
                                <input type="hidden" id="drw-email-share-link" name="drw-email-share-link" class="drw-email-share-link">
                            </div>
                        </div>
                    </div>
                    <div class="drw-email-button-wrapper">
                        <input type="submit" name="drw-email-share-submit" class="drw-email-button drw-email-submit" value="Submit">
                        <input type="button" class="drw-email-button drw-email-close" value="Close">
                    </div>
                </form>
            </div>
        </div>
    </div>
<?php endif; ?>
