<?php
$fedexcross = Mage::getStoreConfig('wizard/wizard_group/fedex_cross');
$fedexcross = floatval($fedexcross);
?>
<?php $cartTotal = $this->helper('checkout/cart')->getQuote()->getGrandTotal();?>
<p class="checkout-back back-link mobile-back-link"><a href="#" onclick="checkout.back(); return false;"><i class="fa fa-angle-left"></i><?php echo $this->__('Back') ?></a></p>
<div class="page-title">
    <h1><?php echo $this->__('Checkout') ?></h1>
</div>
<script type="text/javascript" src="<?php echo $this->getJsUrl('oye/accordion.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/oye/checkout/horizontal/opcheckout.js') ?>"></script>
<?php $count = count($this->getSteps()); ?>
<div id="oye-horizontal">
    <p class="checkout-back back-link"><a href="#" onclick="checkout.back(); return false;"><i class="fa fa-angle-left"></i><?php echo $this->__('Back') ?></a></p>
    <ol id="checkoutSteps" class="step-menu" <?php if($count == 5): ?> class="logged-in"<?php endif; ?>>
        <?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
        <?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++ ?>
         <li class="section section-header opc-<?php echo $_stepId ?><?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
            <div class="step-title">
                <span><?php echo $_stepInfo['label'] ?></span>
                <span class="icon"></span>
            </div>
         </li>
        <?php endforeach ?>

        <li class="section section-header finish">
            <div class="step-title">
                <span>Finish</span>
                <span class="icon"></span>
            </div>
         </li>
    </ol>
    <?php if($cartTotal < $fedexcross): ?>
        <div class="fedextotal"><?php echo $this->__('Your Order eligible for FedEx Overnight if cross '.Mage::helper('core')->currency($fedexcross, true, false).' amount')?></div>
    <?php endif; ?>

   <ol class="opc" id="checkoutStepsContent">
        <?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
            <?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++ ?>
            <li id="opc-<?php echo $_stepId ?>" class="section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
                <ul class="opc-step-wrap">
                    <div id="checkout-step-<?php echo $_stepId ?>" class="step a-item" style="display:none;">
                        <?php echo $this->getChildHtml($_stepId) ?>
                    </div>
                </ul>

            </li>
        <?php endforeach ?>
    </ol>
</div>
<script type="text/javascript">
//<![CDATA[
    var accordion = new OyeAccordion('checkoutSteps', '.step-title', true);
    accordion.setHeaders('.section .section-header');
    <?php if($this->getActiveStep()): ?>
    accordion.openSection('opc-<?php echo $this->getActiveStep() ?>');
    <?php endif ?>
    var checkout = new Checkout(accordion,{
        progress: '<?php echo $this->getUrl('checkout/onepage/progress') ?>',
        review: '<?php echo $this->getUrl('checkout/onepage/review') ?>',
        saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',
        failure: '<?php echo $this->getUrl('checkout/cart') ?>'}
    );
//]]>
</script>