<?php
$takeaTest = array();
$title =  get_field('take_a_test_title','option');
if(have_rows('question-answer','option')): ?>
<?php
    while(have_rows('question-answer','option')): the_row();
            $question = get_sub_field('question','option');
            $option1 = get_sub_field('option1','option');
            $option2 = get_sub_field('option2','option');
            $option3 = get_sub_field('option3','option');
            $rightAnswer = get_sub_field('right_answer','option');
            $tooltip = get_sub_field('tooltip','option');
            $takeaTest[]= array($question,$option1,$option2,$option3,$rightAnswer,$tooltip);
    endwhile;
    $takeaTest = array_chunk($takeaTest,3);
  /*  echo '<pre>';
    print_r($takeaTest);
    exit;*/
?>
<section class="takearest-section">
    <h2><?php echo $title;?></h2>
    <div class="content">
        <div class="left-block">
        <?php $j=1;$i = 1;foreach($takeaTest[0] as $index => $qa):
                $question = $qa[0];
                $option1 = $qa[1];
                $option2 = $qa[2];
                $option3 = $qa[3];
                $rightAnswer = $qa[4];
                $tooltip = $qa[5]; ?>
                <div class="wizard-block">
                    <h3 class="q-title"><span class="number"><?php echo $i ?></span><?php echo $qa[0];?></h3>

                    <div class="options-block">
                        <ul>
                          <?php for ($k=1; $k < 4 ; $k++) { $random = rand(); ?>
                            <li class="option">
                                <input type="radio" id="option<?php echo $random; ?>" name="option<?php echo $j; ?>" class="checkbox"  data-option="<?php echo $k;?>" data-answer="<?php echo $rightAnswer;?>" data-flag="0">
                                <label for="option<?php echo $random; ?>"><?php echo $qa[$k];?></label>
                                <?php if($k == $rightAnswer): ?>
                                  <div class="faq-tooltip-options">
                                      <div class="faq-tooltip-image rubberBand animated">
                                          <img src="<?php echo $this->getSkinUrl('images/faq-tooltip-icon.png'); ?>" alt="" />
                                      </div>
                                      <div class="faq-tooltip-content"><?php echo $tooltip;?>
                                      </div>
                                  </div>
                                <?php endif; ?>
                            </li>
                          <?php } ?>
                        </ul>
                    </div>
                </div>
        <?php $i++; $j++; endforeach;?>
        </div>
        <div class="middle-block">

            <div class="image">
            	 <ul class="number-text">
            	        	<li class="n1">5</li>
            	        	<li class="n2">6</li>
            	        	<li class="n3">1</li>
            	        	<li class="n4">2</li>
            	        	<li class="n5">3</li>
            	        	<li class="n6">4</li>
            	        </ul>
            	 <div class="c100 p0 big">

                    <span class="percent-text"><span class="score">0</span>%</span>
                    <div class="slice">
                        <div class="bar"></div>
                        <div class="fill"></div>
                    </div>
                </div>
            </div>
            <div class="description" style="display: none;">
                <h2><strong><?php echo $this->__('Congratulations!');?></strong></h2>
                <p><?php //echo $this->__('You’re ready to create your very own ring!')?></p> <a href="#" class="readmore"><?php echo $this->__('Start Now');?></a> </div>
        </div>

        <div class="right-block">
        <?php $j=10; $i=4;foreach($takeaTest[1] as $index=>$qa):?>
        <?php
                $question = $qa[0];
                $option1 = $qa[1];
                $option2 = $qa[2];
                $option3 = $qa[3];
                $rightAnswer = $qa[4];
                $tooltip = $qa[5];
        ?>
            <div class="wizard-block">
                <h3 class="q-title"><span class="number"><?php echo $i ?></span><?php echo $question;?>

                </h3>
                <div class="options-block">
                    <ul>
                      <?php for ($k=1; $k < 4 ; $k++) {  $random = rand(); ?>
                            <li class="option">
                                <input type="radio" id="option<?php echo $random; ?>" name="option<?php echo $j; ?>" class="checkbox"  data-option="<?php echo $k;?>" data-answer="<?php echo $rightAnswer;?>" data-flag="0">
                                <label for="option<?php echo $random; ?>"><?php echo $qa[$k];?></label>
                                <?php if($k == $rightAnswer): ?>
                                  <div class="faq-tooltip-options">
                                      <div class="faq-tooltip-image rubberBand animated">
                                          <img src="<?php echo $this->getSkinUrl('images/faq-tooltip-icon.png'); ?>" alt="" />
                                      </div>
                                      <div class="faq-tooltip-content"><?php echo $tooltip;?>
                                      </div>
                                  </div>
                                <?php endif; ?>
                            </li>

                          <?php } ?>
                    </ul>
                </div>
            </div>
         <?php $i++;$j++; endforeach;?>
        </div>
    </div>

    <div class="submit-section-mobile">
      <div class="submit-btn">
        <input class="submit" type="submit" value="submit">
        <input class="skip" type="submit" value="skip">
      </div>
      <div class="checkout-step">
        <ul>
          <li><a href="#" class="active">1</a></li>
          <li><a href="#">2</a></li>
          <li><a href="#">3</a></li>
          <li><a href="#">4</a></li>
          <li><a href="#">5</a></li>
          <li><a href="#">6</a></li>
        </ul>
        <div class="diamond-icon"><a href="#"><img width="30" src="<?php echo $this->getSkinUrl('images/chart-diamond.jpg'); ?>" alt="diamond icon"></a></div>
      </div>
    </div>

</section>
<?php endif;?>
<script type="text/javascript">
jQuery(document).ready(function(){
   jQuery(".checkbox").change(function(){
      var answer = jQuery(this).data("answer");
      var option = jQuery(this).data("option");
      var flag = jQuery(this).attr("data-flag");
      if(option == answer){
          var score = parseInt(jQuery('.middle-block .score').text());
          jQuery(".middle-block .image div").removeClass("p"+score);
          jQuery(".faq-tooltip-image").removeClass("rubberBand");
          if(score < 100){
              if(score == 85){
                  score = score + 15;
                  jQuery(this).parents('ul').find('input').attr('data-flag', '1');
                  jQuery(".middle-block .image div").addClass("p"+score);
              }else{
                  score = score + 17;
                  jQuery(this).parents('ul').find('input').attr('data-flag', '1');
                  jQuery(".middle-block .image div").addClass("p"+score);
              }
              if(score == 100){
                  jQuery(".description").show();
              }
            jQuery('.middle-block .score').text(score);
          }
      }else{
          var score = parseInt(jQuery('.middle-block .score').text());
          jQuery(this).parents('.wizard-block').find(".faq-tooltip-options .faq-tooltip-image").removeClass("rubberBand");
          jQuery(this).parents('.wizard-block').find(".faq-tooltip-options .faq-tooltip-image").addClass("rubberBand");
          jQuery(".middle-block .image div").removeClass("p"+score);
          if(score > 0 && flag == 1){
              if(score == 100){
                score = score - 15;
                jQuery(this).parents('ul').find('input').attr('data-flag', '0');
                jQuery(".middle-block .image div").addClass("p"+score);

              }else{
                score = score - 17;
                jQuery(this).parents('ul').find('input').attr('data-flag', '0');
                jQuery(".middle-block .image div").addClass("p"+score);
              }
              if(score < 100){
                  jQuery(".description").hide();
              }
              jQuery('.middle-block .score').text(score);
          }else{
            jQuery(".middle-block .image div").addClass("p"+score);
          }
      }
   });
});
</script>