<?php
     $trendPost = $this->getCustomPostId();
     $id = $trendPost->ID;
     $title = $trendPost->post_title;
     $content = $trendPost->post_content;
     $tImage = get_field('trending_image',$id);
     $trendingImage = Mage::helper('latestblogpost')->getResizedHomeNewsImage($tImage['url'], 315, 271,"trending-post")
?>
<div class="image">
    <img src="<?php echo $trendingImage; ?>" />
</div>
<h3><?php echo $title ?></h3>
<?php echo $content; ?>