<?php
$diamondCut = array();
$title =  get_field('rts_jewellery_title','option');
$Description =  get_field('rts_jewellery_description','option');
$label =  get_field('rts_jewellery_label','option');
$link =  get_field('rts_jewellery_link','option');
$newtab = '';
$catLink = "javascript:void(0);";
if($link){
    $newtab = 'target="_blank"';
    $catLink = check_custom_diamondlink($link);
} ?>
<?php
if(have_rows('rts_style','option')):
    while(have_rows('rts_style','option')): the_row();
        $diamondName = get_sub_field('rts_style_label','option');
        $diamondLink = get_sub_field('rts_style_link','option');
        $diamondImage = get_sub_field('rts_style_image','option');
        $diamondVideo = get_sub_field('rts_style_video','option');
        $diamondImageOrVideo = get_sub_field('rts_style_select_video_or_image','option');
        $diamondCut[]= array($diamondName,$diamondLink,$diamondImage,$diamondText,$diamondVideo,$diamondImageOrVideo);
    endwhile;
    $diamondCut = array_chunk($diamondCut,2);?>
<section class="diamond-cuts-section rts-our-jewelery-section">
    <div class="description">
        <h2><?php echo $title;?></h2>
        <p><?php echo $Description;?></p>
        <a href="<?php echo $catLink;?>" class="readmore" <?php echo $catLink; ?>><?php echo $label;?></a>
    </div>
    <div class="container">
    <div class="row">
        <ul>
        <?php $i = 0;
            $class = "left-block text-left col-sm-4";
            foreach($diamondCut as $diamond): ?>
            <?php if($i == 0): $class = "left-block text-left col-sm-4";?>
            <?php elseif($i == 1): $class = "right-block pull-right col-sm-4 text-center";?>
            <?php else: $class = "middle-block col-sm-4 text-right"; ?>
            <?php endif; ?>

                    <?php  STATIC $count = 1;foreach($diamond as $cut):
                         $dcLink = "javascript:void(0);";
                         $diamondStyle = $cut[0];
                         $diamondLink = $cut[1];
                         if($diamondLink): $dcLink = check_custom_diamondlink($diamondLink); endif;
                         $image = Mage::helper('latestblogpost')->getResizedHomeNewsImage($cut[2]["url"], 187, 185,"home-diamond");
                         $diamondText = $cut[3];?>
                    <li class="item item<?php echo $count++; ?>">

                    <?php if( $cut[5] == 'Image'){ ?>
                    <?php if(!empty($cut[2])) { ?>
                       <div class="image">
                            <img src="<?php echo $cut[2]["url"];?>" alt="" />
                        </div>
                    <?php } } ?>
                    <?php if($cut[5] == 'Video'){ ?>
                    <?php if(!empty($cut[4])) { ?>
                        <div class="image">
                           <div class="video-wrapper">
                                <video autoplay loop>
                                    <source src="<?php echo $cut[4]['url']; ?>" type="video/mp4">
                                </video>
                            </div>
                        </div>
                    <?php } } ?>




                        <div class="details">
                            <h3><a href="<?php echo $dcLink;?>" title="<?php echo $diamondStyle;?>"><?php echo $diamondStyle;?></a></h3>
                            <p><?php echo $diamondText;?></p>
                        </div>
                    </li>

                    <?php endforeach;?>


        <?php $i++; endforeach;?>
        </ul>
        <?php /* ?><li class="viewall-links">
            <a href="<?php echo $catLink;?>" title="<?php echo $label;?>" <?php echo $newtab;?>><?php echo $label;?></a>
        </li><?php */ ?>
        </div>
    </div>
</section>
<?php endif;?>
<?php
    function check_custom_diamondlink($arglink)
    {
        $httpPost = strpos($arglink,'http');
        if(strlen($arglink)==0)
        {
            $link = 'javascript:;';
        }
        elseif(strlen($httpPost)==0)
        {
           $link = Mage::getUrl().$arglink;
        }
        else
        {
           $link = $arglink;
        }
        return $link;
    }
?>

<script type="text/javascript">
    jQuery(window).on('load',function () {
      jQuery('video').trigger('play');
    });
</script>
