<?php
/** @var Cminds_Multiwishlist_Block_Popup_Form $this */

$items = $this->getItems();
$helper = Mage::helper('cminds_multiwishlist');
?>

<div class="multiwishlist_popup" style="padding: 20px">
    <div class="page-title">
        <h1><?php echo $this->__('Please select the Wishlist you want to add Product') ?></h1>
    </div>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <input type="hidden" name="multiwishlist-product-id" id="multiwishlist-product-id" />
        <?php echo $this->getBlockHtml('formkey')?>
        <div class="fieldset">
            <ul class="form-list">
                <li class="fields">
                    <?php if(count($items) > 0): ?>
                        <?php foreach($items as $item): ?>
                            <div class="field">
                                <div class="input-box">
                                    <input type="radio" name="wishlist_id" id="wishlist_id"
                                           value="<?php echo $this->escapeHtml($item->getWishlistId()); ?>"
                                           title="<?php echo $this->escapeHtml($item->getName()) ?>" class="checkbox"
                                    />
                                    <label for="wishlist_id"><?php echo $this->escapeHtml($item->getName()); ?></label>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <div class="field">
                        <div class="input-box">
                            <input type="radio" name="wishlist_id" id="wishlist_id"
                                   value="new-wishlist"
                                   title="<?php echo $helper->__('create new Wishlist'); ?>" class="checkbox"
                            />
                            <label for="cart_receivers"><?php echo $helper->__('create new Wishlist'); ?></label>
                            <input type="text" name="new_wishlist_name" id="new_wishlist_name" placeholder="Wishlist Name"/>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set">
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
    </form>
</div>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    //]]>
</script>