<?php
$title =  get_field('homepartner_category_title','option');
$description =  get_field('homepartner_category_description','option');
$image =  get_field('homepartner_category_image','option');
$label =  get_field('homepartner_category_label','option');
$link =  get_field('homepartner_category_link','option');
$newtab = '';
$catLink = "javascript:void(0);";
if($link){
    $newtab = 'target="_blank"';
    $catLink = check_custom_explorelink($link);
}
?>
<section class="our-jewelry-section explore-section">
    <div class="description">
        <h2><?php echo $title; ?></h2>
        <?php echo $description;?>
        <a class="readmore" href="<?php echo $catLink;?>" title="<?php echo $label;?>" <?php echo $newtab;?>><?php echo $label;?></a>
    </div>
    <div class="left-block">
        <img src="<?php echo $image['url']; ?>" alt="<?php echo $this->__('Our Jewelary');?>">
    </div>
    <div class="right-block">
        <?php if(have_rows('homepartner_category','option')):  ?>
                <div class="bottom-block">
                    <ul>
                         <?php  while(have_rows('homepartner_category','option')): the_row(); ?>
                             <?php
                              $categoryName = get_sub_field('hpartner_category_label','option');
                              $categoryLink = get_sub_field('hpartner_category_link','option');
                              $categoryImage = get_sub_field('hpartner_category_image','option');
                              $image = Mage::helper('latestblogpost')->getResizedHomeNewsImage($categoryImage['url'], 245, 210,"homepartner-category");
                              $cLink = "javascript:void(0);";?>
                              <?php
                                if($categoryLink):
                                   $cLink = check_custom_explorelink($categoryLink);
                                endif;
                              ?>
                                <li>
                                    <img src="<?php echo $image; ?>" alt="<?php echo $categoryName;?>" /> 
                                    <h3><a href="<?php echo $cLink;?>" title="<?php echo $categoryName;?>"><?php echo $categoryName;?></a></h3>
                                </li>
                        <?php endwhile; ?>
                    </ul>
                </div>
        <?php endif;  ?>
    </div>
</section>
<?php
    function check_custom_explorelink($arglink)
    {
        $httpPost = strpos($arglink,'http');
        if(strlen($arglink)==0)
        {
            $link = 'javascript:;';
        }
        elseif(strlen($httpPost)==0)
        {
           $link = 'http://'.$arglink;
        }
        else
        {
           $link = $arglink;
        }
        return $link;
    }
?>


