<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_GiftCard
 */
?>
<?php /* @var $this Mage_Adminhtml_Block_Sales_Order_Totals_Item */?>
<?php $_source  = $this->getSource() ?>
<?php $this->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getAmGiftCardsAmount()): ?>
	<tr>
		<td class="label"><?php echo Mage::helper('amgiftcard')->__('Gift Cards') ?></td>
		<td>
			<?php echo $this->displayPrices(-$_source->getAmBaseGiftCardsAmount(), -$_source->getAmGiftCardsAmount()); ?>
		</td>
	</tr>
<?php endif; ?>