<?php $helper = Mage::Helper('wizard');?>
<?php $_total=$this->getItems()->count() ?>
    <?php if($_total): ?>
        <div class="compare-window" id="product_comparison">
                <div class="page-title">
                    <h2><?php echo $this->__('Compare') ?></h2>
                </div>
               <ul class="product-shop">
                <?php foreach($this->getItems() as $_item):?>
                    <li>
                        <div class="product-image-zoom"> <a class="product-image" href="#" onclick="setPLocation('<?php echo $this->getProductUrl($_item) ?>', true)" title="<?php echo $this->stripTags($_item->getName(), null, true) ?>">
                       <img
                          src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(328); ?>"
                          data-zoom-image="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(500); ?>"
                          alt="<?php echo $this->stripTags($_item->getName(), null, true) ?>"
                        />
                    </a>
                       <a href="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(1000); ?>"  class="zoom-icon" data-fancybox><img src="<?php echo $this->getSkinUrl('images/zoom-icon1.png'); ?>" alt="" /></a>
                        </div>
                        <h2 class="product-name"><a href="#" onclick="setPLocation('<?php echo $this->getProductUrl($_item) ?>', true)" title="<?php echo $this->stripTags($_item->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getVariantRemark(), 'name') ?></a></h2>
                        <div class="std short-description">
                            <?php /*foreach ($this->getAttributes() as $_attribute): ?>
                                <?php echo $this->helper('catalog/output')->productAttribute($_item, $this->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode()) ?>
                                    <?php endforeach;*/ ?>
                                <?php echo $_item->getShortDescription();?>
                        </div>
                        <?php echo $this->getReviewsSummaryHtml($_item, 'short') ?>
                            <?php echo $this->getPriceHtml($_item, true, '-compare-list-top') ?>
                                <div class="info-table">
                                    <table border="0" width="100%" cellpadding="0" cellspacing="0">
                                        <tbody>
                                            <tr>
                                                <th><?php echo $this->__('Ring Information');?></th>
                                            </tr>
                                            <tr>
                                                <td><?php echo $this->__('Style: '). $helper->getAttributeValue('sub_category',$_item->getSubCategory());?></td>
                                            </tr>
                                            <tr>
                                                <td><?php echo $this->__('Metal: ').$helper->getAttributeValue('karat',$_item->getKarat())." ".$helper->getAttributeValue('metal_type',$_item->getMetalType());?></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="buttons-wrapper"> <a href="javascript:void(0)" class="remove" onclick="removeItem('<?php echo $this->helper('catalog/product_compare')->getRemoveUrl($_item) ?>');" title="<?php echo $this->quoteEscape($this->__('Remove This Item')) ?>"><?php echo $this->__('Remove') ?></a></div>
                    </li>
                    <?php endforeach; ?>
            </ul>



        </div>
        <script type="text/javascript">
            decorateTable('product_comparison');
            jQuery(window).load(function(){
                equalheight(".compare-sidebar-window .compare-window li");
            });
            jQuery(window).resize(function(){
                equalheight(".compare-sidebar-window .compare-window li");
            });
        </script>

<?php endif; ?>