<?php $helper = Mage::helper('sociallogin'); ?>
<?php Mage::getSingleton('customer/session')
          ->setBeforeAuthUrl(Mage::helper("core/url")->getCurrentUrl());?>
<?php if (!$helper->isLoggedIn()){ ?>
<?php if ($helper->isEnableExtension()==1){ ?>
<?php $app_idDN= Mage::getStoreConfig('config_options/facebook/appid');?>
<?php
 $session = Mage::getSingleton('customer/session');
 //$session->setAfterAuthUrl(Mage::helper('core/url')->getCurrentUrl());
 Mage::getSingleton('customer/session')
          ->setBeforeAuthUrl(Mage::helper("core/url")->getCurrentUrl());

?>
<script type="text/javascript" src="<?php echo  $this->getJsUrl('sociallogin/sociallogin.js'); ?>"></script>
<?php }} ?>
    <!-- popup -->
    <div id="header_logo_Div" style="display: none; top: 174px; left: 245px;">
        <a class="closeLink" href="javascript:fme_socialloginclose();"></a>
        <div id="social_popup_main">
            <div id="socialpopup_main_div">
                <div class="left_login">
                    <!-- login block -->   
                    <div style="display: block;" id="login_block">
                    <?php //echo $session->getBeforeAuthUrl(); ?>
                        <form id="form_login" class="socialpopup_form">
                            <h4><?php echo Mage::helper('sociallogin')->__('log in'); ?></h4>
                            <label for="email" class="required"><?php echo Mage::helper('sociallogin')->__('Email'); ?>
<em>*</em></label>
                            <div class="socialpopup-input-box">
                                <input class="" name="email" id="email" title="<?php echo Mage::helper('sociallogin')->__('Email'); ?>" type="text">
                                <div id="email_error" class="popup_error_msg"></div>
                            </div>
                            <label for="pass" class="required"><?php echo Mage::helper('sociallogin')->__('Password'); ?> <em>*</em></label>
                            <div class="socialpopup-input-box">
                                <input class="" name="password" id="password" title="<?php echo Mage::helper('sociallogin')->__('Password'); ?>" type="password">
                                <div id="password_error" class="popup_error_msg"></div>
                                <div id="progress_image_login" style="display: none">
                                    <img src="<?php echo $this->getSkinUrl('sociallogin/images/ajax-loader.gif'); ?>" alt="<?php echo Mage::helper('sociallogin')->__('Please wait'); ?>">
                                </div>
                                <div class="social_login_btn">
                                    <a href="javascript:void(0);" id="show_password" onclick="return show_password();"><?php echo Mage::helper('sociallogin')->__('Did you forgot your password?'); ?></a>
                                    <button type="button" class="button popup_click_btn" title="Login" name="send" onclick="return sendLogin();" id="slogin"><span><span><?php echo Mage::helper('sociallogin')->__('Login'); ?></span></span></button>
                                </div>
                            </div>
                        </form>
                        <div class="new_account_create"><?php echo Mage::helper('sociallogin')->__('You do not have an account?'); ?> <a href="javascript:void(0);" onclick="return show_register();"><?php echo Mage::helper('sociallogin')->__('Create new account'); ?></a></div>
                        <div class="sl_clear"></div> 
                        <div id="forget_password_div" style="display: none">
                            <form id="forget_password_form" class="socialpopup_form">
                                <h4><?php echo Mage::helper('sociallogin')->__('Did you forget your password?'); ?></h4>

                                <span class="small_txt"><?php echo Mage::helper('sociallogin')->__('Enter your email address here to receive a password reset link.'); ?></span>
                                <label for="forget_email" class="required"><?php echo Mage::helper('sociallogin')->__('Email'); ?><em>*</em></label>
                                <div class="socialpopup-input-box">
                            <input class="" name="forget_password" clss="" id="forget_password" type="text">
                                    <div id="forget_password_error" class="popup_error_msg"></div>
                                    <div id="progress_image_forgot" style="display: none">
                        <img src="<?php echo $this->getSkinUrl('sociallogin/images/ajax-loader.gif'); ?>" alt="<?php echo Mage::helper('sociallogin')->__('please wait'); ?>">
                                    </div>  

                                     <div class="social_login_btn">
                                        <button type="button" onclick="return forgot_password();" class="button"><span><span><?php echo Mage::helper('sociallogin')->__('Send'); ?></span></span></button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="sl_clear"></div> 
                    </div>
                    <!-- register block -->
                    <div id="register_block" style="display: none;"> 
                        <div id="register_error" class="popup_error_msg" style="display: none;"></div>
                        <form id="form_validate" name="form_validate" class="socialpopup_form">
                            <h4><?php echo Mage::helper('sociallogin')->__('New customer? Sign up'); ?></h4>
                            <label for="first_name" class="required"><?php echo Mage::helper('sociallogin')->__('First name'); ?> <em>*</em></label>
                            <div class="socialpopup-input-box">
                                <input name="first_name" id="first_name" class="" title="<?php echo Mage::helper('sociallogin')->__('First name'); ?>" type="text">
                                <div id="first_register_error" class="popup_error_msg"></div>
                            </div>
                            <label for="last_name" class="required"><?php echo Mage::helper('sociallogin')->__('Last Name'); ?><em>*</em></label>
                            <div class="socialpopup-input-box">
                                <input name="last_name" id="last_name" class="" title="اسم العائلة" type="text">
                                <div id="last_register_error" class="popup_error_msg"></div>
                            </div>
                            <label for="email_register" class="required"><?php echo Mage::helper('sociallogin')->__('Email'); ?> <em>*</em></label>
                            <div class="socialpopup-input-box">
                                <input name="email_register" id="email_register" class="" title="<?php echo Mage::helper('sociallogin')->__('Email'); ?>" type="text">
                                <div id="email_register_error" class="popup_error_msg"></div>
                            </div> 
                            <label for="password_register" class="required"><?php echo Mage::helper('sociallogin')->__('Password'); ?><em>*</em></label>
                            <div class="socialpopup-input-box">
                                <input name="password_register" class="" id="password_register" title="<?php echo Mage::helper('sociallogin')->__('Password'); ?>" type="password">
                                <div id="password_register_error" class="popup_error_msg"></div>
                            </div>
                            <label for="confirm_password" class="required"><?php echo Mage::helper('sociallogin')->__('Confirm Password'); ?><em>*</em></label>
                            <div class="socialpopup-input-box">
                                <input name="confirm_password" value="" id="confirm_password" class="" title="<?php echo Mage::helper('sociallogin')->__('Confirm Password'); ?>" type="password">
                                <div id="confirm_register_error" class="popup_error_msg"></div>
                            </div>
                              <!--<?php if (!$helper->isDobShow()==0){?>
                                <label for="social_dob">تاريخ الميلاد</label>
                                <div class="socialpopup-input-box">
                                    <input class="" name="social_dob" title="تاريخ الميلاد" id="social_dob" placeholder="اليوم/الشهر/السنة" type="text">
                                    <div id="social_dob_error" class="popup_error_msg"></div>
                                </div>-->
                                <?php }?>
                                <?php //if (!$helper->isVATShow()==0){?>
                                <!-- <label for="VAT" class="required">VAT <em>*</em></label>
                                <div class="socialpopup-input-box">
                                    <input class="" name="social_dob" title="DOB" id="social_dob" placeholder="MM/DD/YYYY" type="text">
                                    <div id="social_dob_error" class="popup_error_msg"></div>
                                </div> -->
                                <?php //}?>
                                <!--<?php if (!$helper->isGenderShow()==0){?>
                                <label for="social_gender">الجنس</label>
                                <div class="socialpopup-input-box">
                                 <select name="social_gender" id="social_gender">
                                        <option value="1">ذكر</option>
                                        <option value="2">أنثى</option>
                                    </select>
                             <div id="social_gender_error" class="popup_error_msg"></div>
                                </div>
                               <?php }?>
                                <div class="socialpopup-input-box">
                               <?php //echo $this->getLayout()->createBlock('captcha/captcha')
                                //->setFormId('form_validate')
                                //->setImgWidht(230)
                                //->setImgHeight(50)
                                //->toHtml();
                                ?>
                               </div>-->
                            
                             

                                <div class="socialpopup-submit-box">
                                <div id="progress_image_register" style="display: none">
                                    <img src="<?php echo $this->getSkinUrl('sociallogin/images/ajax-loader.gif'); ?>" alt="loading please wait">
                                </div>  
                                <div class="social_login_btn">
                                    <button type="button" title="<?php echo Mage::helper('sociallogin')->__('Creat new account'); ?>" class="button" onclick="return sendRegister();" id="sregister"><span><span><?php echo Mage::helper('sociallogin')->__('Creat new account'); ?></span></span></button>
                                </div>
                            </div>
                        </form>
                        <div class="new_account_create"><?php echo Mage::helper('sociallogin')->__('Already have an account'); ?> <a href="javascript:void(0);" onclick="return show_login();"><?php echo Mage::helper('sociallogin')->__('Log in'); ?></a></div>
                    </div>
                    <!-- register block ends -->

                    <div id="twitter_block" style="display:none;">
                        <form id="social_tiw_login" class="socialpopup_form">
                            <h4><?php echo Mage::helper('sociallogin')->__('Please enter your email registered in Twitter'); ?></h4>
                            <label for="tw_email" class="required"><?php echo Mage::helper('sociallogin')->__('Email'); ?><em>*</em></label>
                            <div class="socialpopup-input-box">
                                <input id="tw_email" name="tw_email" class="input_linked required-entry validate-email twitter_popup_input" type="text">
                                <div id="twitter_error" class="popup_error_msg"></div>
                                <div class="social_login_btn">
                                    <button type="button" onclick="return twitter_check();" class="button twitter_popup_btn"><span><span><?php echo Mage::helper('sociallogin')->__('Submit'); ?></span></span></button>
                                </div>
                            </div>


                        </form>
                        <div class="new_account_create"><?php echo Mage::helper('sociallogin')->__('Email'); ?>لديك حساب؟ <a href="javascript:void(0);" onclick="return show_login();"><?php echo Mage::helper('sociallogin')->__('Login'); ?></a></div> 
                    </div>

                </div>

                <div id="all_social_iconbtn">
                    <span class="divider-or social_popup_sprite"><b>أو</b></span>
                    <h4><?php echo Mage::helper('sociallogin')->__('Log in by'); ?></h4>
                    <!-- Social login icons -->
                    <ul>
                                                    <!--Facebook button -->
                     <li id="login" class="sl_clearfix">
                    <a id="facebook_login" title="Facebook" onclick="fblogin();">  <span class="f_icon_left icon_left_grid"></span>    <button type="button" class="fb_login inner_social_grid" name="send">Facebook</button>   <span class="f_icon_right icon_right_grid"></span><img id="progress_image_facebooklogin" style="display:none" src="<?php echo $this->getSkinUrl('sociallogin/images/ajax-loader.gif'); ?>" alt="loading please wait"></a>  </li>
                                                    <!--Twitter button -->
                            <li class="sl_clearfix">  
                                <a onclick="show_twitter();" id="popup_twitter_email" title="Twitter"> <span class="t_icon_left icon_left_grid"></span> <button type="submit" class="twitter_login inner_social_grid" name="send"> Twitter </button> <span class="t_icon_right icon_right_grid"></span></a></li>
                                                    <!--Google button -->
                            <!-- <li class="sl_clearfix">  
                                <a onclick="javascript:location.href = 'http://demo004.net/sociallogin/index.php/googlepost/'" title="Google+"> <span class="gplus_icon_left icon_left_grid"></span> <button type="submit" class="google_login inner_social_grid" name="send"> Google+ </button> <span class="gplus_icon_right icon_right_grid"></span></a></li> -->
                                 <li class="sl_clearfix">  
            <a onclick="javascript:location.href ='<?php echo Mage::$this->getUrl('sociallogin/index/googlepost'); ?>'" title="Google+"> <span class="gplus_icon_left icon_left_grid"></span> <button type="submit" class="google_login inner_social_grid" name="send"> Google+ </button> <span class="gplus_icon_right icon_right_grid"></span></a>
        </li>
                                                    <!--Yahoo button -->
                            <!--<li class="sl_clearfix"> 
                             <a onclick="javascript:location.href = 'http://www.demo004.net/sociallogin/index.php/yahoopost/'" title="Yahoo"> <span class="yahoo_icon_left icon_left_grid"></span> <button type="submit" class="yahoo_login inner_social_grid" name="send"> Yahoo </button> <span class="yahoo_icon_right icon_right_grid"></span></a></li>-->
                                            </ul>
                </div>
                            </div>  
            <div class="sl_clear"></div>

        </div>
        <div class="sl_clear"></div>
    </div>
    </div>



    <!-- popup -->

    <script type="text/javascript">
            function sendRegister() {
            var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
            var email_value = document.getElementById("email_register").value;
            var password_value = document.getElementById('password_register').value;
            var first_name = document.getElementById("first_name").value;
            var last_name = document.getElementById("last_name").value;
            var confirm_password = document.getElementById("confirm_password").value;
            var pattern = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;
            document.getElementById('register_error').style.display = "none";
            if (first_name == '') {
                $('first_name').addClassName("validation-failed");
                $('first_register_error').innerHTML = '<div style="" id="advice-required-entry-first-name" class="validation-advice">Required Entry</div>';
                    return false;
                     } else {
                             $('first_name').removeClassName("validation-failed");
                             $('first_register_error').innerHTML = '';}
                            if (last_name == '') {
                             $('last_name').addClassName("validation-failed");
                             $('last_register_error').innerHTML = '<div style="" id="advice-required-entry-last-name" class="validation-advice">Required Entry</div>';
                                 return false;
                                } else {
                                         $('last_name').removeClassName("validation-failed");
                                         $('last_register_error').innerHTML = '';
                                            }
                                            if (email_value == '')
                                            {
                                                $('email_register').addClassName("validation-failed");
                                                $('email_register_error').innerHTML = '<div style="" id="advice-required-entry-email-register" class="validation-advice">Required Entry</div>';
                                                return false;
                                            } else if (reg.test(email_value) == false) {
                                                $('email_register').addClassName("validation-failed");
                                                $('email_register_error').innerHTML = '<div style="" id="advice-required-entry-email-register" class="validation-advice">Invalid Email Address</div>';
                                                return false;
                                            } else {
                                                $('email_register').removeClassName("validation-failed");
                                                $('email_register_error').innerHTML = '';
                                            }


    //password 
                                            if (password_value == '')
                                            {
                                                $('password_register').addClassName("validation-failed");
                                                $('password_register_error').innerHTML = '<div style="" id="advice-required-entry-password-register" class="validation-advice">Required Entry</div>';
                                                return false;
                                            }
                                            if (password_value.length < 6)
                                            {
                                                $('password_register').addClassName("validation-failed");
                                                $('password_register_error').innerHTML = '<div style="" id="advice-required-entry-password-register" class="validation-advice">Password cannot be less than 6</div>';
                                                return false;
                                            } else {
                                                $('password_register').removeClassName("validation-failed");
                                                $('password_register_error').innerHTML = '';
                                            }
                                            if (confirm_password == '')
                                            {
                                                $('confirm_password').addClassName("validation-failed");
                                                $('confirm_register_error').innerHTML = '<div style="" id="advice-required-entry-confirm-password" class="validation-advice">Required Entry</div>';
                                                return false;
                                            } else {
                                                $('confirm_password').removeClassName("validation-failed");
                                                $('confirm_register_error').innerHTML = '';
                                            }
                                            if (confirm_password != password_value)
                                            {
                                                $('confirm_password').addClassName("validation-failed");
                                                $('confirm_register_error').innerHTML = '<div style="" id="advice-required-entry-confirm-password" class="validation-advice">Password Is Required</div>';
                                                return false;
                                            }


                                                
                                            $$('.popup_error_msg').each(function(msg) {
                                                msg.innerHTML = '';
                                            });

                                            document.getElementById('progress_image_register').style.display = "block";
    var ajaxurl = "<?php echo Mage::helper('customer')->getRegisterPostUrl() ?>";
                                            new Ajax.Request(ajaxurl, {
                                                method: 'post',
                                                parameters: {email: email_value, password: password_value, firstname: first_name, lastname: last_name, confirmation: confirm_password//, dob: social_dob, gender: social_gender, taxvat: //social_vat, captcha: captcha_user_create
                                                },
                                                onSuccess: function(register_success) {

                                                    document.getElementById('progress_image_register').style.display = "none";
                                                    var pattern_url = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;
                                                    var url_value = pattern_url.test(register_success.responseText);

                                                    if (url_value == false)
                                                    {
                                                        document.getElementById('register_error').style.display = "block";
                                                        document.getElementById('register_error').innerHTML = register_success.responseText;
                                                        window.location.href = '<?php echo Mage::getUrl('customer/account');  ?>';
                                                        return false;
                                                    } else
                                                    {
                                                        window.location.href = '<?php echo Mage::getUrl('customer/account');  ?>';
                                                        // window.location.href = register_success.responseText;
                                                    }
                                                }
                                            });
                                        }


                                        function show_twitter() {
                                            document.getElementById('twitter_block').style.display = "block";
                                            document.getElementById('register_block').style.display = "none";
                                            document.getElementById('login_block').style.display = "none";
                                            document.getElementById('forget_password_div').style.display = "none";
                                            return false;
                                        }

                                        function show_password() {
                                            Effect.toggle('forget_password_div', 'slide', {delay: 0.5});
                                            document.getElementById('register_block').style.display = "none";
                                            document.getElementById('twitter_block').style.display = "none";
                                            $('forget_password').setValue('');
                                            return false;
                                        }

                                        function show_register()
                                        {
                                            document.getElementById('login_block').style.display = "none";
                                            document.getElementById('forget_password_div').style.display = "none";
                                            document.getElementById('register_block').style.display = "block";
                                            document.getElementById('twitter_block').style.display = "none";
                                            fme_clearall();
                                            if (typeof window.innerHeight != 'undefined') {
                                                document.getElementById('header_logo_Div').style.top = Math.round(document.body.offsetTop + ((window.innerHeight - document.getElementById('header_logo_Div').getHeight())) / 2) + 'px';
                                                document.getElementById('header_logo_Div').style.left = Math.round(document.body.offsetLeft + ((window.innerWidth - document.getElementById('header_logo_Div').getWidth())) / 2) + 'px';
                                            } else {
                                                document.getElementById('header_logo_Div').style.top = Math.round(document.body.offsetTop + ((document.documentElement.offsetHeight - document.getElementById('header_logo_Div').getHeight())) / 2) + 'px';
                                                document.getElementById('header_logo_Div').style.left = Math.round(document.body.offsetLeft + ((document.documentElement.offsetWidth - document.getElementById('header_logo_Div').getWidth())) / 2) + 'px';
                                            }
                                            return false;
                                        }
                                        function show_login()
                                        {
                                            document.getElementById('register_block').style.display = "none";
                                            document.getElementById('forget_password_div').style.display = "none";
                                            document.getElementById('login_block').style.display = "block";
                                            document.getElementById('twitter_block').style.display = "none";
                                            fme_clearall();
                                            if (typeof window.innerHeight != 'undefined') {
                                                document.getElementById('header_logo_Div').style.top = Math.round(document.body.offsetTop + ((window.innerHeight - document.getElementById('header_logo_Div').getHeight())) / 2) + 'px';
                                                document.getElementById('header_logo_Div').style.left = Math.round(document.body.offsetLeft + ((window.innerWidth - document.getElementById('header_logo_Div').getWidth())) / 2) + 'px';
                                            } else {
                                                document.getElementById('header_logo_Div').style.top = Math.round(document.body.offsetTop + ((document.documentElement.offsetHeight - document.getElementById('header_logo_Div').getHeight())) / 2) + 'px';
                                                document.getElementById('header_logo_Div').style.left = Math.round(document.body.offsetLeft + ((document.documentElement.offsetWidth - document.getElementById('header_logo_Div').getWidth())) / 2) + 'px';
                                            }
                                        }

                         function sendLogin()
                                        {
                                            var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
                                            var email = document.getElementById("email").value;
                                            var password = document.getElementById('password').value;
                                            if (email == '')
                                            {
                                                $('email').addClassName("validation-failed");
                                                $('email_error').innerHTML = '<div style="" id="advice-required-entry-email" class="validation-advice">Required Entry</div>';
                                            } else if (reg.test(email) == false) {
                                                $('email').addClassName("validation-failed");
                                                $('email_error').innerHTML = '<div style="" id="advice-required-entry-email" class="validation-advice">Enter Email Address</div>';
                                                return false;
                                            }

                                            if (password == '')
                                            {
                                                $('password').addClassName("validation-failed");

                                                $('password_error').innerHTML = '<div style="" id="advice-required-entry-password" class="validation-advice">Required Entry</div>';
                                                return false;
                                            }
                                            if (email == '' || password == '')
                                            {
                                                $('email').addClassName("validation-failed");
                                                $('password').addClassName("validation-failed");
                                                $('password_error').innerHTML = '<div style="" id="advice-required-entry-email" class="validation-advice">Enter Valid Email</div>';
                                                return false;
                                            }
                                            else
                                            {
                                                document.getElementById('progress_image_login').style.display = "block";
                                                $('email').removeClassName("validation-failed");
                                                $('password').removeClassName("validation-failed");
                                                document.getElementById('email_error').innerHTML = "";
                                                document.getElementById('password_error').innerHTML = "";
         //var ajaxurl ='<?php echo  Mage::getUrl("sociallogin/index/ajaxlogin"); ?>'
          var ajaxurl = '<?php echo Mage::helper("customer")->getLoginPostUrl()?>';

          new Ajax.Request(ajaxurl, {
                                method: 'post',
                                parameters: {username: email, password: password},
                                 onSuccess: function(transport) {
                                          document.getElementById('progress_image_login').style.display = "none";
                                             var pattern_url = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;
                                            var url_value = pattern_url.test(transport.responseText);

                                            if (url_value == true)
                                                        {
                    // window.location.href = '<?php echo Mage::getUrl() ?>';
                    window.location.reload(); 
                                //window.location.href = transport.responseText;
                                                        }
                                                     else
                                                        {
                                                            document.getElementById('password_error').innerHTML = transport.responseText;
                                                        }
                                                    }
                                                });
                                            }
                                        }
    </script>

  <!--  <div id="fb-root">


   </div> -->
    <div class=" fb_reset" id="fb-root"></div>
    
    <script type="text/javascript">
        //facebook login
        var app_id = '<?php echo $app_idDN ?>';
        function fblogin() {
            FB.login(function(response) {
                FB.getLoginStatus(function(response) {
                    if (response.status === 'connected') {
                        document.getElementById('progress_image_facebooklogin').style.display = "block";
                        login();
                    }
                });
            }, {scope: 'email'});
            return false;
        }

        window.fbAsyncInit = function() {
            FB.init({appId: app_id, status: true, cookie: true, xfbml: true});
            /* All the events registered */
            FB.Event.subscribe('auth.login', function(response) {
                // do something with response
                login();
            });
        };
        (function() {

            var e = document.createElement('script');
            e.type = 'text/javascript';
            e.src = document.location.protocol +
                    '//connect.facebook.net/en_US/all.js';
            e.async = true;
            document.getElementById('fb-root').appendChild(e);
        }());


        function login() {
            FB.api('/me', function(response) {
 
                window.location.href = "<?php echo Mage::getUrl('sociallogin/index/fblogin')?>"
            });
        }

        function forgot_password()
        {
            var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
            var email_value = document.getElementById("forget_password").value;
            var password_value = document.getElementById('password').value;
            if (email_value == '')
            {
                $('forget_password').addClassName("validation-failed");
                $('forget_password_error').innerHTML = '<div style="" id="advice-required-entry-forgot-password" class="validation-advice">Required Entry.</div>';
            } else if (reg.test(email_value) == false) {
                $('forget_password').addClassName("validation-failed");
                $('forget_password_error').innerHTML = '<div style="" id="advice-required-entry-forgot-password" class="validation-advice">Required Entry.</div>';
                return false;
            } else {
                document.getElementById('forget_password_error').innerHTML = "";
                document.getElementById('progress_image_forgot').style.display = "block";
    var ajaxurl = "<?php echo Mage::getUrl('customer/account/forgotPasswordPost') ?>";
                new Ajax.Request(ajaxurl, {
                    method: 'post',
                    parameters: {email: email_value},
                    onSuccess: function(forgot_password) {
                        document.getElementById('progress_image_forgot').style.display = "none";
                        if (forgot_password.responseText == 'sent')
                        {
                            document.getElementById('forget_password_error').innerHTML = "If there is an account associated with  " + email_value + " you will receive an email with a link to reset your password";
                        } else {
                            document.getElementById('forget_password_error').innerHTML = forgot_password.responseText;
                            return false;
                        }
                    }
                });
            }
        }

        function twitter_check()
        {
            var email_value = document.getElementById("tw_email").value;
            var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;




            if (email_value == '')
            {
                $('tw_email').addClassName("validation-failed");
                $('twitter_error').innerHTML = '<div style="" id="advice-required-entry-forgot-password" class="validation-advice">Required Entry.</div>';
            } else if (reg.test(email_value) == false) {
                $('tw_email').addClassName("validation-failed");
                $('twitter_error').innerHTML = '<div style="" id="advice-required-entry-forgot-password" class="validation-advice">Required Entry</div>';
                return false;
            } else {
                document.getElementById('twitter_error').innerHTML = "";
                $('tw_email').removeClassName("validation-failed");
                
                var ajaxurl = "<?php echo Mage::getUrl('sociallogin/index/twitterpost')?>";
                new Ajax.Request(ajaxurl, {
                    method: 'POST',
                    parameters: {email: email_value},
                    onSuccess: function(twitter_success_give) {
                        var pattern_url = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;
                        var url_value = pattern_url.test(twitter_success_give.responseText);
                        if (url_value == false)
                        {
                            document.getElementById('twitter_error').innerHTML = twitter_success_give.responseText;
                            return false;
                        } else
                        {
                            //alert(twitter_success_give.responseText);
                            window.location.href = twitter_success_give.responseText;
                        }
                    }
                });
            }
        }

        // $('socialpopup_main_div').observe('keypress', socialkeypressHandler);
        // function socialkeypressHandler(event) {
        //     var key = event.which || event.keyCode;
        //     switch (key) {
        //         default:
        //             break;
        //         case Event.KEY_RETURN:
        //             sendLogin();
        //             break;
        //     }
        // }

        // $('social_popup_main').observe('keypress', socialsignupkeypressHandler);
        // function socialsignupkeypressHandler(event) {
        //     var key = event.which || event.keyCode;
        //     switch (key) {
        //         default:
        //             break;
        //         case Event.KEY_RETURN:
        //             sendRegister();
        //             break;
        //     }
        // }

    </script>

    </div>

