<?php /** @var $this Cminds_Multiwishlist_Block_Customer_Sidebar_Multiwishlist */?>

<div class="block block-wishlist">
    <div class="block-title">
        <strong><span><?php echo $this->getTitle(); ?></span></strong>
    </div>
    <?php foreach ($this->getWishlists() as $wishlist): ?>
    <div class="block-content">
        <?php if ($this->hasWishlists()): ?>
            <ol class="mini-products-list" id="wishlist-sidebar">
                <?php foreach ($this->getItemsCollection($wishlist) as $_item): ?>
                    <?php $product = $_item->getProduct(); ?>
                    <li class="item">
                        <a href="<?php echo $this->getProductUrl($_item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize(50); ?>" width="50" height="50" alt="<?php echo $this->escapeHtml($product->getName()) ?>" /></a>
                        <div class="product-details">
                            <a href="<?php echo $this->getItemRemoveUrl($_item) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove This Item')) ?>" onclick="return confirm('<?php echo Mage::helper('core')->quoteEscape($this->__('Are you sure you would like to remove this item from the wishlist?'), true) ?>');" class="btn-remove"><?php echo $this->__('Remove This Item') ?></a>
                            <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->escapeHtml($product->getName()) ?></a></p>
                            <?php echo $this->getPriceHtml($product, false, '-wishlist') ?>
                            <?php if ($product->isSaleable() && $product->isVisibleInSiteVisibility()): ?>
                                <a href="<?php echo Mage::helper('cminds_multiwishlist')->getAddToCartUrl($_item) ?>" class="link-cart"><?php echo $this->__('Add to Cart') ?></a>
                            <?php endif; ?>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('wishlist-sidebar');</script>
            <div class="actions">
                <a href="<?php echo $this->helper('cminds_multiwishlist')->getListUrl($_item->getId()) ?>"><?php echo $this->__('Go to %s Wishlist', $_item->getName()) ?></a>
            </div>
        <?php else: ?>
            <p class="empty"><?php echo $this->__('You have not wishlists.') ?></p>
        <?php endif ?>
    </div>
    <?php endforeach; ?>
    <a href="<?php echo $this->getIndexUrl() ?>"><?php echo $this->__('Go to All Wishlist') ?></a>
</div>
