<?php
$title =  get_field('title','option');
$description =  get_field('description','option');
$label =  get_field('label','option');
$link =  get_field('link','option');
$newtab = '';
$catLink = "javascript:void(0);";
if($link){
    $newtab = 'target="_blank"';
    $catLink = check_custom_rts($link);
} ?>
<?php 
if(have_rows('banner_section','option')): ?>
<div class="inner-banner rts-banner owl-carousel" style="display: none">  
    <?php while(have_rows('banner_section','option')): the_row(); ?>  
        <?php 
            $largeImage = get_sub_field('large_image','option');
            $smallImage = get_sub_field('small_image','option');
            $title =  get_sub_field('title','option');
            $description =  get_sub_field('description','option');
            $label =  get_sub_field('label','option');
            $link =  get_sub_field('link','option');
            $newtab = '';
            $catLink = "javascript:void(0);";
            if($link){
                $newtab = 'target="_blank"';
                $catLink = check_custom_rts($link);
            } 
        ?>  
        <div class="item">
            <div class="description">
                <h2><?php echo $title;?></h2>
                <p><?php echo $description;?></p>
                <a href="<?php echo $catLink;?>" <?php echo $newtab; ?> class="readmore"><?php echo $label;?></a>
                <div class="image"><img src="<?php echo $smallImage['url'];?>" alt="<?php echo $label;?>"></div>
            </div>
            <div class="large-image">
                <img src="<?php echo $largeImage['url']; ?>" alt="<?php echo $label;?>" />
            </div>
        </div>
    <?php endwhile;?>
</div> 
<?php endif;?>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('.inner-banner').owlCarousel({
            loop: true,
            margin:0,
            items:1,
            nav: true,
            dots:false
        });  
    });
</script>
<?php
    function check_custom_rts($arglink)
    {
        $httpPost = strpos($arglink,'http');
        if(strlen($arglink)==0)
        {
            $link = 'javascript:;';
        }
        elseif(strlen($httpPost)==0)
        {
           $link = 'http://'.$arglink;
        }
        else
        {
           $link = $arglink;
        }
        return $link;
    }
?>
